### ISSUE TITLE
balanced triads

### ISSUE THREAD

**Issue by geoHeil** [neo4j/graph-data-science#101]
Hi,

I would be interested in https://neo4j.com/docs/graph-algorithms/current/labs-algorithms/balanced-triads/  - the balanced tirads algorithm. However, it is not part of the GDS - only the now deprecated graph algorithms.

In fact:

- https://github.com/neo4j/graph-data-science/commit/3f1b03fcd326bf4f97f682023f934bb8c39d70d2
- https://github.com/neo4j/graph-data-science/commit/c569e71d497330fe65e05cd17a730e66acc68ba7

explicitly remove it. What was the reason for this?
Would it be possible to add it again? Would you be open to a contribution porting the old implementation over to GDS (I might have some time to work on it)?

**Comment by Mats-SX** [comment]
Hello @geoHeil and thanks for reaching out.

The reason the Balanced Triads algorithm was not ported from Graph Algorithms to GDS is that the implementation was not working correctly. Our focus when we ported the library was on a different set of algorithms, and reworking Balanced Triads was out of scope. We are not planning on adding it in any currently set roadmap.

If you would like to use the Balanced Triads algorithm with GDS, our best recommendation is to try to use our [Pregel API](https://neo4j.com/docs/graph-data-science/current/algorithms/pregel-api/) to implement it and add this to your installation of GDS. If you would like, you can submit this implementation as a pull request to this repository and then we could have a look at it and provide some feedback; potentially it could be a candidate to include in the library.

I hope this clears things up for you!
All the best
Mats

**Comment by FlorentinD** [comment]
@geoHeil to give you a bit of starting point, there is only an unweighted `getNeighbours()` in `NodeCentricContext` at the moment. Also there already exists a Triangle-Count [implementation](https://github.com/neo4j/graph-data-science/blob/master/examples/pregel-example/src/main/java/org/neo4j/graphalgo/beta/pregel/triangleCount/TriangleCountPregel.java) using the Pregel-API, which can be adapted to your needs.
