### ISSUE TITLE
ArticleRank docs are outdated

### ISSUE THREAD

**Issue by BalmungSan** [neo4j/graph-data-science#102]
If you take a look at the [documentation](https://neo4j.com/docs/graph-data-science/1.5/algorithms/article-rank/) of **ArticleRank** for the `1.5.0` version, and try to replicate the example you will find two problems.

The first one is:

> **Neo.ClientError.Procedure.ProcedureCallFailed**
> Failed to invoke procedure `gds.alpha.articleRank.stream`: Caused by: java.lang.IllegalArgumentException: Unexpected configuration key: iterations (Did you mean [maxIterations]?)

Which is not a big deal since it is easy to see and fix the error thanks to the useful message.
However, after fixing this we would get the following results:

Name | ArticleRank
-- | --
Paper 0 | 0.7561931365286
Paper 1 | 0.5640594441909343
Paper 2 | 0.306357501167804
Paper 4 | 0.27750000506639483
Paper 3 | 0.22862500101327898
Paper 5 | 0.15000000000000002
Paper 6 | 0.15000000000000002

Which is very different from the ones shown in the documentation.

Name | ArticleRank
-- | --
Paper 0 | 0.34616300000000005
Paper 1 | 0.319422
Paper 4 | 0.213733
Paper 2 | 0.21089400000000003
Paper 3 | 0.18026850000000003
Paper 5 | 0.15000000000000002
Paper 6 | 0.15000000000000002

Or is this a bug with the implementation?

**Comment by vnickolov** [comment]
@BalmungSan thank you for pointing this out, we are going to look into it.
There is a fair chance the results in the documentation to be outdated since this algorithm is in the `alpha` space.
