### ISSUE TITLE
Model Catalog documentation

### ISSUE THREAD

**Issue by alenegro81** [neo4j/graph-data-science#104]
The page about model catalog in the GDS documentation (https://neo4j.com/docs/graph-data-science/current/model-catalog/model-catalog/) indicates two different set of procedures. In the summary (where is correct) it states:

gds.beta.model.exists
gds.beta.model.list
gds.beta.model.drop

While in the examples "beta" disappear (and in the version 1.5.0 "beta" should be there). Moreover, should be stated that in the community it is not possible to store more than one model or (even better) generate an error upfront. 
Knowing it after 10 hours of computation that cannot be done is a bit "uncomfortable" :-)

**Comment by Mats-SX** [comment]
@alenegro81 Thank you for reporting this! We will make sure to fix the documentation and will notify here when it has been corrected.

I have also added the suggestion for checking the availability of registering a model in the catalog before we compute -- a very good idea!

**Comment by FlorentinD** [comment]
Since `1.6` we check if the model can be stored beforehand. I will close this issue as all suggestions seem to be addressed.
