### ISSUE TITLE
louvain alg

### ISSUE THREAD

**Issue by yysirs** [neo4j/graph-data-science#106]
if i have node type: compony third_compony
rel type: trade,subcompony
how to use louvain alg to find the community or scc?
beginner please help.

**Comment by AliciaFrame** [comment]
Check out the documentation on [Native Projections](https://neo4j.com/docs/graph-data-science/current/management-ops/native-projection/) (loading a named graph by specifying node and relationship types), or [Anonymous Graphs](https://neo4j.com/docs/graph-data-science/current/management-ops/anonymous-graph/) (loading data & executing an algorithm in a single command).

If you're just looking for examples and tutorials to get started, I'd check out our browser guide - just type `:play graph-data-science` in Neo4j browser, and you'll get a step by step tutorial with examples of how to use the library, load data, and call algorithms.

For your specific question, if you want to use a named graph, it will look something like this:

with a **named graph**:
```
call gds.graph.create('my-graph',['compony','third_compony'],['trade','subcompony']);

call gds.louvain.stream('my-graph');
```

Or with an *anonymous* graph:
```
call gds.louvain.stream({
     nodeProjection:['compony','third_compony'],
     relationshipProjection:['trade','subcompony']
})
```
