### ISSUE TITLE
Failed to invoke procedure `gds.alpha.scc.write`: Caused by: java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by strangeman375** [neo4j/graph-data-science#110]
Hi.
I've got an error:
Failed to invoke procedure `gds.alpha.scc.write`: Caused by: java.lang.ArrayIndexOutOfBoundsException: -1

Version of Neo4j: 3.5.26
Lib versions:
neo4j-graph-algorithms-3.5.11.0
neo4j-graph-algorithms-3.5.14.0
neo4j-graph-data-science-1.1.6

Just now i'm trying to collect additional info.
Neo4j log do not contain error and stack trace.

Give me some advice, how to collect more info about error?

**Comment by Mats-SX** [comment]
Hi @strangeman375 and thanks for raising this issue! I see that I'm a bit late to the party and that #112 is already addressing this issue. I've had a look at that solution and it seems from your emoji reactions that it does solve what you have reported. Is that correct?

Assuming it does fix the issue, I'll focus on getting that contribution merged and then we will ship a fix in an upcoming patch.

**Comment by strangeman375** [comment]
Hi @Mats-SX!
Yes, #112 solves my problem.
Thank you.
