### ISSUE TITLE
nodeSimilarity p50 median calculated wrong

### ISSUE THREAD

**Issue by albert-kevin** [neo4j/graph-data-science#115]
Hi,
I believe to have found a bug in the Node Similarity algorithm Jaccard.
When I run a CALL gds.nodeSimilarity.write(...) it output statistics data and I believe P50 is mistakenly calculated.
![image](https://user-images.githubusercontent.com/15119906/120495222-c9b0b080-c3bc-11eb-9025-722cb9b93993.png)
p50 should be 0.547...
GDS v1.5.2,
Neo4j v4.2.6

**Comment by vnickolov** [comment]
Hi @albert-kevin, 

Thank you for raising this, can you please:

1. Try out the GDS 1.6.0 release
2. Share details on the graph that you used so we can reproduce and inspect the issue.

Thank you in advance.

**Comment by s1ck** [comment]
@albert-kevin Thanks for reporting this. Which library are you using to compute the histogram? We use [HdrHistogram](https://github.com/HdrHistogram/HdrHistogram). A simple test gives us the `0.42` for the given input data. Is there maybe some loss in precision in your histogram implementation?

```
    @Test
    void histogramTest() {
        var values = List.of(0.111111, 0.6666667, 0.6666667, 0.428571, 0.428571, 0.6666667);
        var histogram = new DoubleHistogram(HISTOGRAM_PRECISION_DEFAULT);
        values.forEach(histogram::recordValue);
        System.out.println(histogram.getValueAtPercentile(50)); // prints 0.4285712242126465
    }
```

**Comment by albert-kevin** [comment]
here is the result I used with Python module 'Pandas'
![image](https://user-images.githubusercontent.com/15119906/120513837-f076e300-c3cc-11eb-8711-04b5851e66c4.png)

**Comment by AliciaFrame** [comment]
It looks like Pandas is using the average of the 3rd and 4th values in the data set, while the library GDS uses takes the 3rd value as the closest observation.

Neither one is *wrong* but we can always provide clarity on how percentiles are calculated. 

For a fun exercise, you can use [this calculator](https://www.wessa.net/rwasp_percentiles.wasp) to show 8(!) different ways of calculating percentiles:
![image](https://user-images.githubusercontent.com/48333261/120527212-12aa3a00-c3a8-11eb-8274-fe08db53941b.png)

**Comment by albert-kevin** [comment]
I will accept this, I got confused by percentile 50 meaning the same as the median.
where you sort the values and pick the value right in between 50% of the values left and 50% of the values right,
if the number of values are an even amount then you simply take the average of the two middle values.
I did not know Alicia, this is interesting, my apologies to bother with thinking this was a bug of some sort since it looks as if it always selects the 25th percentile... thank you all once again, feel free to close this ticket
