### ISSUE TITLE
How to install Graph Data Science (GDS) library embedded in Java applications

### ISSUE THREAD

**Issue by xiz675** [neo4j/graph-data-science#117]
Hi friends, 

I have a similar setting to this issue but different error: https://github.com/neo4j/graph-data-science/issues/91#issue-741990816

1. I downloaded graph-data-science jar and put it under plugins folder;
2. I added these two lines to neo4j.conf
```
dbms.security.procedures.unrestricted=gds.*
dbms.security.procedures.whitelist=gds.*
```
3. I started the server in java code:
![屏幕快照 2021-06-18 下午10 01 04](https://user-images.githubusercontent.com/32505316/122633975-49fb3500-d090-11eb-9ee8-07e88b07db4c.png)

Then I got an error when starting the embedded database in Java :
![屏幕快照 2021-06-18 下午10 03 33](https://user-images.githubusercontent.com/32505316/122633984-554e6080-d090-11eb-89c1-7c6e077d79f9.png)

**Comment by xiz675** [comment]
I downloaded the latest version of graph-data-science jar (1.6.1), then a different error poped out 
![屏幕快照 2021-06-19 上午12 44 26](https://user-images.githubusercontent.com/32505316/122635263-b75e9400-d097-11eb-9760-1c04f5563861.png)

**Comment by s1ck** [comment]
Hey @xiz675 

Please have another look at https://github.com/neo4j/graph-data-science/issues/91

Did you register the procedures you want to use on server startup as described by Mats in https://github.com/neo4j/graph-data-science/issues/91#issuecomment-727895099 ?

**Comment by xiz675** [comment]
I tried the latest version of Neo4j and the issue solved
