### ISSUE TITLE
Index -1 out of bounds for length 28088 when calling node2vec in write mode and relationshipWeightProperty set

### ISSUE THREAD

**Issue by drsealks** [neo4j/graph-data-science#119]
neo4j kernel version is 4.2.6
DS lib version is 1.6

Originally, the issue has been reported [here](https://community.neo4j.com/t/index-1-out-of-bounds-for-length-28088-when-calling-node2vec-in-write-mode-and-relationshipweightproperty-set/40286).

What I have is a simple bipartite graph, with main nodes and a set of properties(represented as nodes) that the main nodes are connected to. And I want to run node2vec to get node embeddings. For that, I create a native projection in the following way:

```
call gds.graph.create(
    "my-graph",
    "*",
    {
        DATA: {
            type: "DATA",
            orientation: "UNDIRECTED",
            properties : {
                weight: "weight"
            }
        }
    },
    {
        relationshipProperties:[{DATA:"weight"}]
    }
)
YIELD graphName, nodeCount, relationshipCount;
```
So it is a simple graph with a single relationship type. Notice, the native projection also utilizes the `weight` property of each relation.

To actually adjust the embeddings, I run the following:

```
CALL gds.beta.node2vec.write('er-graph', {
    embeddingDimension: 64,
    writeProperty: "node2vec",
    concurrency: 4,
    iterations: 200,
    inOutFactor: 1,
    returnFactor: 0.5,
    walksPerNode: 20,
    walkLength: 10,
})
```
Please, note this one does not try to use relationship weights. When I call it, the procedure runs as expected and generates some reasonable embeddings.
However, when I run the node2vec with the `relationshipWeightProperty` property set, I get an error:
```
CALL gds.beta.node2vec.write('er-graph', {
    embeddingDimension: 64,
    writeProperty: "node2vec",
    concurrency: 4,
    iterations: 200,
    inOutFactor: 1,
    returnFactor: 0.5,
    walksPerNode: 20,
    walkLength: 10,
    relationshipWeightProperty:"weight"
})
```

The following log is obtained 

```
neo4j          | 2021-06-23 13:13:58.296+0000 ERROR Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: Lexical error at line 17, column 46.  Encountered: <EOF> after : "", reference b95a99d5-7c8f-4b0a-90fb-0d321abbd89e.
neo4j          | 2021-06-23 13:14:07.870+0000 INFO  [node-store-scan-0] LOADING 16%
neo4j          | 2021-06-23 13:14:07.871+0000 INFO  Node Store Scan (NodeCursorBasedScanner): Imported 28,088 records and 0 properties from 415 KiB (425,880 bytes); took 0.002 s, 17,157,157.68 Nodes/s, 248 MiB/s (260,142,776 bytes/s) (per thread: 4,289,289.42 Nodes/s, 62 MiB/s (65,035,694 bytes/s))
neo4j          | 2021-06-23 13:14:07.905+0000 INFO  [relationship-store-scan-3] LOADING 41%
neo4j          | 2021-06-23 13:14:07.920+0000 INFO  [relationship-store-scan-0] LOADING 70%
neo4j          | 2021-06-23 13:14:07.920+0000 INFO  [relationship-store-scan-1] LOADING 100%
neo4j          | 2021-06-23 13:14:07.927+0000 INFO  Relationship Store Scan (RelationshipScanCursorBasedScanner): Imported 140,368 records and 140,368 properties from 2334 KiB (2,390,880 bytes); took 0.053 s, 2,659,020.13 Relationships/s, 43 MiB/s (45,290,935 bytes/s) (per thread: 664,755.03 Relationships/s, 11057 KiB/s (11,322,733 bytes/s))
neo4j          | 2021-06-23 13:14:07.928+0000 INFO  [neo4j.BoltWorker-3 [bolt] [/172.18.0.1:57292] ] LOADING 
neo4j          | 2021-06-23 13:14:07.936+0000 INFO  [neo4j.BoltWorker-3 [bolt] [/172.18.0.1:57292] ] LOADING Actual memory usage of the loaded graph: 22 MiB
neo4j          | Exception in thread "Thread-17" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 28088
neo4j          |        at org.neo4j.graphalgo.core.utils.paged.HugeIntArray$SingleHugeIntArray.get(HugeIntArray.java:280)
neo4j          |        at org.neo4j.graphalgo.core.huge.TransientAdjacencyList.degree(TransientAdjacencyList.java:154)
neo4j          |        at org.neo4j.graphalgo.core.huge.HugeGraph.degree(HugeGraph.java:316)
neo4j          |        at org.neo4j.gds.embeddings.node2vec.RandomWalk$RandomWalkTask.walkOneStep(RandomWalk.java:275)
neo4j          |        at org.neo4j.gds.embeddings.node2vec.RandomWalk$RandomWalkTask.walk(RandomWalk.java:261)
neo4j          |        at org.neo4j.gds.embeddings.node2vec.RandomWalk$RandomWalkTask.run(RandomWalk.java:244)
neo4j          |        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
neo4j          |        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
neo4j          |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
neo4j          |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
neo4j          |        at java.base/java.lang.Thread.run(Thread.java:829)
neo4j          |        at org.neo4j.internal.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:110)
neo4j          |        Suppressed: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 28088
neo4j          |                ... 12 more
neo4j          |        Suppressed: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 28088
neo4j          |                ... 12 more
neo4j          |        Suppressed: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 28088
neo4j          |                ... 12 more
neo4j          | 2021-06-23 13:15:56.016+0000 INFO  [neo4j.BoltWorker-3 [bolt] [/172.18.0.1:57292] ] Node2Vec :: Training :: Start
neo4j          | 2021-06-23 13:15:56.016+0000 INFO  [neo4j.BoltWorker-3 [bolt] [/172.18.0.1:57292] ] Node2Vec :: Iteration 1 :: Start
neo4j          | 2021-06-23 13:15:56.016+0000 INFO  [neo4j.BoltWorker-3 [bolt] [/172.18.0.1:57292] ] Node2Vec :: Iteration 1 :: Finished
.
.
.
neo4j          | 2021-06-23 13:15:56.239+0000 INFO  [neo4j.BoltWorker-3 [bolt] [/172.18.0.1:57292] ] WriteNodeProperties :: Finished
```
So as you can see, there are some weird exceptions, and the iterations start and stop almost immediately. The embeddings produced also are not being optimized. They get initialized with random values and never change.

Am I trying to use weighted transition in the wrong way?

**Comment by FlorentinD** [comment]
Hey @drsealks,
thank you for reporting the issue! The `-1` means, that we try to get the degree of a non-existing node.
Your node2vec call looks correct. My guess is, that our implementation does not support negative relationship weights. Could you check if there have negative relationship weights?

On a side note: you don't need to specify the relationship property twice in your `graph.create`. `relationshipProperties:[{DATA:"weight"}]` loads `weight` the for _all_ relationship projections and renames the property to `DATA`.
You can simply remove the global `relationshipProperties` as you specified `weight` already in your projection of `DATA`

**Comment by drsealks** [comment]
Hi @FlorentinD 

Thanks for your prompt reply - appreciate it so much! I do not have any negative weights in the db:
```
match ()-[r:DATA]-() with r.weight as weights return min(weights)
```
returns this 
```
╒════════════════════╕
│"min(weights)"      │
╞════════════════════╡
│0.011764705882352941│
└────────────────────┘
```

Also, thanks for your side note!

**Comment by FlorentinD** [comment]
We do L1-normalize the  weights internally, so it is definitely a bug. 
If you cannot wait for a fix, you could try using [FastRP](https://neo4j.com/docs/graph-data-science/current/algorithms/fastrp/#algorithms-embeddings-fastrp) or [GraphSAGE](https://neo4j.com/docs/graph-data-science/current/algorithms/graph-sage/) for your node embeddings.

**Comment by drsealks** [comment]
Thanks for this. If I happen to have a small sample graph for the problem, I will make sure to post it here. 
Keep up the good work guys, using your DS library is a pleasure!

**Comment by FlorentinD** [comment]
@drsealks we could find two bugs in node2vec (7a95270132). The first, which you most likely encountered, was due to parallel computations on a non thread-safe graph. Also for now we throw on negative weights, as the sampling logic does not support negative weights yet.

The fixes will be in the next release (`1.6.2`). If you cannot wait until then, you could try building our library locally.

Hope that resolves your issue.

**Comment by AliciaFrame** [comment]
@drsealks GDS 1.6.2 has been published, including the two bug fixes for node2vec that @FlorentinD referenced above: https://github.com/neo4j/graph-data-science/releases/tag/1.6.2

Please let us know if that fixes your problem 🙂

**Comment by FlorentinD** [comment]
I will close this issue for now. Feel free to reopen if the issue was not resolved.
