### ISSUE TITLE
Wcc Stream should be in read mode and not write mode

### ISSUE THREAD

**Issue by albertodelazzari** [neo4j/graph-data-science#121]
https://github.com/neo4j/graph-data-science/blob/39451c82e33c8e495749675f6d5f052c4a844b2a/proc/community/src/main/java/org/neo4j/graphalgo/wcc/WccStreamProc.java#L49

If I call the wcc algorithm in stream mode the "query mode" is declared as write mode so a piece of code like this

```python
query = """
 CALL gds.wcc.stream('digitalPayments-credit-card') 
 YIELD nodeId, componentId
 RETURN collect(nodeId) as nodes, componentId
"""
df1 = spark.read.format("org.neo4j.spark.DataSource") \
   .option("url", host) \
   .option("database", "digitalpayments") \
   .option("authentication.type", "basic") \
   .option("authentication.basic.username", user) \
   .option("authentication.basic.password", password) \
   .option("query", query) \
   .option("partitions", "2")\
   .load() \
   .show()
```

Raise the following error:

`IllegalArgumentException: Please provide a valid READ query`

**Comment by s1ck** [comment]
@albertodelazzari Thanks for reporting this issue. We found some additional procedures that use an incorrect mode. It will be fixed in the next 1.6.3 patch release as well as on master.
