### ISSUE TITLE
Replace the term 'view' in the document with a 'materialized view'

### ISSUE THREAD

**Issue by nameof** [neo4j/graph-data-science#122]
According to the description in the document `graph-catalog.adoc`:  " A graph projection can be seen as a **view** over the stored graph, containing only analytically relevant, potentially aggregated, topological and property information. "

From the perspective of the view on the relational database, it may be confusing to use the view to compare the graph projection. The view will reflect the latest changes in the data in the relational database, but in the GDS, the graph projection will not change once it is created. The term materialized view will be more accurate.

**Comment by Mats-SX** [comment]
I agree with your observations and have approved the pull request. Now we only need a CLA signature and then we'll gladly merge it.

**Comment by nameof** [comment]
> I agree with your observations and have approved the pull request. Now we only need a CLA signature and then we'll gladly merge it.
@Mats-SX  Okay, I have sent the email, please check it out, thank you

**Comment by Mats-SX** [comment]
Fixed in https://github.com/neo4j/graph-data-science/commit/8be9f537182a15123067bc7ec29b7a4c44f2d0b7
