### ISSUE TITLE
Build Failure for Graph-data-science project

### ISSUE THREAD

**Issue by AnubhavGuptaRLE** [neo4j/graph-data-science#126]
Hey,
I am following the https://neo4j.com/docs/operations-manual/current/installation/ to setup **Graph-data-science** project but while building the project through gradle facing build failure issues.

**Documentation followed to build the project :** https://github.com/neo4j/graph-data-science/

**Steps Taken to build the project:**

1. Cloned the project from git.(GitHub - https://github.com/neo4j/graph-data-science/).
2. Done project setup in intellij by skimpily opening the cloned project .
3. Trying to build the Project using gradlew check command but build got fail .

**Please refer the below logs:**
Missing header in: alpha\alpha-algo\src\test\java\org\neo4j\graphalgo\impl\spanningTree\MyPrimTest.java
Task :alpha-algo:licenseTest FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':alpha-algo:licenseTest'.
License violations were found: C:\VCM_rle\neo4jgdslibrary\alpha\alpha-algo\src\test\java\org\neo4j\graphalgo\impl\spanningTree\MyPrimTest.java

**Version Information :
Neo4j Desktop version : 4,2,1
Graph Data Science Library- 1.4.1
Java : 14
gradle : 6.6.1**

Both java and gradle are already set in System Settings -> Environmental Variables.

Please guide me out to solve this.

**Comment by FlorentinD** [comment]
Hey  AnubhavGuptaRLE,
I assume you created `MyPrimTest.java`?
Based on the posted failure, there is an issue with the license in that file.
You have to add a valid license to this file such as:
```
/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [http://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Neo4j is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
```

**Comment by Mats-SX** [comment]
Closing this as inactive. Please reach back if there are outstanding issues, and then we can reopen.
