### ISSUE TITLE
How to use a Stored Graph in Graph Catalog  in Dijkstra Source-Target Algorithm 

### ISSUE THREAD

**Issue by samasalam** [neo4j/graph-data-science#127]
Hello 
Finally, with great help  of @FlorentinD (repairing a bug in this algorithm),  I created a graph using graph generator algorithm as follow: 
`CALL gds.beta.graph.generate('test', 3, 2, 
{
 relationshipDistribution : 'random',
  relationshipProperty: {
                        name:',cost',
                        type: 'RANDOM',
                        min : 40.0,
                        max : 80.0
                        }
})
YIELD name, nodes, relationships, generateMillis, relationshipSeed, averageDegree, relationshipDistribution, relationshipProperty`

Here a graph named **test** is created and stored in the graph catalog. As depicted in [Link_1](https://neo4j.com/docs/graph-data-science/current/alpha-algorithms/graph-generation/), the generated graph can be used as input for any algorithm in the library.
Now to use the generated graph in Dijkstra Source-Target Algorithm, I run the following cypher: 

`MATCH (source:host {name: 'node_1'}), (target:host {name: 'node_2'})
CALL gds.shortestPath.dijkstra.stream('myGraph', {
    sourceNode: source,
    targetNode: target,
    relationshipWeightProperty: 'cost'
})
YIELD index, sourceNode, targetNode, totalCost, nodeIds, costs, path
RETURN
    index,
    gds.util.asNode(sourceNode).name AS sourceNodeName,
    gds.util.asNode(targetNode).name AS targetNodeName,
    totalCost,
    [nodeId IN nodeIds | gds.util.asNode(nodeId).name] AS nodeNames,
    costs,
    nodes(path) as path
ORDER BY index`

How can I set the node names in the generated graph to be used as Source-Target in the Dijkstra Algorithm?

**Comment by vnickolov** [comment]
Hello @samasalam currently the in-memory graph **does not** support String properties.
You can use the results from the algorithm to query the Neo4j database and fetch the name from there.

**Comment by FlorentinD** [comment]
Also, what is your idea with the MATCH before? Would be helpful to know more details of your use case.

You generated a random graph, so the nodes do not correspond to nodes in your neo4j database.
The node ids in the in-memory graph are from `0` to `nodeCount -1`, so you can try out `shortestPath` by using any id in that space for source and target.

**Comment by samasalam** [comment]
Hello @FlorentinD 
well I now understand that the MATCH is not needed. so I modified the graph generation and the shortest path queries as follow:

`CALL gds.beta.graph.generate('test', 1000, 2, 
{
 relationshipDistribution : 'random',
  relationshipProperty: {
                        name:'cost',
                        type: 'random',
                        min : 40.0,
                        max : 80.0
                        }
})
YIELD name, nodes, relationships, generateMillis, relationshipSeed, averageDegree, relationshipDistribution, relationshipProperty`

`CALL gds.shortestPath.dijkstra.stream('test', {
    sourceNode: 3,
    targetNode: 100,
    relationshipWeightProperty: 'cost'
})
YIELD index, sourceNode, targetNode, totalCost, nodeIds, costs, path
RETURN
    index,
    gds.util.asNode(sourceNode).name AS sourceNodeName,
    gds.util.asNode(targetNode).name AS targetNodeName,
    totalCost,
    [nodeId IN nodeIds | gds.util.asNode(nodeId).name] AS nodeNames,
    costs,
    nodes(path) as path
ORDER BY index`

No errors but no path is returned. The answer is `(no changes, no records)`.

**Comment by FlorentinD** [comment]
Then the source and target nodes are not connected in the generated graph.
As you have `1000` nodes and only `2` relationships on average, it is also not very likely, that both nodes are connected. 

You could play around a bit with the average degree and degree distribution of the generated graph.

**Comment by samasalam** [comment]
@FlorentinD 
You ask me about my use case. I want to prove that best (optimal) paths is computed in Neo4j in no time (comparing to other databases like Relational). I built a Python script that models and stores an SDN (Software Defined Network) network topology as a graph in Neo4j, and store cost metric as  relationship property to execute the Dijkstra Source-Target Algorithm. To show the benefit of the modelling process, I choose the shortest path approach. Thanks for your efforts.

**Comment by FlorentinD** [comment]
To me it sounds like it makes more sense to project an example SDN into GDS.

I would strongly advise against using random graphs for benchmarks. They should be rather seen as a tool to explore the possibilities of GDS.

Also you can try to use the shortestPath directly built into cypher (https://neo4j.com/docs/cypher-manual/current/execution-plans/shortestpath-planning/).

**Comment by samasalam** [comment]
@FlorentinD Sorry but what you meant by this statement: **To me it sounds like it makes more sense to project an example SDN into GDS.**
From your perspective, how can I benefit from the created graph that is modeled using Python & Neo4j integration? This graph represents the underlying network topology in the SDN data plane. It also can store traffic statistics in node and/or relationship properties. Can I benefit from the available graph algorithms in the GDS library ? I'll be so thankful for any ideas.

**Comment by FlorentinD** [comment]
Do you have example data to use?
I  would imagine, there are example network topologies to use load into Neo4j + GDS instead of using a random graph.

My recommendation is to go through our docs, but path algorithms sound like a good fit.
For more general use-case questions, I would recommend our community forum (https://community.neo4j.com/).
Maybe there is also someone that has more experience in your area.

The original issue is resolved so I would close this issue.

Feel free to reopen if there is anything unclear.
