### ISSUE TITLE
Create subgraph - java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by carloslaufer** [neo4j/graph-data-science#128]
Hi All,

I am getting an error when trying to create a subgraph using gds.beta.graph.create.subgraph

I am using:
Neo4j community edition version 4.2.7 
gds version 1.6.4 
machine memory 64G

First, I run gds.graph.create.cypher to create a graph filtered by date, returning a set of edge integer properties.

CALL gds.graph.create.cypher('date_20200519',
'MATCH (p)-[{data: date("2020-05-19")}]-()
RETURN DISTINCT id(p) as id',
'MATCH (p1)-[r {data: date("2020-05-19")}]->(p2)
RETURN id(p1) as source, id(p2) as target, r.atrib_resp as atrib_resp, r.conflito as conflito, r.moralidade as moralidade, r.conseq_pandemia as conseq_pandemia, r.med_contencao as med_contencao, r.met_tratamento as met_tratamento')
YIELD graphName, nodeCount, relationshipCount, createMillis;
graphName - "date_20200519" nodeCount - 222.244 relationshipCount - 444.246 createMillis - 795277

This is ok. I can run a pageRank over this graph without problems. When I try to create a subgraph, filtering by one of the properties I get an error:

CALL gds.beta.graph.create.subgraph('date_20200519_atrib_resp_subgraph', 'date_20200519', '*', 'r.atrib_resp = 1')
YIELD graphName, fromGraphName, nodeCount, relationshipCount
ERROR Neo.ClientError.Procedure.ProcedureCallFailed Failed to invoke procedure gds.beta.graph.create.subgraph: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 45647 out of bounds for length 3473

Please, could someone help me?

Thank you in advance, Laufer

**Comment by soerenreichardt** [comment]
Hi @carloslaufer, thanks for reporting this issue.
With the information given it is difficult to reproduce your issue. Could you provide the whole stacktrace of the error? You should find it in one of the neo4j logs.

**Comment by FlorentinD** [comment]
Also the new version `1.6.5` fixed an issue in `create.subgraph`, so updating your GDS version might resolve the issue.

**Comment by carloslaufer** [comment]
I've tried with version 1.6.5 and the eror still remains

**Comment by carloslaufer** [comment]
Here is the debug.log
[debug.log](https://github.com/neo4j/graph-data-science/files/7174169/debug.log)

**Comment by DarthMax** [comment]
@carloslaufer The add was meant for you not @soerenreichardt  :see_no_evil:

**Comment by carloslaufer** [comment]
Hi, @DarthMax,
Thank you very much for your work and kindness.
My app is now working five times faster using subgraphs and gds version 1.7.
Best, Laufer
