### ISSUE TITLE
Performance problems/Bug with Personalized PageRank

### ISSUE THREAD

**Issue by SandroMartens** [neo4j/graph-data-science#129]
**Describe the bug**
I want to write a Personalized page Rank to my database. But the query never finishes. After 10 minutes it wrote 20 GB on my drive and crashed. 

**To Reproduce**
<details>
  <summary>Spoiler warning</summary> 
  
╒═════════════════════════════════════════════╤══════════════════════════════════════════╕
│"key"                                        │"value"                                   │
╞═════════════════════════════════════════════╪══════════════════════════════════════════╡
│"gdsVersion"                                 │"1.6.4"                                   │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"gdsEdition"                                 │"Community"                               │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"neo4jVersion"                               │"4.3.3"                                   │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"minimumRequiredJavaVersion"                 │"11"                                      │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"featurePreAggregation"                      │false                                     │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"featureSkipOrphanNodes"                     │false                                     │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"featureMaxArrayLengthShift"                 │28                                        │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"featureKernelTracker"                       │false                                     │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"featurePropertyValueIndex"                  │false                                     │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"featureParallelPropertyValueIndex"          │false                                     │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"featureBitIdMap"                            │true                                      │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"buildDate"                                  │"2021-07-29_08:36:17"                     │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"buildJdk"                                   │"11.0.6+10 (Oracle Corporation)"          │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"buildJavaVersion"                           │"11.0.6"                                  │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"buildHash"                                  │"e190474777b80e7ad836fe6a83b56ec705b50174"│
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"availableCPUs"                              │16                                        │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"physicalCPUs"                               │16                                        │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"availableHeapInBytes"                       │1073741824                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"availableHeap"                              │"1024 MiB"                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"heapFreeInBytes"                            │800774208                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"heapFree"                                   │"763 MiB"                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"heapTotalInBytes"                           │1073741824                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"heapTotal"                                  │"1024 MiB"                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"heapMaxInBytes"                             │1073741824                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"heapMax"                                    │"1024 MiB"                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"offHeapUsedInBytes"                         │471269104                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"offHeapUsed"                                │"449 MiB"                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"offHeapTotalInBytes"                        │525221888                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"offHeapTotal"                               │"500 MiB"                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCodeheapNonNmethodsUsedInBytes"         │2246400                                   │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCodeheapNonNmethodsUsed"                │"2193 KiB"                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCodeheapNonNmethodsTotalInBytes"        │4980736                                   │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCodeheapNonNmethodsTotal"               │"4864 KiB"                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolMetaspaceUsedInBytes"                   │352765312                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolMetaspaceUsed"                          │"336 MiB"                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolMetaspaceTotalInBytes"                  │372801536                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolMetaspaceTotal"                         │"355 MiB"                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCodeheapProfiledNmethodsUsedInBytes"    │24301824                                  │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCodeheapProfiledNmethodsUsed"           │"23 MiB"                                  │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCodeheapProfiledNmethodsTotalInBytes"   │47841280                                  │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCodeheapProfiledNmethodsTotal"          │"45 MiB"                                  │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCompressedClassSpaceUsedInBytes"        │51267216                                  │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCompressedClassSpaceUsed"               │"48 MiB"                                  │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCompressedClassSpaceTotalInBytes"       │57262080                                  │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCompressedClassSpaceTotal"              │"54 MiB"                                  │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1EdenSpaceFreeInBytes"                 │560988160                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1EdenSpaceFree"                        │"535 MiB"                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1EdenSpaceTotalInBytes"                │674234368                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1EdenSpaceTotal"                       │"643 MiB"                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1EdenSpaceMaxInBytes"                  │-1                                        │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1EdenSpaceMax"                         │"N/A"                                     │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1OldGenFreeInBytes"                    │238737472                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1OldGenFree"                           │"227 MiB"                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1OldGenTotalInBytes"                   │397410304                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1OldGenTotal"                          │"379 MiB"                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1OldGenMaxInBytes"                     │1073741824                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1OldGenMax"                            │"1024 MiB"                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1SurvivorSpaceFreeInBytes"             │0                                         │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1SurvivorSpaceFree"                    │"0 Bytes"                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1SurvivorSpaceTotalInBytes"            │2097152                                   │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1SurvivorSpaceTotal"                   │"2048 KiB"                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1SurvivorSpaceMaxInBytes"              │-1                                        │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolG1SurvivorSpaceMax"                     │"N/A"                                     │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCodeheapNonProfiledNmethodsUsedInBytes" │40726272                                  │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCodeheapNonProfiledNmethodsUsed"        │"38 MiB"                                  │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCodeheapNonProfiledNmethodsTotalInBytes"│42336256                                  │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"poolCodeheapNonProfiledNmethodsTotal"       │"40 MiB"                                  │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"freePhysicalMemoryInBytes"                  │4176252928                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"freePhysicalMemory"                         │"3982 MiB"                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"committedVirtualMemoryInBytes"              │2635423744                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"committedVirtualMemory"                     │"2513 MiB"                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"totalPhysicalMemoryInBytes"                 │17106104320                               │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"totalPhysicalMemory"                        │"16313 MiB"                               │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"freeSwapSpaceInBytes"                       │12207243264                               │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"freeSwapSpace"                              │"11641 MiB"                               │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"totalSwapSpaceInBytes"                      │40074113024                               │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"totalSwapSpace"                             │"37 GiB"                                  │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"openFileDescriptors"                        │-1                                        │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"maxFileDescriptors"                         │-1                                        │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"vmName"                                     │"OpenJDK 64-Bit Server VM"                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"vmVersion"                                  │"11.0.8+10-LTS"                           │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"vmCompiler"                                 │"HotSpot 64-Bit Tiered Compilers"         │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"containerized"                              │false                                     │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"dbms.security.procedures.unrestricted"      │"jwt.security.*,apoc.*,gds.*"             │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"dbms.memory.pagecache.size"                 │"512m"                                    │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"dbms.tx_state.memory_allocation"            │"ON_HEAP"                                 │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"dbms.memory.off_heap.max_size"              │2147483648                                │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"dbms.memory.transaction.global_max_size"    │0                                         │
├─────────────────────────────────────────────┼──────────────────────────────────────────┤
│"dbms.memory.transaction.max_size"           │0                                         │
└─────────────────────────────────────────────┴──────────────────────────────────────────┘ 

</details>

GDS version: 1.6.4
Neo4j version: 4.3.3
Operating system: Windows 10 Pro 21H1

- [x] I'm working with a Network of Twitter Users. 423,049 "User" Nodes with 378,311 "Answered" Relations.
- [x] Further queries
- `match (n:Nutzer {mainAutor: True})
Call gds.pageRank.write({
  nodeProjection: "Nutzer",
  relationshipProjection: "ANTWORTETE_AUF",
  relationshipProperties: "anzahlTweets",
  relationshipWeightProperty: "anzahlTweets",
  writeProperty: "PageRankAntworten",
  sourceNodes: [n]
  }
)
YIELD  nodePropertiesWritten
RETURN  nodePropertiesWritten`

**Expected behavior**
The query should write the Page Rank property

**Additional context**
The normal Page Rank runs without problems in ~5s or so.

**Comment by vnickolov** [comment]
@SandroMartens can you please provide the result of `CALL gds.articleRank.write.estimate` on the graph you are using? 

It looks like you have configured `maxHeap: 1024MB` which may not be enough for this graph.

**Comment by SandroMartens** [comment]
This is the Output (JSON)

[
  {
    "requiredMemory": "[28 MiB ... 34 MiB]",
    "treeView": "Memory Estimation: [28 MiB ... 34 MiB]
|-- graph: [18 MiB ... 24 MiB]
    |-- this.instance: 104 Bytes
    |-- nodeIdMap: [6689 KiB ... 12806 KiB]
        |-- this.instance: 64 Bytes
        |-- Neo4j identifiers: 3305 KiB
        |-- Mapping from Neo4j identifiers to internal identifiers: [3332 KiB ... 9449 KiB]
        |-- Node Label BitSets: 51 KiB
    |-- adjacency list for 'RelationshipType{name='ANTWORTETE_AUF'}': 5981 KiB
        |-- this.instance: 40 Bytes
        |-- pages: 1024 KiB
        |-- degrees: 1652 KiB
        |-- offsets: 3305 KiB
    |-- property 'RelationshipType{name='ANTWORTETE_AUF'}.anzahlTweets: 6377 KiB
        |-- this.instance: 40 Bytes
        |-- pages: 3072 KiB
        |-- offsets: 3305 KiB
|-- algorithm: 9967 KiB
    |-- this.instance: 80 Bytes
    |-- vote bits: 51 KiB
    |-- compute steps: 384 Bytes
        |-- this.instance: 96 Bytes
    |-- node value: 3305 KiB
        |-- pagerank (DOUBLE): 3305 KiB
    |-- message arrays: 6610 KiB
        |-- this.instance: 56 Bytes
        |-- send array: 3305 KiB
        |-- receive array: 3305 KiB
",
    "mapView": {
"name": "Memory Estimation",
"components": [
        {
          "name": "graph",
          "components": [
            {
              "name": "this.instance",
              "memoryUsage": "104 Bytes"
            },
            {
              "name": "nodeIdMap",
              "components": [
                {
                  "name": "this.instance",
                  "memoryUsage": "64 Bytes"
                },
                {
                  "name": "Neo4j identifiers",
                  "memoryUsage": "3305 KiB"
                },
                {
                  "name": "Mapping from Neo4j identifiers to internal identifiers",
                  "memoryUsage": "[3332 KiB ... 9449 KiB]"
                },
                {
                  "name": "Node Label BitSets",
                  "memoryUsage": "51 KiB"
                }
              ],
              "memoryUsage": "[6689 KiB ... 12806 KiB]"
            },
            {
              "name": "adjacency list for 'RelationshipType{name='ANTWORTETE_AUF'}'",
              "components": [
                {
                  "name": "this.instance",
                  "memoryUsage": "40 Bytes"
                },
                {
                  "name": "pages",
                  "memoryUsage": "1024 KiB"
                },
                {
                  "name": "degrees",
                  "memoryUsage": "1652 KiB"
                },
                {
                  "name": "offsets",
                  "memoryUsage": "3305 KiB"
                }
              ],
              "memoryUsage": "5981 KiB"
            },
            {
              "name": "property 'RelationshipType{name='ANTWORTETE_AUF'}.anzahlTweets",
              "components": [
                {
                  "name": "this.instance",
                  "memoryUsage": "40 Bytes"
                },
                {
                  "name": "pages",
                  "memoryUsage": "3072 KiB"
                },
                {
                  "name": "offsets",
                  "memoryUsage": "3305 KiB"
                }
              ],
              "memoryUsage": "6377 KiB"
            }
          ],
          "memoryUsage": "[18 MiB ... 24 MiB]"
        },
        {
          "name": "algorithm",
          "components": [
            {
              "name": "this.instance",
              "memoryUsage": "80 Bytes"
            },
            {
              "name": "vote bits",
              "memoryUsage": "51 KiB"
            },
            {
              "name": "compute steps",
              "components": [
                {
                  "name": "this.instance",
                  "memoryUsage": "96 Bytes"
                }
              ],
              "memoryUsage": "384 Bytes"
            },
            {
              "name": "node value",
              "components": [
                {
                  "name": "pagerank (DOUBLE)",
                  "memoryUsage": "3305 KiB"
                }
              ],
              "memoryUsage": "3305 KiB"
            },
            {
              "name": "message arrays",
              "components": [
                {
                  "name": "this.instance",
                  "memoryUsage": "56 Bytes"
                },
                {
                  "name": "send array",
                  "memoryUsage": "3305 KiB"
                },
                {
                  "name": "receive array",
                  "memoryUsage": "3305 KiB"
                }
              ],
              "memoryUsage": "6610 KiB"
            }
          ],
          "memoryUsage": "9967 KiB"
        }
      ],
"memoryUsage": "[28 MiB ... 34 MiB]"
    },
    "bytesMin": 29713296,
    "bytesMax": 35976568,
    "nodeCount": 423049,
    "relationshipCount": 378311,
    "heapPercentageMin": 0.1,
    "heapPercentageMax": 0.1
  }
]

**Comment by vnickolov** [comment]
@SandroMartens thank you, this seems okay, can you also please share the error stack trace so we can have a look and try to find the cause

**Comment by FlorentinD** [comment]
Does the problem only occur on writing? Could you try out if the personalized `pageRank.stream` or `pageRank.mutate` are also slower.

In the implementation, the personalized PR differs in the initial values for the nodes. This could result in the personalized PR running more iterations, but that should not result in such a huge difference.
