### ISSUE TITLE
graph convolutional neural networks in gds

### ISSUE THREAD

**Issue by HashRocketSyntax** [neo4j/graph-data-science#13]
Really excited for what graph data science will bring to the table!

Would it be possible to add gds Python methods for frameworks like Deep Graph in order to perform `graph convolution neural networks` and `neural message passing` just like any other algo? Deep Graph already supports self looping and parallel edges. It would be nice to be able to specify which edge and node properties would be used instead of defaulting to all of them. 
^ or just write serializers for the popular gcn libs since wrapping everything is a nightmare and why neovis fails. 

If you aren't familiar with gcns, they make **adjacency matrixes** (by looking at which nodes connect to which nodes) which are used similarly to CNN convolutions.
![image](https://user-images.githubusercontent.com/16389820/75642096-51cb6780-5c08-11ea-8510-fc619f372339.png)
![image](https://user-images.githubusercontent.com/16389820/75642602-1336ac80-5c0a-11ea-96cd-a2d2ab8faa0a.png)
![image](https://user-images.githubusercontent.com/16389820/75642619-247fb900-5c0a-11ea-8589-c1387db07cb5.png)

In cheminformatics and protein-to-protein interactions, it will be rad to look _n_ hops out to intuitively know how molecules are structured. Even though that data is useless w/o 3D structure. 

These algs work just like the "wicked predictive node-edge-node triplets" section of the Graph Algorithms book.

**Comment by AliciaFrame** [comment]
Thanks for the comment!

While we're aware of what GCNNs are, we don't have them on our near term roadmap. For now, we're focused on building fast and scaleable algorithms that can run in reasonable time frames (minutes to hours) on very large graphs (tens of billions of nodes and edges). We're currently prototyping graph embedding implementations, so keep an eye out for those in the second half of 2020.
