### ISSUE TITLE
ArrayIndexOutOfBoundsException when running triangleCount or LCC

### ISSUE THREAD

**Issue by RockSmashUgg** [neo4j/graph-data-science#134]
**Describe the bug**

I've been encountering an ArrayIndexOutOfBoundsException when running gds.triangleCount.stream  and .stats (which, as it uses the triangleCount, also throws the same error for gds.localClusteringCoefficient.stream and .stats.).   For both algos, I am able to complete a .estimate procedure.

**To Reproduce**

GDS version: 1.7.0
Neo4j version: 4.3.5
Operating system: MacOS Mojave 10.14.6

Also installed:
APOC 4.3.0.3
Neosemantics 4.3.0.1

- [ ] Neosemantics pre-configs set as:
`CREATE CONSTRAINT n10s_unique_uri ON (r:Resource)
ASSERT r.uri IS UNIQUE;`
`CALL n10s.graphconfig.init( { handleMultival: "ARRAY" , handleVocabUris: "IGNORE"});`
- [ ] Load RDF:
`CALL n10s.onto.import.fetch(
"https://gitlab.isl.ics.forth.gr/cidoc-crm/cidoc_crm_rdf/-/raw/v7.1.1_preparation/CIDOC_CRM_7.1.1_RDFS_Impl_v1.1.rdfs","RDF/XML", {
languageFilter: 'en'});`
//results should be 3606 triples loaded/parsed with null namespaces
- [ ] Create undirected graph projection:
`CALL gds.graph.create(
'Algos_0_CRM_UD', 
'*', 
{ 
DOMAIN: {orientation: 'UNDIRECTED'},
RANGE: {orientation: 'UNDIRECTED'},
SPO: {orientation: 'UNDIRECTED'},
SCO: {orientation: 'UNDIRECTED'}
}
)
YIELD graphName, nodeCount, relationshipCount;`
//results should be 387 nodes, 1776 relationships
- [ ] run triangleCount .estimate algo:
`CALL gds.triangleCount.write.estimate('Algos_0_CRM_UD', { writeProperty: 'triangleCount' })
YIELD nodeCount, relationshipCount, bytesMin, bytesMax, requiredMemory`
//result screenshot shows estimate call successful with no errors
![Screenshot 2021-10-06 at 11 52 53 AM](https://user-images.githubusercontent.com/5048986/136193310-43334851-5d76-42be-9e33-dc4b873ff654.png)
- [ ] run triangleCount.stats or .stream:
`CALL gds.triangleCount.stream('Algos_0_CRM_UD')
YIELD nodeId, triangleCount
RETURN gds.util.asNode(nodeId) AS name, triangleCount
ORDER BY triangleCount DESC`
//result = failed
![Screenshot 2021-10-06 at 11 51 49 AM](https://user-images.githubusercontent.com/5048986/136193626-451dc4cc-8027-466c-928e-91d82cac3134.png)

**Expected behavior**

Did not expect the procedure to throw this error.  Previous runs (see below) yielded globalTriangleCount, nodeCount and returned gds.util.asNode(nodeId) results successfully.

**Additional context**

The last time I was able to successfully run gds.triangleCount.write.estimate (.stats and .stream) was an a dbms that was upgraded from Neo4j 4.1.2 to 4.3.3 and using GDSL either 1.6.4 or 1.7.0 (bad record-keeping there on my part.  that'll teach me.)   The same error occurs regardless if the dbms I'm running (all using 4.3.5 and GDSL 1.7.0) is holding RDF-derived, CSV or JSON-imported data or combinations thereof.

**Comment by ILYSHI** [comment]
The same issue with approximateBetweenness algorithms.

**Comment by knutwalker** [comment]
Hi @RockSmashUgg, we have identified the issue and pushed a fixed that will be available on this repo by tomorrow morning UTC-ish. We are also scheduling a 1.7.1 patch release that will likely be available in a few days.

@ILYSHI Although the exception is the same type, this is an unrelated issue. Could you please open a new issue for this with a way to reproduce it?
