### ISSUE TITLE
 Pathfinding Algorithms should have an option to include original relationship names in the returned path

### ISSUE THREAD

**Issue by KukumavMozolo** [neo4j/graph-data-science#135]
It would be great if Pathfinding Algorithms would also return the original relationship names other than path_0,...

**Describe the solution you would like**
It would be great if calling relationships(path) would also return the original relationship names and not only the ones created by the algorithm(e.g. for Yens it is path_0, path_1, ...)
**Describe alternatives you have considered**
At the moment I need to query neo4j again for the relationship names based on the node Id's yen's returns. It would be great if that could be done with the same request

**Comment by FlorentinD** [comment]
Thank you for your input @KukumavMozolo.
Can you elaborate a bit more what you mean with `names`? Do you mean the relationship type or do you refer to a `name` property?

**Comment by KukumavMozolo** [comment]
Ah, my apologies. Now I realize they are called Relationship Types.

**Comment by FlorentinD** [comment]
Thank you for the clarification and for bringing up your request.

We discussed your request in the team and added it to a list of features requests.
I cannot promise you, that we will take action in the near future but we will definitely consider it.

I will close this issue for now, but feel free to open it again :)
