### ISSUE TITLE
Update version.json generation

### ISSUE THREAD

**Issue by conker84** [neo4j/graph-data-science#137]
Since few days maven central apis dropped the support for HTTP, moving to HTTPS, and changed the behaviour by returning only 25 rows if you ask for more of 200. Please update the version.json generation
with this tested maven URL:

`https://search.maven.org/solrsearch/select?q=g:%22org.neo4j%22+AND+a:%22neo4j%22&core=gav&rows=200&wt=json`

**Comment by FlorentinD** [comment]
Thank you for notifying us!

However, our `versions.json` is generated in a different way. Therefore, we don't need to act on this.
