### ISSUE TITLE
graph algorithms not available for linux neo4j-desktop?

### ISSUE THREAD

**Issue by HashRocketSyntax** [neo4j/graph-data-science#14]
Is the plugin for graph algorithms not available for Linux neo4j-desktop ? 

The install button for the plugin is greyed out, whereas the APOC plugin installs fine.

![image](https://user-images.githubusercontent.com/16389820/76153243-663fb200-6097-11ea-9b4d-7016f019b90c.png)

If I switch to offline mode, the APOC plugin is not installable.

**Comment by mneedham** [comment]
Presumably you're using 4.0? 

If so, the plugin won't be available until April. See https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/924

**Comment by Mats-SX** [comment]
As Mark says, 4.0 support will come in future releases of the Graph Data Science library, which is supported by a different Neo4j Desktop plugin from the Graph Algorithms library.

If you're having issues using the GDS plugin with Neo4j versions 3.5.9 or later in the 3.5 series, please raise a new issue.

**Comment by HashRocketSyntax** [comment]
Was setting up new env in AWS so tried 4.0 like you guys said. Downgraded to 3.5 and the plugin works fine.
