### ISSUE TITLE
Would it be possible to allow custom restraints on path finding algorithms?

### ISSUE THREAD

**Issue by Deeswoc** [neo4j/graph-data-science#142]
I think it would be useful to allow for restraining the paths returned for the path finding algorithms to do things such as not having repeated properties on a path, multiple connections to a node of X type or having nodes on a path have a set pattern to exclude paths that aren't needed when you expect a set pattern for returned paths.

What I'm thinking is a property on the config for Yen's algorithm, Dijkstra's algorithm and the path algorithms that could accept a query or map containing property names and restrains for them similar to the node and relationship projections.

**Comment by s1ck** [comment]
@Deeswoc thanks for your interest. I think what you're referring to are regular path queries (RPQs) which would be applied during shortest path search. While this is most certainly an interesting field, their complexity is open research in graph query languages and the implementation is not straightforward. We haven't yet seen many users who need it and have therefore pushed out implementing such a feature. That being said, you are of course invited to open a PR :)

You are probably aware, but for completeness: To express simple predicates wrt to single nodes / edges, you can also pre-process the graph using `graph.create.subgraph` and apply the corresponding node and relationship filters.

**Comment by Deeswoc** [comment]
@s1ck That's unfortunate but I completely understand. I'll make an attempt at some type of implementation on my own but I make no guarantees haha.

The second paragraph I'm not to sure I understand completely. I'm not sure if it can get paths with the constraints I'd need, unique properties/relationships, but I'm curious what you meant and would like to know more.

**Comment by s1ck** [comment]
You won't be able to to apply the constraints you specified with `graph.create.subgraph`. You are limited to predicates that can be expressed for a single entity (node or relationship), e.g. `n:Foo AND n.property > 42`. Maybe you can model your input in a way that would allow predicates on single nodes.

Looking forward to your PR. Will close this for now. Please let me know if you need more information.
