### ISSUE TITLE
Feature Request: add Translate (Center) to scaleProperties

### ISSUE THREAD

**Issue by devineyfajr** [neo4j/graph-data-science#143]
sometimes we want to subtract the mean, but not divide by the standard deviation. I didn't find this easy to do in Cypher for lists of numbers (like embeddings)

**Comment by AliciaFrame** [comment]
Thanks for the request! We've added it to our feature backlog, and we'll let you know when it's available 😄

**Comment by IoannisPanagiotas** [comment]
This is now included as part of 2.2.0
