### ISSUE TITLE
Why  can not find these class file?

### ISSUE THREAD

**Issue by mullerhai** [neo4j/graph-data-science#144]
**Describe the bug**
these class file  use in the test case ,but  can not find  they are  defined ?
ImmutableRelationshipsLoadResult
ImmutableGraphCreateFromGdlConfig
GdlFactoryBuilder
ImmutableGraphCreateFromGdlConfig
EmptyProgressEventTracker
TestDatabaseManagementServiceBuilder
ImpermanentDbmsExtension
ImmutableGdlGraphSetup

CanonicalAdjacencyMatrix

**To Reproduce**

GDS version: X.Y.Z
Neo4j version: X.Y.Z
Operating system: (for example Windows 95/Ubuntu 16.04)

- [ ] Graph/dataset to reproduce the bug.  Alternatively describe as much as possible the data, e.g., graph size and other schema/structure details.
- [ ] Create Query 
- [ ] Further queries

**Expected behavior**

**Additional context**

**Comment by Mats-SX** [comment]
Hello @mullerhai and thank you for reaching out to us!

I'm a little bit confused as to what you are trying to achieve. Could you share some details on what your goal is? For standard usage of GDS, you needn't worry about the location of these classes. The simplest way to use GDS is to install Neo4j Desktop and the one-click install of GDS via the Neo4j Desktop plugin. [Instructions for that can be found in the GDS Manual](https://neo4j.com/docs/graph-data-science/current/installation/neo4j-desktop/).

But I'll try to respond directly to the question also. Some of the classes you mention are not checked into this repository, but they are _generated_ at compile time, often through the use of an annotation processor. This includes the following classes that you mention:

```
ImmutableRelationshipsLoadResult
ImmutableGraphCreateFromGdlConfig
GdlFactoryBuilder
ImmutableGraphCreateFromGdlConfig
ImmutableGdlGraphSetup
```

Some classes we receive by way of dependency. That includes the following:

```
TestDatabaseManagementServiceBuilder
ImpermanentDbmsExtension
```

You can study the sources for them in their host repository: [ImpermanentDbmsExtension](https://github.com/neo4j/neo4j/blob/4.3/community/community-it/it-test-support/src/main/java/org/neo4j/test/extension/ImpermanentDbmsExtension.java) and [TestDatabaseManagementServiceBuilder](https://github.com/neo4j/neo4j/blob/4.3/community/community-it/it-test-support/src/main/java/org/neo4j/test/TestDatabaseManagementServiceBuilder.java).

The class `EmptyProgressEventTracker` I am not aware of. Where have you found that class name? We do have a class called [EmptyProgressTracker](https://github.com/neo4j/graph-data-science/blob/98612186107d739869e536c1fd8f2cf2b864ad17/core/src/main/java/org/neo4j/gds/core/utils/progress/tasks/ProgressTracker.java#L62). Maybe that is good?

The remaining class is located in this repository: [CanonicalAdjacencyMatrix](https://github.com/neo4j/graph-data-science/blob/master/test-utils/src/main/java/org/neo4j/gds/canonization/CanonicalAdjacencyMatrix.java).

Best regards
Mats

**Comment by mullerhai** [comment]
> Hello @mullerhai and thank you for reaching out to us!
> 
> I'm a little bit confused as to what you are trying to achieve. Could you share some details on what your goal is? For standard usage of GDS, you needn't worry about the location of these classes. The simplest way to use GDS is to install Neo4j Desktop and the one-click install of GDS via the Neo4j Desktop plugin. [Instructions for that can be found in the GDS Manual](https://neo4j.com/docs/graph-data-science/current/installation/neo4j-desktop/).
> 
> But I'll try to respond directly to the question also. Some of the classes you mention are not checked into this repository, but they are _generated_ at compile time, often through the use of an annotation processor. This includes the following classes that you mention:
> 
> ```
> ImmutableRelationshipsLoadResult
> ImmutableGraphCreateFromGdlConfig
> GdlFactoryBuilder
> ImmutableGraphCreateFromGdlConfig
> ImmutableGdlGraphSetup
> ```
> 
> Some classes we receive by way of dependency. That includes the following:
> 
> ```
> TestDatabaseManagementServiceBuilder
> ImpermanentDbmsExtension
> ```
> 
> You can study the sources for them in their host repository: [ImpermanentDbmsExtension](https://github.com/neo4j/neo4j/blob/4.3/community/community-it/it-test-support/src/main/java/org/neo4j/test/extension/ImpermanentDbmsExtension.java) and [TestDatabaseManagementServiceBuilder](https://github.com/neo4j/neo4j/blob/4.3/community/community-it/it-test-support/src/main/java/org/neo4j/test/TestDatabaseManagementServiceBuilder.java).
> 
> The class `EmptyProgressEventTracker` I am not aware of. Where have you found that class name? We do have a class called [EmptyProgressTracker](https://github.com/neo4j/graph-data-science/blob/98612186107d739869e536c1fd8f2cf2b864ad17/core/src/main/java/org/neo4j/gds/core/utils/progress/tasks/ProgressTracker.java#L62). Maybe that is good?
> 
> The remaining class is located in this repository: [CanonicalAdjacencyMatrix](https://github.com/neo4j/graph-data-science/blob/master/test-utils/src/main/java/org/neo4j/gds/canonization/CanonicalAdjacencyMatrix.java).
> 
> Best regards Mats

HI, @Mats-SX Mats-SX Very Thanks for your detail  reply  for  my problem ,  After  I  git clone this  repository, I import these code  to idea and  use  cmd: gradle build this project. I get the build result  to solve my confusion ,so many  class  implement the interface  is  generate by  three part  jar package  like org.immutables!   Sorry for it , I am  not familiar with that generate code style and  gradle build tool , I  ofter use  scala  sbt  spark flink jena  python  tensorflow pytorch  these tool chains

Now  I want to say ,Why I  need to get  these code file , because   I want to use  gds  algorithm in my  scala project for compute the knowledge learn short path , I  don't  want to use cypher cql  style and  neo4j desktop  ,I need   the  gds code 
 style like spark  ml lib ,use full java code  or  scala  code  to solve it ,because it need  auto-change the compute part .
but  I  find  the neo4j  officer  only show the cypher query style to use gds , It's  not enough . So  could you give the neo4j developer  the  java code version to use gds like the testcase  you are write in algo/src/test/java/org/neo4j/gds/paths/dijkstra/DijkstraTest.java ?  but I  found the   Graph graph and IdFunction idFunction all   object  you use Inject style , It is  not easy to create them !!  In my opinion  ,If you want recommend the code developer use gds, you may support  we  use many  write code style , some other  toolchains  coder need  it . finally   I think   neo4j  import rdf file  also need  developer part code style  ,not only  cypher query style ,please consider  what I say,  thank you
feel  appreciated  for you

**Comment by Mats-SX** [comment]
@mullerhai I understand.

We have some [general developer guidelines](https://github.com/neo4j/graph-data-science#developing-with-opengds) for how you can extend the library using standard dependency techniques and then choose the build tooling and (JVM) language of your choosing. This setup should definitely support Scala with sbt; the only thing you really need is Maven Central. That way you can ignore our code generation and many other features we use to develop the library.

The simplest way to build your own algorithm with GDS is to use the Pregel API that we offer. There are [two example projects](https://github.com/neo4j/graph-data-science/tree/master/examples) that you can study or copy. One contains [an example of how to implement a PregelComputation](https://github.com/neo4j/graph-data-science/blob/master/examples/pregel-bootstrap/src/main/java/gds/example/ExamplePregelComputation.java). These examples are pure Java, but it should be possible to do a similar extension also in Scala. Perhaps the procedure generation might be different or difficult; I do not know how annotation processing works in Scala. But if you do not intend to use procedures via Cypher that doesn't matter anyway.

I think for developing extensions and/or modifications directly within the GDS library, you will have to learn a few tools that we use, mainly Gradle and Java. There are some [guidelines for how to build the project here](https://github.com/neo4j/graph-data-science#building-the-library), which you may find helpful.

I guess that if you really want to avoid Java and our build tooling, but still want to make custom modifications to our algorithms, you can copy the relevant algorithms and port the code over to Scala, still reusing its components through dependency from Maven Central. In my experience, using Java code from Scala is not very difficult (the inverse is much worse!). Porting it is some work, but it'll buy you the freedom of developing in a familiar environment.

I hope this helps!
Regards
Mats

**Comment by mullerhai** [comment]
@Mats-SX  :
                Thanks your detail reply , the   general developer guidelines is so easy  mode  ,it is not suit for my project solution,  second ,the an example of how to implement a PregelComputation.   also not fit mine, I think  long long time after ,You will consider  our graph developer voice that the style for  pure java code to using neo4j gds algorithm . 
 third  , guidelines for how to build the project here it is not enough  for new user gradle  build tools , to build this project in china ,I need to edit some  build.gradle  config files. 

Most importantly ,Please  publish the pure jvm code to use gds algorithm  for develop , it is eagerly to solve 

by the way  ,I need to say ,when I use gds. 1.8.0 ,build. meet error ,the   jar package com/neo4j/gds/neo4j-kernel-adapter-4.4.0-alpha01/1.8.0   is  dependencyed   but not exist in maven repository,



![image](https://user-images.githubusercontent.com/6143404/146037696-646a97c2-29de-4a35-9c16-f77ee70194ce.png)

**Comment by Mats-SX** [comment]
@mullerhai You're right, this is a misconfiguration on our side. The `alpha01` version of Neo4j never existed. I have [pushed a commit that removes it](https://github.com/neo4j/graph-data-science/commit/383d2bc595ba5ebc3ca618761096ad1c08ee2c2b) from the project layout.

I am not sure how I can help you with Gradle. If this is an unfamiliar tool for you to use and the other advice to stay away from it that I gave in previous replies is not useful, then I must refer you to [Gradle's own documentation](https://docs.gradle.org/current/userguide/userguide.html) to learn how to use it. We are not Gradle experts in any other way than we are using it to assemble the GDS library software and are not educated to author advanced documentation for this tool.

We are certainly open to address any internationalization issues that exist with our build scripts. We do not have any developers for this project in China currently, so we are unaware of the issues that may exist. Could you please show what kind of changes that you have had to make, and then we can consider including them?

For your request

> Most importantly ,Please publish the pure jvm code to use gds algorithm for develop , it is eagerly to solve

I am not sure how best to reply. All of my advice this far has been "pure jvm". In fact, GDS (together with Neo4j) will only run on a JVM, so any other code is not relevant.
The only ideas that come to mind is to repeat my previous advice. Could you add more details or examples on what precisely you are looking for in terms of documentation?

Regards
Mats

**Comment by Mats-SX** [comment]
I hope I have been able to offer you some assistance. Please do not hesitate to open additional issues for any additional hurdles you may face. I believe for the original problems mentioned in this issue, there has been some success in resolving them.

I will close this issue. Please reopen to continue the conversation here, or in a new issue.

**Comment by mullerhai** [comment]
@Mats-SX  yes, I think you have solve the problem I meet when use gds .
