### ISSUE TITLE
Missing node+properties for Cypher on GDS projections

### ISSUE THREAD

**Issue by rruchala** [neo4j/graph-data-science#147]
**Describe the bug**

I tried to run Cypher on GDS graph with 4.3+GDS1.8 and recently 4.4+GDS1.8  as described in example https://neo4j.com/docs/graph-data-science/current/management-ops/create-cypher-db/ 

There is no error during projection itself and also database is being created. However, there are no nodes present in new database although relationships are there. That way final query is getting an error - snapshot attached.

**To Reproduce**

GDS version: 1.8
Neo4j version: 4.4
Operating system: Mac

Follow example steps from https://neo4j.com/docs/graph-data-science/current/management-ops/create-cypher-db/ 

**Expected behavior**
Failure on last query example. No nodes+properties present within graphDB from projection.

**Additional context**
Snapshot attached
![cypherGDSmissingNodes](https://user-images.githubusercontent.com/12023463/146153134-26e5c582-1da0-43a3-82c2-852267b65f45.png)

**Comment by DarthMax** [comment]
Hello @rruchala,
thank you for reporting the issue. 
We have investigated the problem and probably found a solution, which will most likely be included in the next patch release of GDS.

Thanks again!
Best,  
Max

**Comment by s1ck** [comment]
@rruchala a fix will be included in 1.8.2 which is due this week.
