### ISSUE TITLE
Port test cases from FastRPTest to FastRPGdlTest

### ISSUE THREAD

**Issue by FlorentinD** [neo4j/graph-data-science#149]
In our library, our test graphs are either based on a Neo4j db or a [gdl](https://github.com/s1ck/gdl) graph.
As the Neo4j db introduces an unnecessary indirection, we prefer using gdl graphs when possible.

For our embedding algorithm FastRP, we started porting the unit tests to use a gdl graph.
It would be great if we could port the remaining test cases from the [FastRPTest](https://github.com/neo4j/graph-data-science/blob/master/algo/src/test/java/org/neo4j/gds/embeddings/fastrp/FastRPTest.java) to gdl tests as started in [FastRPGdlTest](https://github.com/neo4j/graph-data-science/blob/master/algo/src/test/java/org/neo4j/gds/embeddings/fastrp/FastRPGdlTest.java)

**Comment by airtyon** [comment]
hi @FlorentinD, is this one still available? could I pick this as a first time contributor?

**Comment by FlorentinD** [comment]
hey @airtyon ,
happy to hear you are interested!
yes this is still available.

if you have any questions, just write on this issue. 
You can find several examples in our library where we used GDL in our tests.

Due to Christmas, we might not respond in the next days though.

Happy coding and merry Christmas 🎄
