### ISSUE TITLE
Closeness centrality algorithm gives incorrect results for directed graphs

### ISSUE THREAD

**Issue by danielprecog** [neo4j/graph-data-science#153]
**Describe the bug**
Closeness centrality gives incorrect results (at least for directed graphs)

**To Reproduce**

GDS version: 1.8.0
Neo4j version: 4.4.0
Operating system: (Ubuntu 20.04.3 LTS)

Create a graph with three nodes (0,1,2)

Node 0 is connected with Node 1 by NeededEdge
Node 1 is connected with Node 2 by EffectEdge
Node 2 is connected with Node 1 by EffectEdge

![image](https://user-images.githubusercontent.com/84659356/147566458-6bebe02a-b13b-4ad5-9101-39bb48c7b832.png)

--
If we run closeness centrality with the natural graph orientation (see query in screenshot), we get:
![Screenshot from 2021-12-28 13-54-32](https://user-images.githubusercontent.com/84659356/147567113-86cdaa3a-e905-445a-91a5-d6c30eeda4c3.png)

{0: 0, 1:0.5, 2: 0.3333}
If we run it with the reversed orientation

![Screenshot from 2021-12-28 13-54-53](https://user-images.githubusercontent.com/84659356/147567864-ff35b49b-7a72-478b-8f51-25006bfd74d0.png)

{0: 0, 1:2.0, 2:2.0}

The results are incorrect, which is obvious because Node 0 is connected to Node 1 but always has a closeness centrality of 0.
**Expected behavior**

If inward edges are used for calculation, the result should be

{0: 0.0, 1: 1.0, 2: 0.6666666666666666} if the Wasserman-Faust correction is used
{0: 0.0, 1: 1.0, 2: 0.6666666666666666} if it is not

If outward edges are used for calculation, the result should be:

{0: 0.6666666666666666, 1: 0.5, 2: 0.5} if the Wasserman-Faust correction is used
{0: 0.6666666666666666, 1: 1.0, 2: 1.0} if it is not

**Additional context**
The [networkx implementation](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.centrality.closeness_centrality.html#networkx.algorithms.centrality.closeness_centrality) is correct (it uses the inward edges for calculation)

**Comment by IoannisPanagiotas** [comment]
Hi Daniel,

Thank you for bringing this to our attention. We have  added a [fix](https://github.com/neo4j/graph-data-science/commit/deaf82a7af431a3c119572b83a02a71869d970a8) that hopefully solves the issue. 

It should be available with the next release.

**Comment by danielprecog** [comment]
Do you have the Wasserman- Faust correction on? The test case you are using gives the same result whether it is on or off, so there needs to be a test that indicates whether the parameter is being used correctly.

It would be good if the correction was exposed as a parameter, so that we could choose whether to use the correciton.

**Comment by IoannisPanagiotas** [comment]
Hi again,

The Wasserman-Faust correction is already available as an optional  boolean parameter called _improved_  although it seems undocumented as of now.

**Comment by IoannisPanagiotas** [comment]
Hi again,

Yes, this should hopefully work. I agree about the tests , we will be handling  it shortly;

Best

**Comment by danielprecog** [comment]
Any update on this? A new version has been released (1.8.3), and the correction is not there.
I also don't see any new tests.

Did you mean the bug fix update would be in in version 1.9?

**Comment by IoannisPanagiotas** [comment]
Hello again,

It was indeed intented for the next proper release, but it probably should  have been backported to 1.8.3...
I will make sure it is included in the next release be it a patch or not. 

We have also expanded on testing to ensure that WF works properly on directed graphs now.

**Comment by danielprecog** [comment]
Any ETA on the next version with the fix? If I shouldn't ask here, please tell me where to ask.

**Comment by IoannisPanagiotas** [comment]
Hello again,

It should be out hopefully towards the end of the month.

Best,
Ioannis.

**Comment by jjaderberg** [comment]
@danielprecog The fix is included in 1.8.4, which was just released.

**Comment by jjaderberg** [comment]
fix is released, closing
