### ISSUE TITLE
LCC acting weird after you project a REVERSED graph and run Node similarity

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#157]
I've notice this on a bigger graph, but managed to reproduce it on a tiny graph:

Construct the graph:

```
CREATE
  (alice:Person {name: 'Alice'}),
  (bob:Person {name: 'Bob'}),
  (carol:Person {name: 'Carol'}),
  (dave:Person {name: 'Dave'}),
  (eve:Person {name: 'Eve'}),
  (guitar:Instrument {name: 'Guitar'}),
  (synth:Instrument {name: 'Synthesizer'}),
  (bongos:Instrument {name: 'Bongos'}),
  (trumpet:Instrument {name: 'Trumpet'}),

  (alice)-[:LIKES]->(guitar),
  (alice)-[:LIKES]->(synth),
  (alice)-[:LIKES]->(bongos),
  (bob)-[:LIKES]->(guitar),
  (bob)-[:LIKES]->(synth),
  (carol)-[:LIKES]->(bongos),
  (dave)-[:LIKES]->(guitar),
  (dave)-[:LIKES]->(synth),
  (dave)-[:LIKES]->(bongos);
  ```

Project a reversed relationship:

```
CALL gds.graph.create(
    'myGraph',
    ['Person', 'Instrument'],
    {LIKES: {orientation:'REVERSE'}}
);
```

Then run node similarity algorithm:

```
CALL gds.nodeSimilarity.mutate('myGraph', {
    mutateRelationshipType: 'SIMILAR',
    mutateProperty: 'score'
})
YIELD nodesCompared, relationshipsWritten
```

And finally, execute the LCC algorithm:

`CALL gds.localClusteringCoefficient.stream('myGraph', {nodeLabels:['Instrument'], relationshipTypes:['SIMILAR']})
`

Returns

nodeId | localClusteringCoefficient
-- | --
5 | 0.0
6 | 0.0
7 | 0.0
8 | 0.0

Now what is funny is that if I don't include the nodeLabels parameter, it works correctly:

```
CALL gds.localClusteringCoefficient.stream('myGraph', { relationshipTypes:['SIMILAR']})
```

nodeId | localClusteringCoefficient
-- | --
0 | 0.0
1 | 0.0
2 | 0.0
3 | 0.0
4 | 0.0
5 | 1.0
6 | 1.0
7 | 1.0
8 | 0.0

Now, to verify the relationships, I written them back to the database:

```
CALL gds.graph.writeRelationship('myGraph', 'SIMILAR')
```
and the viz is:
![Screenshot from 2022-01-09 16-41-13](https://user-images.githubusercontent.com/19948365/148689462-9eeea9b4-a510-4d84-b901-95484edef36a.png)

So the LCC results should be identical fot the three nodes when I include `nodeLabels` parameter or not.

p.s. In my bigger graph, also the `gds.degree` is acting funny when I play with orientation parameter in the algo, but I couldn't reproduce it here. Also, the bug doesn't appear if the projected relationship is not reversed. However, I am more suspicious of the `nodeLabels` param than the reversed orientation.

Tested with 1.7.1 version and also 1.8.1

**Comment by s1ck** [comment]
@tomasonjo Thanks for reporting this. Your suspicion is correct, it is related to the `nodeLabels` filter and more precisely to how triangle count computes neighborhood intersections (triangle count is used within LCC). We'll push a fix, so expect this to work in the next patch release.
