### ISSUE TITLE
Accurate GraphSage Embedding Generation

### ISSUE THREAD

**Issue by laxmimerit** [neo4j/graph-data-science#159]
Hi,
I am training the `GraphSage` model for embeddings with 64 dim like below

```
CALL gds.beta.graphSage.train(
  'products',
  {
    modelName: 'productsGraphSage',
    nodeLabels: ['Group', 'Group1'],
    relationshipTypes: ['HAS_GROUP1'],
    featureProperties: ['group1_count', 'length'],
    embeddingDimension: 64,
    projectedFeatureDimension: 2,
    epochs: 10
  }
)
```

The model converged but generated embeddings are quite close to each other. Generated embeddings are always in this range 
```
[0.0125671e-16, 0.0125672e-16, .......]
```
I am doing binary node classification by taking embeddings as input. The classification result gives me accuracy near to 50% only.
</b>
However, If I generate embeddings with `FastRP` algo, generated embeddings are quite good. It varies from +1 to -1 and my node classification algorithm also gives me 95% accuracy.
Seems like something is missing in `GraphSage` algo. Can someone help me to identify the actual cause of this issue?
```
DB Version: 4.4.3
GDS Version: 1.8.2
Neo4j Desktop: 1.4.12
OS: Windows 11
```

**Comment by laxmimerit** [comment]
Hi,
Thanks for the comment. My question is that generated embedding has almost 0 (~1.e-5) variance which doesn't seem right. There are 1M nodes and all of these nodes are projected very close to each other.

**Comment by FlorentinD** [comment]
Hello @laxmimerit,
I could imagine problems with `searchDepth` of 5. Are there only relationships from `Group` to `Group1` or also the backwards?

There are a lot of parameters you can tune.
People often also try to lower the `learning rate` and `tolerance`.

**Comment by laxmimerit** [comment]
Yes it is just Group to Group1. I tried lowering and increasing learning rate but no luck. I also tried with relu and sigmoid activation functions.

**Comment by FlorentinD** [comment]
Then your graph might not very suited for GraphSAGE as the topology is very simplistic.
Is there a specific reason why you want to use GraphSAGE instead of FastRP?

**Comment by laxmimerit** [comment]
May be you are correct. As such there is no specific requirement to use GraphSage. I was looking for something where I don't need to retrain model everytime. 

So if I use FastRP to train my ml model once for node classification. And next time if I regenerate embeddings for additional nodes on new data, I think old ml model won't work because this time embedding is changed. Right?

**Comment by FlorentinD** [comment]
I could thing of different options:
(1) So you could further try to tune the parameters of GraphSage. An additional property could also help, by running f.i. graph algorithm such as PageRank. 

(2) You can try to use the `randomSeed` in FastRP as these embeddings should be more stable unless your graph changes too much. Internally our seeding uses the node ids to initialize each embedding. Then your ml model could still work.

**Comment by laxmimerit** [comment]
Thanks for your feedback. I will try with random seed.

**Comment by FlorentinD** [comment]
Can you provide us with your dataset as a neo4j dump?
This could help us to improve our GraphSage implementation in the future :)

**Comment by laxmimerit** [comment]
Hi,
I am afraid I can't share dataset. I had tested Graphsage on
game-of-thrones dataset as well. I didn't get good result with graphsage
but FastRP was doing good.

**Comment by FlorentinD** [comment]
Ok I understand.
Hope you can solve your problem by using FastRP for now.

I would close this issue for now, but feel free to reopen it :)
