### ISSUE TITLE
BUG: triangleCount.write returns averageClusteringCoefficient 0.0 if we don't set clusteringCoefficientProperty

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#16]
Basically, what the title says. Average clustering coefficient returns 0.0 if we don't set the clusteringCoefficientProperty parameter.

Example:

```
CREATE (alice:Person {name: 'Alice'}),
       (michael:Person {name: 'Michael'}),
       (karin:Person {name: 'Karin'}),
       (chris:Person {name: 'Chris'}),
       (will:Person {name: 'Will'}),
       (mark:Person {name: 'Mark'}),
       (michael)-[:KNOWS]->(karin),
       (michael)-[:KNOWS]->(chris),
       (will)-[:KNOWS]->(michael),
       (mark)-[:KNOWS]->(michael),
       (mark)-[:KNOWS]->(will),
       (alice)-[:KNOWS]->(michael),
       (will)-[:KNOWS]->(chris),
       (chris)-[:KNOWS]->(karin)
```

Run algo without clusteringCoefficientProperty  parameter:

```
CALL gds.alpha.triangleCount.write({
  nodeProjection: 'Person',
  relationshipProjection: {
    KNOWS: {
      type: 'KNOWS',
      orientation: 'UNDIRECTED'
    }
  },
  writeProperty: 'triangles'
})
YIELD nodeCount, triangleCount, averageClusteringCoefficient
```

Returns 0.0 as averageClusteringCoefficient, which is not correct and could be misleading.

If we add clusteringCoefficientProperty to parameter:

```
CALL gds.alpha.triangleCount.write({
  nodeProjection: 'Person',
  relationshipProjection: {
    KNOWS: {
      type: 'KNOWS',
      orientation: 'UNDIRECTED'
    }
  },
  writeProperty: 'triangles',
  clusteringCoefficientProperty:'coefficient'
})
YIELD nodeCount, triangleCount, averageClusteringCoefficient
```
It correctly returns 0.6055555555555555 as averageClusteringCoefficient.

I imagine that calculating averageClusteringCoefficient takes some additional time and can be skipped if not needed, so I would treat it similarly to how we treat optional return path in randomWalk, which is make it null by default and add to docs how to make it non-null, i.e. add clusteringCoefficientProperty

**Comment by DarthMax** [comment]
Resolved by the new TC implementation in 1.2
