### ISSUE TITLE
Add failIfMissing parameter to gds.beta.model.drop

### ISSUE THREAD

**Issue by devineyfajr** [neo4j/graph-data-science#160]
**Is your feature request related to a problem? Please describe.**

scripts fail if they include gds.beta.model.drop for a nonexistent model

**Describe the solution you would like**

add the parameter, as in gds.graph.drop

**Describe alternatives you have considered**

add an additional method gds.beta.model.dropIfExists 

**Additional context**

**Comment by FlorentinD** [comment]
Thank you for your request! 
We picked up your request and implemented this for the next release.
