### ISSUE TITLE
Syntax proposal: Rename triangleCount.write parameter from writeProperty to triangleCountProperty

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#17]
As  `alpha.triangleCount.write` has two different options of results to write back:

- triangle count
- clustering coefficient

and for clustering coefficient we already use **clusteringCoefficientProperty**, maybe it makes sense that we also use for triangle count parameter **triangleCountProperty** instead of **writeProperty** for more clarity.

**Comment by Mats-SX** [comment]
@tomasonjo What would you think of this kind of syntax:

```
CALL gds.triangleCount.write('g', {
  writeProperties: {
    triangleCount: 'tc',
    localClusterinCoefficient: 'lcc'
  }
})
```

**Comment by tomasonjo** [comment]
I like it, very descriptive.

**Comment by Mats-SX** [comment]
We will aim for this in the preview release of `1.2.0`, where `triangleCount` will move to the production-ready tier. This is the first algorithm (in the top tier) that computes two values for each node so it poses some API challenges. Thanks a lot for the fast feedback!

**Comment by Mats-SX** [comment]
I'm sorry but I spoke too soon. This syntax was considered, but we decided to go in another direction, by splitting the concerns into two different procedures. You will find `gds.triangleCount.<mode>()` in the `1.2.0-alpha01` but it doesn't compute any clustering coefficients, local or average.

Instead, we will build a dedicated procedure to calculate clustering coefficients based on triangle counting. This will also arrive in 1.2, but not in the first alpha.

**Comment by tomasonjo** [comment]
Not relevant anymore as the triangle count and clustering coefficient was split into two procedures.
