### ISSUE TITLE
support Bellman Ford algorithm

### ISSUE THREAD

**Issue by jerryleooo** [neo4j/graph-data-science#174]
**Is your feature request related to a problem? Please describe.**

To find a negative cycle in a graph, we may need to support [Bellman Ford algorithm](https://en.wikipedia.org/wiki/Bellman%E2%80%93Ford_algorithm)

**Describe the solution you would like**

Support Bellman Ford algorithm in Neo4j

**Describe alternatives you have considered**

Support other algorithms that can used to find a negative cycle

**Additional context**

I come here from https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/116 @jexp

**Comment by Mats-SX** [comment]
@jerryleooo Thanks for raising this issue with us. We have noted your request and added it to our backlog for future work. Unfortunately, we are not looking towards adding the Bellman-Ford algorithm at this time, so I cannot give you an estimated delivery date.

**Comment by jerryleooo** [comment]
Thank @Mats-SX adding it to backlog👍

**Comment by IoannisPanagiotas** [comment]
Hello @jerryleooo,

We are happy to announce that with  the new GDS release 2.4  we have finally added support for the Bellman-Ford algorithm. 

You can find available documentation for how to use algorithm [here](https://neo4j.com/docs/graph-data-science/current/algorithms/bellman-ford-single-source/)  and the newest version of our library in the [download centre ](https://neo4j.com/graph-data-science-software/)

I will now close this thread, feel free to  let us  know if you have any other questions either here or in another issue.
Best regards,
Ioannis.
