### ISSUE TITLE
randomWalk ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by RGDZ-GZU** [neo4j/graph-data-science#176]
**Describe the bug**

GDS is a great project and has been clicked on star， but when running randomWalk, the program timed out.

I think the main problem is when I rebuild the graph again after deleting the last graph
The node ID generated by neo4j was extremely large for me, but the total number of nodes was very small. As a result, when I specified sourceNodes in randomWalk, the id(node) passed in would be extremely large, exceeding the number of nodes, resulting in the abnormal operation of randomWalk

![node-total](https://user-images.githubusercontent.com/50510019/160795282-6a407be8-f1c6-420c-bec0-17aa7a042ec1.png)

![node_id](https://user-images.githubusercontent.com/50510019/160795343-e9de65a3-4906-410d-bab0-b97b87237a20.png)

cypher-command:
```
match (n:MetaAttackPatternNode)
with collect(n) as sourceNodes
call gds.beta.randomWalk.stream(
    "project1",
    {
        sourceNodes:sourceNodes
    })
yield nodeIds, path
return nodeIds, path
```
Error log:
```
2022-03-30 08:58:08.192+0000 INFO  [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:64690] ] RandomWalk :: Start
2022-03-30 08:58:08.193+0000 INFO  [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:64690] ] RandomWalk :: create walks :: Start
Exception in thread "Thread-25" java.lang.ArrayIndexOutOfBoundsException: Index 1828 out of bounds for length 65
	at org.neo4j.gds.core.utils.paged.HugeIntArray$SingleHugeIntArray.get(HugeIntArray.java:277)
	at org.neo4j.gds.core.huge.CompressedAdjacencyList.degree(CompressedAdjacencyList.java:121)
	at org.neo4j.gds.core.huge.HugeGraph.degree(HugeGraph.java:322)
	at org.neo4j.gds.traversal.RandomWalk$RandomWalkTask.run(RandomWalk.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.neo4j.internal.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:110)
	Suppressed: java.lang.ArrayIndexOutOfBoundsException: Index 1829 out of bounds for length 65
		... 10 more
	Suppressed: java.lang.ArrayIndexOutOfBoundsException: Index 1831 out of bounds for length 65
		... 10 more
	Suppressed: java.lang.ArrayIndexOutOfBoundsException: Index 1830 out of bounds for length 65
		... 10 more

```

**To Reproduce**

GDS version: 2.0.0
Neo4j version: 4.4.4
Operating system: MacOS-Monterey-12.3(Inter)

1. create graph
2. detach delete graph
3. create graph
4. run randomWalk

**Expected behavior**

Ids and PATH should be returned normally

**Additional context**

**Comment by RGDZ-GZU** [comment]
After I look at the source code, the code I had a problem with should look like the following, `assert index < size`

This assertion determines the size of the index and array

However, the received index is nodeId

So when I have a very large nodeId, greater than the array of nodes created by `graph.project` I throw an exception

<img width="767" alt="image" src="https://user-images.githubusercontent.com/50510019/160906248-c526f7fc-3d13-490a-8d51-4385cf10c9f8.png">

<img width="750" alt="image" src="https://user-images.githubusercontent.com/50510019/160906515-a6b9ce7d-7523-4139-bc83-ad95ab313cb2.png">


So what do we need to fix if this happens? This seems to be about all `sourceNodes` bug, other algorithms that need to pass in sourceNodes parameters might have this problem as well

😅😅😅

**Comment by RGDZ-GZU** [comment]
I tried to build the debugger from source code, but the JAR I built myself didn't work

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/50510019/160908749-6d8e0f96-644d-458b-85b9-0550ed6b6ab0.png">

If you can solve this problem, thank you very much

**Comment by DarthMax** [comment]
Hej @RGDZ-GZU, thank you for submitting the issue. You where indeed correct that the node IDs configured as `sourceNodeIds` where not mapped into the internal id space. 
I have created a fix that should be merged within the coming days. 
The fix should be available in the 2.0.1 patch release.

Best, Max

**Comment by RGDZ-GZU** [comment]
I made a simple improvement to `ListNodeSupplier`, using `graph.tomappedNodeId` to convert to an internally mapped `ID` when returning `nextNode`, and it now works fine

This may be a feasible and simple temporary solution

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/50510019/161231781-1a51623c-f9d2-42a2-a8fe-ebb4de350584.png">

**Comment by DarthMax** [comment]
Yes that is basically the fix that I developed. :)

**Comment by vnickolov** [comment]
@andrew-delph this is unrelated to `randomWalk` can you please create a separate issue and share more details about the case when this is failing, like dataset, graph project queries. Thank you in advance.
