### ISSUE TITLE
Pregel - Add logger to init and compute context

### ISSUE THREAD

**Issue by FlorentinD** [neo4j/graph-data-science#180]
**Is your feature request related to a problem? Please describe.**

Pregel is a vertex-centric computation model to define your own algorithms via a user-defined compute function. 
Exposing the Progress logger via the `org.neo4j.gds.beta.pregel.context.InitContext` and `org.neo4j.gds.beta.pregel.context.ComputeContext` would allow users to log additional information to the neo4j log.

Motivated by #175.

This card is in our backlog, but is also a good-first issue.

**Comment by frank-zsy** [comment]
As I opened the issue #175, I would like to take the issue~
