### ISSUE TITLE
Cannot download graph-data-science plugin in any way.

### ISSUE THREAD

**Issue by cmartinotti** [neo4j/graph-data-science#181]
Hello, 

I'm trying to install gds on a docker container. to do that i launch the following command:
```
 docker run -p7474:7474 -p7687:7687 -it -v $HOME/neo4j/data/data_jdl_geochemical_1:/data -v $HOME/neo4j/logs:/logs -v $HOME/neo4j/import:/var/lib/neo4j/import -v $HOME/neo4j/plugins:/plugins -e NEO4JLABS_PLUGINS='["apoc", "graph-data-science"]' --env NEO4J_dbms_connector_https_advertised__address="localhost:7473" --env NEO4J_dbms_connector_http_advertised__address="localhost:7474" --env NEO4J_dbms_connector_bolt_advertised__address="localhost:7687" --env NEO4J_AUTH=neo4j/$PASSWORD neo4j:latest
```

This fails to download the gds.jar file and basically downloads a 0kb file in the /plugins directory that makes the container crash.

Now i tried to download the plugin manually, but if I try any of the links in the neo4j download center (https://neo4j.com/download-center/#algorithms  ) which all pont to this .ninjas domains (example: https://graphdatascience.ninja/neo4j-graph-data-science-2.0.1.zip ) the domain name fails to resolve, as the url doesn't exist. 

I think there lies the problem, is this a bug or am I doing something wrong?

**Comment by jjaderberg** [comment]
@cmartinotti Are you able to download other resources from the download center? The URL is correct and works fine for me (and as far as I know for most users)

**Comment by jjaderberg** [comment]
Have you successfully downloaded GDS from your university network before?
We recently changed our setup for serving GDS downloads, and if there are problems for users we want to know about it. Any idea why your university would block that URL?

**Comment by jjaderberg** [comment]
Closing for now, keeping a reference if we see more reports of problems.
