### ISSUE TITLE
Importing stream mode algorithm developed using pregel to neo4j

### ISSUE THREAD

**Issue by mohanedmoh** [neo4j/graph-data-science#186]
**Describe the bug**

I'm trying to import the example from the pregel API SSSP algorithm and whenever I import my plugin file (.jar), all algorithms modes are shown in the neo4j database except stream mode.

is there a specific way to import stream modes?
**To Reproduce**

GDS version: 2.0.0
Neo4j version: 4.4.4
Operating system: Windows 10

- [ ] Graph/dataset to reproduce the bug.  Alternatively describe as much as possible the data, e.g., graph size and other schema/structure details.
- [ ] Create Query 
- [ ] Further queries

**Expected behavior**

**Additional context**

**Comment by s1ck** [comment]
Hi. Are you building the plugin manually or did you download a packaged GDS jar? As you can see in https://github.com/neo4j/graph-data-science/blob/master/examples/pregel-example/src/main/java/org/neo4j/gds/beta/pregel/sssp/SingleSourceShortestPathPregel.java#L37 the algorithm is annotated with `@PregelProcedure` and it's configured to generate the `STREAM` procedure. Did you change something in that file? 

> all algorithm modes are shown

Do you mean specifically for SSSP?

**Comment by mohanedmoh** [comment]
hi there, so I figured that if I wanted to export the stream mode I should use the open GDS command, not the usual one ./gradlew:shadowCopy. 
Thank you for your replay
