### ISSUE TITLE
I found an error in the official document

### ISSUE THREAD

**Issue by AkuZcy** [neo4j/graph-data-science#189]
neo4j version :3.5.1
GDS version : 1.1.7
neo4j doc link : https://neo4j.com/docs/graph-data-science/1.1/alpha-algorithms/shortest-path/

This error is shown in the picture below

![image](https://user-images.githubusercontent.com/48719185/167094096-81c5e153-5b92-45dc-80dc-542d4fb15c66.png)

**Comment by jjaderberg** [comment]
Thanks @AkuZcy that's now fixed
