### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by lavkan** [neo4j/graph-data-science#199]
I am trying to install this package on macOS Big Sur (11.6.3). I followed the instructions as specified in the page. When I run
`sdk install java 11.0.13-tem` my machine complains:

```
Stop! java 11.0.13-tem is not available. Possible causes:
 * 11.0.13-tem is an invalid version
 * java binaries are incompatible with your platform
 * java has not been released yet
```
and as a result `./gradlew check` fails. I was able to successfully install this in macOS Catalina. So I suppose the java binaries are incompatible with the platform. Kindly let me know what should I do to successfully install this package in my machine.

Thank you very much.

**Comment by FlorentinD** [comment]
Hello @lavkan,
you can also use another distribution of Java 11, `11.0.13-tem` is only a recommendation.
To see the available distributions on your machine, you can use `sdk list java`.
There was a recent response by @Mats-SX about Java distributions on macOS (https://github.com/neo4j/graph-data-science/pull/193#issuecomment-1128496908),

**Comment by lavkan** [comment]
Hello @FlorentinD,

I did try with the latest versions, eg. 11.0.15 - as suggested by sdk list java - still no luck. I will see the comment #193 and update this space.

**Comment by lavkan** [comment]
@FlorentinD 
Update:
I downloaded the repo once again, and installed java 17.0.3-tem and 11.0.15 that were available for my OS successfully using sdk (sdk install java 17.0.3-tem   and sdk install java 11.0.15-tem), but yet ./gradlew check   failed to build. I am pasting the messages I get below. Please let me know.
 
   
./gradlew check   

> Task :algo:test

GraphSageModelTrainerTest > batchesPerIteration(double, boolean, int) > org.neo4j.gds.embeddings.graphsage.GraphSageModelTrainerTest.batchesPerIteration(double, boolean, int)[1] FAILED
    org.opentest4j.AssertionFailedError at GraphSageModelTrainerTest.java:333
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.commons.lang3.reflect.FieldUtils (file:/Users/lavanyakannan/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-lang3/3.12.0/c6842c86792ff03b9f1d1fe2aab8dc23aa6c6f0e/commons-lang3-3.12.0.jar) to field sun.nio.ch.FileChannelImpl.positionLock
WARNING: Please consider reporting this to the maintainers of org.apache.commons.lang3.reflect.FieldUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Results: FAILURE (3446 tests, 3444 successes, 1 failures, 1 skipped)

3446 tests completed, 1 failed, 1 skipped

> Task :algo:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':algo:test'.
> There were failing tests. See the report at: file:///Users/lavanyakannan/Documents/PregelAPI/downloaded/graph-data-science-master/algo/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 38s
74 actionable tasks: 1 executed, 73 up-to-date

**Comment by FlorentinD** [comment]
Hello @Iavkan,
thats good news!
This GraphSage test is rather recent and not tested on a MacOS, you can simply ignore it (by adding a `@Disabled` annotation locally).

 I will look into making this test stable :)

**Comment by s1ck** [comment]
Closing. @lavkan please reopen if the problem still exists.
