### ISSUE TITLE
Latest github release notes compatibility kinda misleading

### ISSUE THREAD

**Issue by HashRocketSyntax** [neo4j/graph-data-science#20]
https://github.com/neo4j/graph-data-science/releases/tag/1.1.0-alpha02
`The GDS library is compatible with Neo4j 3.5 versions greater than 3.5.8`
^ Wouldn't this be better phrased as `3.5.9 or later`? I installed and tinkered with 3.5.8 after reading that quickly.

**Comment by AliciaFrame** [comment]
Thanks for pointing this out -- I updated it in the most recent release notes for clarity :)
