### ISSUE TITLE
neo4j-kernel-adapter-2.1.0 fails to find neo4j-kernel-adapter-4.4.7-drop01.0 when referencing from maven

### ISSUE THREAD

**Issue by cuneyttyler** [neo4j/graph-data-science#202]
When I try to build my for of GDS maintained for building additional algorithms when building neo4j-kernel-adapter-2.1.0, it fails to find neo4j-kernel-adapter-4.4.7-drop01.0. In the maven repository, in 2.0.4 version of neo4j-kernel-adapter, there are links to neo4j-kernel-adapter-4.4.7-drop01.0, although not in 2.0.1. See here : https://mvnrepository.com/artifact/org.neo4j.gds/neo4j-kernel-adapter/2.0.4 and  https://mvnrepository.com/artifact/org.neo4j.gds/neo4j-kernel-adapter/2.1.0. Can you update these references so that when we access neo4j-kernel-adapter via maven it don't fails to build.

Thanks.

**Comment by vnickolov** [comment]
Hi @cuneyttyler, 

We have just released GDS 2.1.1, using this version should solve the issue with the dependency. You may want to give it some time to get published to Maven Central though.

Please let us know if you have any further issues.

**Comment by cuneyttyler** [comment]
Thanks, it's ok and working now.

**Comment by vnickolov** [comment]
Thank you @cuneyttyler, closing this issue now.
