### ISSUE TITLE
Similarity Relationship -Merge relationship instead of create

### ISSUE THREAD

**Issue by andyhegedus** [neo4j/graph-data-science#205]
Please see this [post for example use case](https://community.neo4j.com/t5/neo4j-graph-platform/have-gds-similarity-write-to-existing-relationship/td-p/56681):

Similarity write operations create new relationships. The write operation also create a score property.  The request is for the creation of the similarity relationship to use merge instead of create.  If an existing relationship exists the score property is added to that relationship or if existing is changed tot he new value.  This would prevent to similarity relationship being created between two nodes and the confusion on how to access them.
Andy

**Comment by FlorentinD** [comment]
Hey @andyhegedus,
Thank you for your feature request!. We saw on your linked post, there was a work-around suggested.
I added your idea to our backlog and we will consider it in the future.

Feel free to reopen the issue if you have more input on this request :)
