### ISSUE TITLE
UnableToConnectError: {code: Neo.ClientError.Statement.SyntaxError}

### ISSUE THREAD

**Issue by yangnianen** [neo4j/graph-data-science#206]
Can't connect remotely, but it can be changed to other frameworks，  example : from neo4j import GraphDatabase
BUG :
UnableToConnectError: {code: Neo.ClientError.Statement.SyntaxError} {message: Unknown function 'gds.version' (line 1, column 8 (offset: 7))
"RETURN gds.version() AS `gds.version()`"
        ^}

**Comment by s1ck** [comment]
Are you sure that the GDS plugin is installed on the server you're trying to connect to?
