### ISSUE TITLE
Bug: gds.graph.writeNodeProperties always returns propertiesWritten 0

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#21]
Create graph:

`CREATE (c:Node)-[:REL]->(:Node)`

Load the graph:

`CALL gds.graph.create('test','Node','REL')`

Mutate a property:

`CALL gds.pageRank.mutate('test',{mutateProperty:'pagerank'})`

and finally, write it back:

`CALL gds.graph.writeNodeProperties('test',['pagerank'])`

propertiesWritten result is 0, even though it has written back two properties

**Comment by kingebere** [comment]
Relationship count returns zero for call Gds.graph.write
