### ISSUE TITLE
Cypher Projection + SubGraph

### ISSUE THREAD

**Issue by MattyCrowther** [neo4j/graph-data-science#210]
Hi,
I am unsure if this is an issue.
I am using the cypher projection to project a graph.
From this I am using the gds.beta.graph.project.subgraph to further modify the graph.
Are these two functions compatible with one another? Or so I need to do a native projection instead of a cypher projection?
Because when it is does this way, I get errors such as:

neo4j.exceptions.ClientError: {code: Neo.ClientError.Procedure.ProcedureCallFailed} {message: Failed to invoke procedure `gds.beta.graph.project.subgraph`: Caused by: org.neo4j.gds.beta.filter.expression.SemanticErrors: Semantic errors while parsing expression:
Unknown label `ATC`.

**Comment by MattyCrowther** [comment]
Just a follow-up to this when I perform a cypher-projection the schema is as follows:
{'relationships': {'__ALL__': {}}, 'nodes': {'__ALL__': {}}}
Is this always the case that the schema is unable to be accurately derived when a cypher-projection occurs?

**Comment by FlorentinD** [comment]
Hello @MattyCrowther ,
Also with cypher projections you can have a graph schema in the GDS graph.
I can recommend you to look at https://neo4j.com/docs/graph-data-science/current/graph-project-cypher/#_multi_graph for how to also project the labels and types.

**Comment by MattyCrowther** [comment]
Sorry, yes you're correct.
Thanks very much for your help!
