### ISSUE TITLE
Modularity metric

### ISSUE THREAD

**Issue by devineyfajr** [neo4j/graph-data-science#211]
**Is your feature request related to a problem? Please describe.**

Would like to be able to calculate the modularity metric for identified communities, similar to the conductance metric method gds.alpha.conductance

**Describe the solution you would like**

Either a separate metric, ala gds.modularity.???, or a generalized metric calculator gds.community-metric.??? where "conductance" and "modularity" are parameters.

**Describe alternatives you have considered**

**Additional context**

**Comment by vnickolov** [comment]
Hello @devineyfajr thank you for raising this, we have reviewed it and added this to our backlog. Will keep you updated when we start the work and have this feature available. We aim for the `alpha` namespace and decided to have a separate procedure for the modularity metric.

**Comment by vnickolov** [comment]
Hello @devineyfajr, we have implemented procedures to compute modularity for given communities and the functionality will be available in the latest release. If you are building the library the procedures are:
- `gds.alpha.modularity.stream(graphName, configuration)`
- `gds.alpha.modularity.stats(graphName, configuration)`

There is mandatory `communityProperty` configuration parameter that should be the node property holding the pre-computed community ID.

Please let us know if you have questions or comments.
