### ISSUE TITLE
neo4j version 4.4.9 is not listed in versions.json

### ISSUE THREAD

**Issue by mattmichal** [neo4j/graph-data-science#213]
**Describe the bug**
https://graphdatascience.ninja/versions.json does not have an entry for neo4jversion 4.4.9. When starting the container version of neo4j this causes the app to exit.

**To Reproduce**
Run container image neo4j:4.4.9 with NEO4JLABS_PLUGINS: '["graph-data-science"]'

**Additional context**
```
Fetching versions.json for Plugin 'graph-data-science' from https://graphdatascience.ninja/versions.json
Installing Plugin 'graph-data-science' from null to /var/lib/neo4j/plugins/graph-data-science.jar 
```

**Comment by knutwalker** [comment]
Hi @mattmichal,

thanks for pointing this out, it's now listed and can be used.
