### ISSUE TITLE
FastRP algorithms gives zeros as embeddings 

### ISSUE THREAD

**Issue by meg261995** [neo4j/graph-data-science#218]
Hi,

Can anyone explain me why FastRP gives zeros as embeddings for nodes?

**Comment by FlorentinD** [comment]
Do you have orphan nodes (nodes with 0 relationships)?
We also have a description in our docs as our `nodeSelfInfluence` parameter is a way too avoid this (https://neo4j.com/docs/graph-data-science/current/machine-learning/node-embeddings/fastrp/#algorithms-embeddings-fastrp-node-self-influence).

**Comment by meg261995** [comment]
Yes actually. The relationshipType I have mentioned in the configuration is null for all the nodes with zero embeddings

**Comment by FlorentinD** [comment]
Then I would suggest to try out the `nodeSelfInfluence` parameter.
Hope this solves your problem!

**Comment by meg261995** [comment]
Can u give an example please? It says I need to provide a float value. Suppose I give a value of 2.0 how would that affect the result?

**Comment by FlorentinD** [comment]
`Similarly, nodeSelfInfluence behaves like an iteration weight for a 0 th iteration, or the amount of influence the projection of a node has on the embedding of the same node.`
So you would chose values similar to the other iteration weights.

Please read our docs (https://neo4j.com/docs/graph-data-science/current/machine-learning/node-embeddings/fastrp/#_iteration_weights)

**Comment by meg261995** [comment]
Yes, Thanks alot
