### ISSUE TITLE
bug: the centrality degree algorithm displays opposite results With reverse and natural orientations in Ne04J and Graph Data Science Playground (Neuler)

### ISSUE THREAD

**Issue by LyneEwandje** [neo4j/graph-data-science#228]
**Environnement**
-Neo4j Desktop 4.4.5
-Neuler-graph data Science 0.1.54
-GDSL 2.0.3

**Reproduction steps** 

- neo4J

1) insert graph 
CREATE
  (alice:User {name: 'Alice'}),
  (bridget:User {name: 'Bridget'}),
  (charles:User {name: 'Charles'}),
  (doug:User {name: 'Doug'}),
  (mark:User {name: 'Mark'}),
  (michael:User {name: 'Michael'}),

  (alice)-[:FOLLOWS {score: 1}]->(doug),
  (alice)-[:FOLLOWS {score: -2}]->(bridget),
  (alice)-[:FOLLOWS {score: 5}]->(charles),
  (mark)-[:FOLLOWS {score: 1.5}]->(doug),
  (mark)-[:FOLLOWS {score: 4.5}]->(michael),
  (bridget)-[:FOLLOWS {score: 1.5}]->(doug),
  (charles)-[:FOLLOWS {score: 2}]->(doug),
  (michael)-[:FOLLOWS {score: 1.5}]->(doug)

![image](https://user-images.githubusercontent.com/116086972/198527059-cb5a20a0-98cd-462b-9429-babf534f857f.png)

2. do the function reverse on the projection graph 

CALL gds.graph.project(
  'myGraph',
  'User',
  {
    FOLLOWS: {
      orientation: 'REVERSE',
      properties: ['score']
    }
  }
)

 3. visualise the results With the orientation Reverse in Ne04j

![image](https://user-images.githubusercontent.com/116086972/198528220-e871ae98-e13c-467a-8c66-849d8d5a75b8.png)

- Neuler

1. Select the database and configure 

![image](https://user-images.githubusercontent.com/116086972/198528715-f5b409cb-8160-48c4-8278-5c107ec9c9e9.png)

3. visualize the results With the orientation Reverse

![image](https://user-images.githubusercontent.com/116086972/198529228-d119dd75-4aeb-4ac3-a404-38860abab278.png)

**Comparison of results With the reverse and natural orientation in Neuler and Ne04J**

<img width="393" alt="neo" src="https://user-images.githubusercontent.com/116086972/198529583-6eda1c64-c148-47d6-a0f1-b96b37322926.PNG">

which gives us opposite results of the execution of the centrality degree algorithm in Ne04j and in Neuler

**Comment by FlorentinD** [comment]
Hello @LyneEwandje,
the problem lies in specifying the `REVERSE` orientation twice in the cypher queries.

What happens is, that first during graph projection the relationships are reversed.
Then when you call degree centrality with `REVERSE` orientation, you are reversing the projected relationships.
This results in computing the degree centrality of the reversed `REVERSE` relationships or in short the `NATURAL` orientation.

I would suggest to remove your orientation from the `degree` query if you have more algorithms you want to run your graph.

**Comment by LyneEwandje** [comment]
Hello @FlorentinD,

Thanks for your quick answer!!
Indeed I did the tests by removing the orientation of the degree request and by leaving only the definition of the projection graph and it works.  Thanks !
