### ISSUE TITLE
Neo4j Graph Data Science plugin not specified for Neo4j 4.4.15

### ISSUE THREAD

**Issue by pesc** [neo4j/graph-data-science#236]
Hi

Affects Neo4j Version: 4.4.15

https://graphdatascience.ninja/versions.json is missing the version entry for Neo4j 4.4.15 and so the fetching of the GDS plugin fails.

```
Fetching versions.json for Plugin 'graph-data-science' from https://graphdatascience.ninja/versions.json
Installing Plugin 'graph-data-science' from null to /var/lib/neo4j/plugins/graph-data-science.jar 
```

Greetings Pascal

**Comment by Mats-SX** [comment]
Hello @pesc and thank you for the report.

I have re-added the mapping for Neo4j 4.4.15 and 4.3.22, which mysteriously disappeared. We will investigate the source for losing these entries, which we added already on November 28.

Please, try again and apologies for the outage.

All the best
Mats
