### ISSUE TITLE
How does one search for a small subgraph within a huge database?

### ISSUE THREAD

**Issue by younis-ba** [neo4j/graph-data-science#246]
how can I search in subgraph in the neo4j database , is this feature available?

**Comment by Mats-SX** [comment]
@younis-ba What do you mean, precisely? Just searching for subgraphs is exactly what the Cypher query language does. Does that cover your use case?

For example, finding all the subgraphs of friends of friends who aren't friends:

```
MATCH (p:Person)-[:KNOWS]-(friend:Person)-[:KNOWS]-(friendOfFriend:Person)
WHERE NOT EXISTS { (p)-[:KNOWS]-(friendOfFriend) }
RETURN p, friend, friendOfFriend
```

**Comment by Mats-SX** [comment]
Closing this as inactive.
