### ISSUE TITLE
kMeans doesn't compute the silhouette nor the distance to centroid

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#248]
GDS version: 2.3.0
Neo4j version: 5.4.0
Operating system: Sandbox

Generate data:

```
UNWIND range(1,100) AS _
CREATE (:Node {vector:[rand(), rand(), rand()]});
```

Project the graph:

```
CALL gds.graph.project('test', 'Node', '*', {nodeProperties:['vector']})
```

Execute kmeans algo:

```
CALL gds.beta.kmeans.stats('test', {k:5, nodeProperty:'vector', computeSilhouette: true})
YIELD averageDistanceToCentroid, averageSilhouette
```
Results:

averageDistanceToCentroid | averageSilhouette
-- | --
0.0 | 0.0

**Comment by IoannisPanagiotas** [comment]
Hi @tomasonjo ,

Thank you for brining this to our attention. We've fixed the issue, and it will be available with Gds 2.3.2
