### ISSUE TITLE
Easy one.  Website Typo

### ISSUE THREAD

**Issue by john-james-ai** [neo4j/graph-data-science#249]
The description for [Neo4J Graph Data Science Certification ](https://graphacademy.neo4j.com/certification/) is as follows:

The [Neo4j Graph Data Science Certification](https://graphacademy.neo4j.com/courses/gds-certification/?ref=certification) tests on use of Neo4j Graph Data Science Library, workflow with the library, and common algorithms used in Graph Data Science. The following learning path should teach you everything you need to know to achieve **Neo4j Certified Professional creditation.**

The last sentence should be as follows:
 The following learning path should teach you everything you need to know to achieve the **Neo4j Graph Data Science Certification.**

**Comment by adam-cowley** [comment]
Thanks for the heads up!  I have updated this on the graphacademy website.
