### ISSUE TITLE
Drop all graphs from catalog

### ISSUE THREAD

**Issue by HashRocketSyntax** [neo4j/graph-data-science#25]
Is there a quick way to drop all named_graphs from the catalog?
```
CALL gds.graph.drop('*') YIELD graphName;
//
RETURN gds.graph.clear()
```
> https://neo4j.com/docs/graph-data-science/1.0/management-ops/graph-catalog-ops/#catalog-graph-drop
I am running a pipeline where I am creating many named graphs. However, the graphs live in the java memory, not my python notebook's memory, so when I restart my notebook kernel... the old graph catalog is still there.

I could fetch them all with `list()` and then pass that as a list arg into `drop()`, but there is definitely a more elegant way. 

Feel like devs would have already written this for clearing out their own catalogs when hacking on the catalog.

**Comment by HashRocketSyntax** [comment]
Here is how I am clearing my catalog at the moment:

```
from neomodel import db

unflat_catalog_all, meta = db.cypher_query("""
        CALL gds.graph.list()
        YIELD graphName, nodeCount, relationshipCount
        RETURN collect(graphName);
    """,
    {}
)

catalog_all = unflat_catalog_all[0][0]

for graphName in catalog_all:
    db.cypher_query("""
            CALL gds.graph.drop({graphName});
        """,
        {"graphName": graphName}
    )
```

**Comment by tomasonjo** [comment]
Why not use just a single cypher query?

```
CALL gds.graph.list() YIELD graphName
CALL gds.graph.drop(graphName);
```

**Comment by HashRocketSyntax** [comment]
@tomasonjo Cypher usually gets mad when I try do/ run multiple MATCH, CALL in a single query. This is the error I get when running your query. I also tried deviations of that using WITH and FOR EACH
```
CypherSyntaxError: Query cannot conclude with CALL (must be RETURN or an update clause) (line 3, column 9 (offset: 47))
"    CALL gds.graph.drop(graphName) YIELD graphName;"
     ^
```

**Comment by tomasonjo** [comment]
Well, you just have to return something...

```
CALL gds.graph.list() YIELD graphName
CALL gds.graph.drop(graphName) YIELD graphName as dropped
RETURN dropped
// or RETURN distinct 'done'
```
