### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException error when running gds.alpha.modularity.stats

### ISSUE THREAD

**Issue by mlnrt** [neo4j/graph-data-science#251]
**Describe the bug**
I am running community detection algorithms (Leiden, Modularity Optimization and Label Propagation) on an undirected graph projection. For each result I am computing the modularity score.

When computing the modularity score on the results of the Label Propagation algorithm  I get the following error:
{code: Neo.ClientError.Procedure.ProcedureCallFailed} {message: Failed to invoke procedure `gds.alpha.modularity.stats`: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 695 out of bounds for length 632}

**To Reproduce**
Operating system: (for example Windows 10)
GDS: 2.3.1
Python GDS
Neo4j: 5.4.0

- Get the GML file from [here](https://graph-data-science-modularity-stats-error.s3.eu-west-1.amazonaws.com/everything.gml) and put it in the Neo4j project import folder
- Create a database
- Import the GML file into the database `CALL apoc.import.graphml("all_members.gml", {readLabels: true})`
- The import procedures transforms the relationship weight to a string (why?) so cast it to a float `MATCH ()-[r:PARTNERED_WITH]->() SET r.expeditionCount = toFloat(r.expeditionCount)`
- Create the graph projection: `CALL gds.graph.project("members", ["NonSherpaNonTibetan", "Sherpa", "Tibetan"], {PARTNERED_WITH: {orientation: "UNDIRECTED", properties: "expeditionCount"}})`
- Run the label propagation algorithm with the default settings `CALL gds.labelPropagation.mutate("members", {mutateProperty: "labelCommunityId", relationshipWeightProperty: "expeditionCount"})`
- Compute the modularity score `CALL gds.alpha.modularity.stats("members", {communityProperty:"labelCommunityId", relationshipWeightProperty: "expeditionCount"}) YIELD nodeCount, relationshipCount, communityCount, modularity`

Interestingly, to write this bug report, I originally exported just the graph projection into a GML file, but when I do that and follow the above steps to reimport the GML file in a separate DB, then there is no issue. Also computing the modularity score on the result of other community detection algorithm, works fine.

**Expected behavior**
The gds.alpha.modularity.stats procedure returns the modularity score for the computed community

**Additional context**

"gdsVersion"	"2.3.1"
"gdsEdition"	"Unlicensed"
"neo4jVersion"	"5.4.0"
"minimumRequiredJavaVersion"	"11"
"unavailableCompatibility"	"Neo4j 4.4"
"unavailableCompatibility"	"Neo4j 5.1"
"unavailableCompatibility"	"Neo4j 5.2.0"
"unavailableCompatibility"	"Neo4j 5.3"
"availableCompatibility"	"Neo4j 5.4"
"unavailableCompatibility"	"Neo4j 5.5"
"unavailableCompatibility"	"Neo4j Settings 4.4"
"unavailableCompatibility"	"Neo4j Settings 5.1"
"unavailableCompatibility"	"Neo4j Settings 5.2.0"
"unavailableCompatibility"	"Neo4j Settings 5.3"
"availableCompatibility"	"Neo4j Settings 5.4"
"unavailableCompatibility"	"Neo4j Settings 5.5"
"featureSkipOrphanNodes"	false
"featureMaxArrayLengthShift"	28
"featurePropertyValueIndex"	false
"featureParallelPropertyValueIndex"	false
"featurePartitionedScan"	false
"featureBitIdMap"	true
"featureShardedIdMap"	false
"featureUncompressedAdjacencyList"	false
"featureReorderedAdjacencyList"	false
"buildDate"	"2023-02-14_09:05:59"
"buildJdk"	"11.0.15+10 (Eclipse Adoptium)"
"buildJavaVersion"	"11.0.15"
"buildHash"	"c1623b22e2e1a55c6dc37bf9e081414836f8d224"
"availableCPUs"	12
"physicalCPUs"	12
"availableHeapInBytes"	2684354560
"availableHeap"	"2560 MiB"
"heapFreeInBytes"	935056752
"heapFree"	"891 MiB"
"heapTotalInBytes"	2363490304
"heapTotal"	"2254 MiB"
"heapMaxInBytes"	2684354560
"heapMax"	"2560 MiB"
"offHeapUsedInBytes"	572721680
"offHeapUsed"	"546 MiB"
"offHeapTotalInBytes"	580517888
"offHeapTotal"	"553 MiB"
"poolCodeheapNonNmethodsUsedInBytes"	2807808
"poolCodeheapNonNmethodsUsed"	"2742 KiB"
"poolCodeheapNonNmethodsTotalInBytes"	3211264
"poolCodeheapNonNmethodsTotal"	"3136 KiB"
"poolMetaspaceUsedInBytes"	423475536
"poolMetaspaceUsed"	"403 MiB"
"poolMetaspaceTotalInBytes"	428802048
"poolMetaspaceTotal"	"408 MiB"
"poolCodeheapProfiledNmethodsUsedInBytes"	51154560
"poolCodeheapProfiledNmethodsUsed"	"48 MiB"
"poolCodeheapProfiledNmethodsTotalInBytes"	51183616
"poolCodeheapProfiledNmethodsTotal"	"48 MiB"
"poolCompressedClassSpaceUsedInBytes"	57835536
"poolCompressedClassSpaceUsed"	"55 MiB"
"poolCompressedClassSpaceTotalInBytes"	59834368
"poolCompressedClassSpaceTotal"	"57 MiB"
"poolG1EdenSpaceFreeInBytes"	536870912
"poolG1EdenSpaceFree"	"512 MiB"
"poolG1EdenSpaceTotalInBytes"	1432354816
"poolG1EdenSpaceTotal"	"1366 MiB"
"poolG1EdenSpaceMaxInBytes"	-1
"poolG1EdenSpaceMax"	"N/A"
"poolG1OldGenFreeInBytes"	396812288
"poolG1OldGenFree"	"378 MiB"
"poolG1OldGenTotalInBytes"	874512384
"poolG1OldGenTotal"	"834 MiB"
"poolG1OldGenMaxInBytes"	2684354560
"poolG1OldGenMax"	"2560 MiB"
"poolG1SurvivorSpaceFreeInBytes"	1373552
"poolG1SurvivorSpaceFree"	"1341 KiB"
"poolG1SurvivorSpaceTotalInBytes"	56623104
"poolG1SurvivorSpaceTotal"	"54 MiB"
"poolG1SurvivorSpaceMaxInBytes"	-1
"poolG1SurvivorSpaceMax"	"N/A"
"poolCodeheapNonProfiledNmethodsUsedInBytes"	37448576
"poolCodeheapNonProfiledNmethodsUsed"	"35 MiB"
"poolCodeheapNonProfiledNmethodsTotalInBytes"	37486592
"poolCodeheapNonProfiledNmethodsTotal"	"35 MiB"
"freePhysicalMemoryInBytes"	17074290688
"freePhysicalMemory"	"16283 MiB"
"committedVirtualMemoryInBytes"	3577798656
"committedVirtualMemory"	"3412 MiB"
"totalPhysicalMemoryInBytes"	34020347904
"totalPhysicalMemory"	"31 GiB"
"freeSwapSpaceInBytes"	44329644032
"freeSwapSpace"	"41 GiB"
"totalSwapSpaceInBytes"	68380086272
"totalSwapSpace"	"63 GiB"
"openFileDescriptors"	-1
"maxFileDescriptors"	-1
"vmName"	"OpenJDK 64-Bit Server VM"
"vmVersion"	"17.0.5+8-LTS"
"vmCompiler"	"HotSpot 64-Bit Tiered Compilers"
"containerized"	false
"dbms.security.procedures.unrestricted"	"apoc.*,gds.*"
"db.tx_state.memory_allocation"	"ON_HEAP"
"server.memory.pagecache.size"	2147483648
"server.memory.off_heap.max_size"	2147483648
"dbms.memory.transaction.total.max"	1879048192
"db.memory.transaction.total.max"	0
"db.memory.transaction.max"	0

**Comment by IoannisPanagiotas** [comment]
Hi @mlnrt ,

Thank you for bringing this issue into our attention.  It appears our 'gds.alpha.modularity' procedure has not been configured to work under arbitrary community input; rather it expects every input community value to  be smaller than the size of the graph. 

We will try to address this for the next minor release (2.3.2), which should be out this week or next week.

In the meantime I would suggest a minor tweak in your script which should take care of your issue.

Namely, you can replace 
`CALL gds.labelPropagation.mutate("members", {mutateProperty: "labelCommunityId", relationshipWeightProperty: "expeditionCount"})
`
with 
`  CALL gds.labelPropagation.mutate("members", {mutateProperty: "labelCommunityId", relationshipWeightProperty: "expeditionCount", **consecutiveIds: true** })`

Setting consecutiveIds to true will map the output of label propagation algorithm such that it respects the input requirements of modularity.

Let me know if that resolves your problem.

**Comment by mlnrt** [comment]
Hello @IoannisPanagiotas thank you for answering so quickly!
Yes setting `consecutiveIds: true` fix the problem.
Sorry I am pretty new to Neo4j. I did not had the error with other community algorithm but is this parameter recommended for other community detection algorithms?

FYI: it is public data but since you found the root cause of the problem I deleted the link to the data to reproduce the issue.

**Comment by IoannisPanagiotas** [comment]
Hello again, @mlnrt,

Glad to hear this has fixed your issue, until we can get something more stable in.

For the rest of our algorithms, this should not be a problem: their output is In the 0..nodeCount-1.
The only case where this might not be true is  if you specify the seedProperty  parameter(where applicable).  In this case,  the community detection algorithms start  with some predefined communities (which might change) and this might cause issues with the `gds.alpha.modularity` if their value is higher than nodeCount. 

This issue is mostly related to Label Propagation algorithm, perhaps it makes some sense from our side to reconsider it's output behaviour.

That being said,  I would like to close the issue from now, but feel free to ask again here or somewhere else if you come across any other issues or need help :)
