### ISSUE TITLE
GDS triangleCount, there is a bug when configuring `nodeLabels`

### ISSUE THREAD

**Issue by sybest1259** [neo4j/graph-data-science#259]
GDS version: 2.3
Neo4j version: 5.3.0
Operating system: Ubuntu 18.04

I ran the triangleCount algo as follow:
CALL gds.triangleCount.stream(
	'g2', 
  {
  	maxDegree: 10,
  	nodeLabels: ['person']
  }
)
YIELD nodeId, triangleCount
RETURN gds.util.asNode(nodeId).name AS name, triangleCount
ORDER BY triangleCount DESC

Then I got an error:
`Failed to invoke procedure gds.triangleCount.stream: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 16722829 out of bounds for length 15560`
I found that `16722829` is an id of node
Is there any bugs in traingleCount algo?

**Comment by FlorentinD** [comment]
This is definitely a bug in the algorithm. The user should never see a `AIOOB` exception.

Thanks for reporting.
Would you be able to provide your dataset as well?

**Comment by FlorentinD** [comment]
If not, providing the stacktrace from the logs would be also helpful.

**Comment by sybest1259** [comment]
Thks @FlorentinD,
I'm sorry,the dataset is of privacy,I ran traingleCount algo  on the web side as follow:
![截屏2023-03-24 08 22 29](https://user-images.githubusercontent.com/41052224/227393428-fa0810e1-5d80-4bfe-92dc-90cceda067c7.png)

**Comment by vnickolov** [comment]
@sybest1259 would it be possible to share the `debug.log` and `neo4j.log` from the Neo4j logs directory, they should contain more details about the error.

**Comment by vnickolov** [comment]
Closing this since we can't reproduce it and it has been inactive for more than a month.
