### ISSUE TITLE
Error handling: Cosine similarity vector with null value

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#26]
If the vector for the similarity calculation contains a null, we get a null pointer error. Maybe we could inform the user that the vector should not contain any nulls.

Create graph:

`CREATE (:User), (:User)`

Run the algo:

```
MATCH (u:User)
WITH {item:id(u), weights: [1, null]} as userData
With collect(userData) AS data
CALL gds.alpha.similarity.cosine.stream({nodeProjection: '*', relationshipProjection: '*', data: data})
YIELD item1, item2, count1, count2, similarity
RETURN item1, item2, similarity
```

returns an error:

> Failed to invoke procedure `gds.alpha.similarity.cosine.stream`: Caused by: java.lang.NullPointerException

**Comment by tomasonjo** [comment]
Probably related to this error is when the vectors are not the same size:

Example algorithm with different length of weights

```
WITH [{item:1, weights: [1, 2, 3]}, {item:2, weights: [1, 2]}] as data
CALL gds.alpha.similarity.cosine.stream({nodeProjection: '*', relationshipProjection: '*', data: data})
YIELD item1, item2, count1, count2, similarity
RETURN item1, item2, similarity
```

Also returns the null pointer example

**Comment by FlorentinD** [comment]
The first error we could reproduce and fix (corrected the handling of `null` values, but the second query succeeds when testing.

Could you share the used versions, so I can try to reproduce your second query? @tomasonjo

**Comment by tomasonjo** [comment]
I tried it on v1.1 and it works fine. The thing is that mathematically ([I think](https://www.quora.com/Linear-Algebra-How-do-I-calculate-cosine-similarity-with-vectors-of-different-lengths)), you can't compare the cosine similarity of two vectors of different sizes. What it looks like we do, which is fine, is we cut off the larger vector to the length of the smaller one as the example:

 ```
WITH [{item:1, weights: [1, 2, 3]}, {item:2, weights: [1, 2]}] as data
CALL gds.alpha.similarity.cosine.stream({nodeProjection: '*', relationshipProjection: '*', data: data})
YIELD item1, item2, count1, count2, similarity
RETURN item1, item2, similarity
```

Returns a similarity of 1. So no need to fix this, but definitely include it the documentation. Or maybe even add a separate parameter that allows various length vectors or not. What do you think @FlorentinD ? @Mats-SX

**Comment by FlorentinD** [comment]
I agree this should be documented. 
Personally, I wouldnt add a parameter as I can't see the mathematical meaning in allowing this.

**Comment by Mats-SX** [comment]
Seems like a good thing to cover in the docs yes. If this was up for promotion to a higher tier, I would call into question the default behaviour and throw errors if the lengths do not match, potentially with a configuration parameter that could specify a strategy to handle this case, such as cutting of the longer one, prepending or appending the shorter one with `null` etc.

Since this will remain in the `alpha` tier for now, just documenting the current default and unconfigurable strategy seems like the best option.
