### ISSUE TITLE
write-services with version 2.3.2 not found in maven central repository.

### ISSUE THREAD

**Issue by Mr-Z2001** [neo4j/graph-data-science#267]
**Describe the bug**
 In README.adoc, the artifactID of the last dependency is "write-services" with version 2.3.2. But I looked up in the maven repo, I found the latest version of it is 2.0. I found another one called "open-write-services" which has a version of 2.3.2. I think there is a typo in README. Thank you!

**Comment by vnickolov** [comment]
Thank you @Mr-Z2001 you are absolutely correct,

```
<!-- Required by the write execution modes, this artifact is responsible for providing the various exporters -->
<dependency>
  <groupId>org.neo4j.gds</groupId>
  <artifactId>write-services</artifactId>
  <version>2.3.2</version>
</dependency>
```

should be 

```
<!-- Required by the write execution modes, this artifact is responsible for providing the various exporters -->
<dependency>
  <groupId>org.neo4j.gds</groupId>
  <artifactId>open-write-services</artifactId>
  <version>2.3.2</version>
</dependency>
```

we are going to correct this, thanks for reporting it 🙇

**Comment by vnickolov** [comment]
@Mr-Z2001 the README has been updated, I will go ahead and close this issue.
