### ISSUE TITLE
Mutated properties writeback default value 0 is confusing

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#27]
I have noticed that we use 0 as a default value for writing back mutated properties. This does not seem the best idea as it might be very confusing when dealing with community detection algorithms.

Create graph:

`CREATE (:Node)-[:LINK]->(:Node), (:Label), (:Label)`

Load the graph:

`CALL gds.graph.create('test',['Node','Label'],'*')`

Stream only using label Node results for reference:

`CALL gds.louvain.stream('test',{nodeLabels:['Node']})`

results:

nodeId | communityId | intermediateCommunityIds
-- | -- | --
1492 | 1 | null
1493 | 1 | null

Run the mutated version of the algos:

`CALL gds.louvain.mutate('test',{nodeLabels:['Node'],mutateProperty:'mutate'})`

and writeback results:

`CALL gds.graph.writeNodeProperties('test',['mutate'])`

If we inspect results:

`MATCH (n) return id(n), n.mutate`

we get:

id(n) | n.mutate
-- | --
1492 | 1
1493 | 1
1494 | 0
1495 | 0

Given the results you might think that this means that the other two nodes are in the same community... which they are not as there is no relationship between them. So either a big warning should be placed that the community 0 actually does not exist, it's just a default value. My opinion is that this is not enough and either change the default value to -1 to make it more obvious or just change it to null, which would be the best solution IMO

**Comment by Mats-SX** [comment]
I would agree that `null` or `NaN` would be the appropriate result. For technical reasons it might not be feasible to use `null` (ie, no value whatsoever for the property) but `NaN` is effectively the same (and we try to treat it the same within the library).

To be clear: the algorithm will write some value to `mutateProperty` for all nodes that are input to the algorithm. Due to the `nodeLabels` filter some nodes in `'test'` are filtered out, and as such they should not get any valid value for `mutateProperty`, because they were not processed. This should apply regardless of whether they have relationships or not; if they're filtered out they're filtered out and should not get a property.

**Comment by tomasonjo** [comment]
I agree, my point was to show an example of why the default value 0 might not be the best option, given that a user might mistake it for a valid community id, and that is why I omitted the relationship.

On the other hand, if we could get plain cypher to treat NaN as null, that would be also awesome! :)
In the 1.1 preview version it stored back NaN values, which show up as `null` in Neo4j Browser and that can be confusing to say the least as `WHERE x IS NOT NULL` will not work as a filter

**Comment by Mats-SX** [comment]
I think we've made some measures on not writing back `NaN` values anymore, so hopefully that will help. For making Cypher treat `NaN` and `null` the same: this is a more difficult topic and goes beyond the scope of this library. If you're interested, perhaps raise an issue at https://github.com/opencypher/openCypher, or read this bit on what Cypher thinks about `null`: https://github.com/opencypher/openCypher/blob/master/cip/1.accepted/CIP2016-06-14-Define-comparability-and-equality-as-well-as-orderability-and-equivalence.adoc#311-the-meaning-of-null

**Comment by tomasonjo** [comment]
Yea I know cypher is out of the scope of this project, just wishful thinking :)

**Comment by DarthMax** [comment]
Fixed in 1.1.1
