### ISSUE TITLE
How to calculate jaccard similarity score when multi-relationships

### ISSUE THREAD

**Issue by lin17182210** [neo4j/graph-data-science#284]
In gds docs:
<img width="647" alt="image" src="https://github.com/neo4j/neo4j/assets/39157511/4f701d3d-83d2-49e0-9058-ab6f65172812">
This is my gds graph project:
![image](https://github.com/neo4j/neo4j/assets/39157511/bd6d3834-5008-43ea-bb3a-74d853b3e004)
then i call nodeSimilarity get this:
```
call gds.nodeSimilarity.stream('test', {topK:5})
yield node1, node2, similarity
return node1, node2, similarity
order by similarity, node1, node2;
```
<img width="1155" alt="image" src="https://github.com/neo4j/neo4j/assets/39157511/ad8b1a10-0a9b-49fe-b2e5-73d74b0e1c14">
the following two pictures are the query results of 12271 and 29419: 

![image](https://github.com/neo4j/neo4j/assets/39157511/a8e00d52-dbc5-4efb-aa13-d26cd9d2a924)

![image](https://github.com/neo4j/neo4j/assets/39157511/e3120cba-9ca3-4445-adad-e0e500ba0a86)
**they only have the same content in the red box, 
So why the final similarity is 0.2?**
At the same time, I also tested that only one relationship is used when creating a project, the result is consistent with the formula in the gds document.
Thank you in advanced for any helps.

**Comment by IoannisPanagiotas** [comment]
Hi @lin17182210,

Based on the data you are sharing, the results seem normal to me.
The first node  has a degree of 4   so |A|=4
The second node has a degree of 2, so |B|=2, and  |A /\ B| =1 , the  node in the red box.

So Jaccard(A,B) =.   1/(4 + 2 -1) = 1/5 = 0.2 as shown in the result.

Note that node Similarity does only looks at the neighbors of a node,  not the relationship types.

Can you please let us how you were expecting the algorithm to behave? 

Best regards,
Ioannis.

**Comment by lin17182210** [comment]
Thank you very much. I understand. 
I fell into a misunderstanding of calculation before, which led to the inconsistency with the expected result.
I am going to use the similarity of nodes for supplementary expansion of the search result set.
Before that, our expansion method completely used query statements, because I have not been in contact with neo4j for a long time, do you have any other suggestions on search recommendations?
thanks again

**Comment by IoannisPanagiotas** [comment]
Hello again @lin17182210,

Nice, happy to see nothing is wrong after all :) 

If you want exact similarity  search based on common neighborhoods between nodes, I cannot think anything besides `gds.nodeSimilarity`.

If you can settle for non-exact, one potential idea is generating [embeddings](https://neo4j.com/docs/graph-data-science/current/machine-learning/node-embeddings/)  and using these embeddings as the input node property  on [kNN](https://neo4j.com/docs/graph-data-science/current/algorithms/knn/). 

But this approach does  not gurantee you that the top-k pairs you find are indeed the closest in similarity  or that the computed similarities are 100% accurate.

 But  as a compromise it might be faster than nodeSimilarity and quality-wise hopefully not that bad.

Best regards and good luck in your project,
Ioannis.
