### ISSUE TITLE
gds.alpha.hits.write returns error related to conversion default value of partitioning (AUTO) to AnyValue 

### ISSUE THREAD

**Issue by martynscn** [neo4j/graph-data-science#285]
**Describe the bug**
gds.alpha.hits.write returns ClientError: [Procedure.ProcedureCallFailed] Failed to invoke procedure `gds.alpha.hits.write`: Caused by: java.lang.IllegalArgumentException: Cannot convert AUTO of type org.neo4j.gds.beta.pregel.Partitioning to AnyValue, classloader=jdk.internal.loader.ClassLoaders$AppClassLoader@5ffd2b27, classloader-name=app

**To Reproduce**
CALL gds.alpha.hits.mutate() or CALL gds.alpha.hits.write()

GDS version: 2.4.4
Neo4j version: 5.11.0 ENTERPRISE
Operating system: Ubuntu 22.04.1 LTS

- [ ] Project the graph. node count ~400000, relationship count ~1200000, 
- [ ] Run CALL gds.alpha.hits.write() or CALL gds.alpha.hits.mutate()

**Expected behavior**
Query completes successfully without an error

**Current behavior**
The following error is returned 
ClientError: [Procedure.ProcedureCallFailed] Failed to invoke procedure `gds.alpha.hits.write`: Caused by: java.lang.IllegalArgumentException: Cannot convert AUTO of type org.neo4j.gds.beta.pregel.Partitioning to AnyValue, classloader=jdk.internal.loader.ClassLoaders$AppClassLoader@5ffd2b27, classloader-name=app

**Additional context**
Manually changing the value of **partitioning** in `gds.alpha.hits.write` any of to 'AUTO', 'RANGE' and 'DEGREE' returns the following error

[Procedure.ProcedureCallFailed] Failed to invoke procedure `gds.alpha.hits.write`: Caused by: java.lang.IllegalArgumentException: The value of `partitioning` must be of type `Partitioning` but was `String`.

**Comment by vnickolov** [comment]
Hello @martynscn, I can confirm that I managed to reproduce this issue, will let you know when a fix has been released.

**Comment by vnickolov** [comment]
Hello @martynscn, GDS 2.4.6 has been released and it contains the fix, can you please test it and close the issue.

**Comment by JohT** [comment]
Hi @vnickolov and @martynscn,
i'm curious if there would also be a new 2.5.0 preview version (tag) including this (and other) fixes.

**Comment by martynscn** [comment]
Hi @vnickolov and @JohT, I just tested this in Neo4j version =  5.11.0 and GDS version = 2.5.6 with the command **CALL gds.hits.write()** and it now works well. Thank you for the fix
