### ISSUE TITLE
Always failed with java.util.NoSuchElementException: Cannot find graph with name

### ISSUE THREAD

**Issue by IPL** [neo4j/graph-data-science#29]
No matter what gds algorithm that I tried, I always got the NoSuchElementException, because the graph name did not exist. Then I cloned the code of this repo, added more log, and then put it into the plugin folder. Based on the extra info that I recorded, I can see that graphsByName(in GraphStoreCatalog.java) is empty. Is there any problem of my usage? Thanks in advance.

**Comment by vnickolov** [comment]
Hi @IPL

Thank you for reaching out, have you created the graph first?

You should use the `gds.graph.create` procedure and then you can run the algorithm with the name you have given to the graph during creation.

Please see the [documentation on Graph Catalog Operations](https://neo4j.com/docs/graph-data-science/current/management-ops/graph-catalog-ops/)

**Comment by IPL** [comment]
My bad. I didn't notice this pre request. Thanks.

**Comment by vnickolov** [comment]
No problem at all, please reach out if you have any questions.
