### ISSUE TITLE
Bug: Weighted shortest path seems not to work correctly

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#3]
Basically, I think that `gds.alpha.shortestPath.stream` does not work properly with `relationshipWeightProperty`. It does not find the shortest weighted path, but it finds the shortest unweighted path and calculates the weight for it.

import data:

```
WITH "https://github.com/neo4j-graph-analytics/book/raw/master/data/transport-nodes.csv"
AS uri
LOAD CSV WITH HEADERS FROM uri  AS row
MERGE (place:Place {id:row.id})
SET place.latitude = toFloat(row.latitude),
    place.longitude = toFloat(row.latitude),
    place.population = toInteger(row.population)
```

and rels:

```
WITH "https://github.com/neo4j-graph-analytics/book/raw/master/data/transport-relationships.csv"
AS uri
LOAD CSV WITH HEADERS FROM uri AS row
MATCH (origin:Place {id: row.src})
MATCH (destination:Place {id: row.dst})
MERGE (origin)-[:EROAD {distance: toInteger(row.cost)}]->(destination)
```

Execute the algorithm with:

```
MATCH (source:Place {id: "Amsterdam"}),
      (destination:Place {id: "London"})
CALL gds.alpha.shortestPath.stream({nodeProjection:'Place',relationshipProjection: {EROAD: {type:'EROAD', projection:'Natural', properties:'distance'}},startNode:source, endNode: destination, relationshipWeightProperty: 'distance'})
YIELD nodeId, cost
RETURN gds.util.asNode(nodeId).id AS place, cost
```

returns :

place | cost
-- | --
"Amsterdam" | 0.0
"Immingham" | 369.0
"Doncaster" | 443.0
"London" | 720.0

When in reality the shortest weighted path should be:

place | cost
-- | --
"Amsterdam" | 0.0
"Den Haag" | 59.0
"Hoek van Holland" | 86.0
"Felixstowe" | 293.0
"Ipswich" | 315.0
"Colchester" | 347.0
"London" | 453.0

**Comment by vnickolov** [comment]
@tomasonjo we have investigated this issue, the graph is directed and there is no relationship from   
"Hoek van Holland" -> "Felixstowe" (the relationship is the other way around).
If you use `projection: 'UNDIRECTED'` the result is as expected.
`{EROAD: {type:'EROAD', projection:'UNDIRECTED', properties:'distance'}}`

**Comment by tomasonjo** [comment]
You are absolutely correct, sorry I totally forgot that the old algos use undirected projection as the default for path-finding.

**Comment by vnickolov** [comment]
No problem at all :-)
