### ISSUE TITLE
GraphDataScience constructor version check failed on 'neo4j' database

### ISSUE THREAD

**Issue by Mintactus** [neo4j/graph-data-science#300]
When using the GDS python client

The GDS GraphDataScience constructor is complaining about not finding the database 'neo4j'
It seems there is a version check gds.version() when trying to create a gds object, this check is ignoring the database parameter of the constructor and make everything crash.

The database I'm trying to connect to is provided and it's not the neo4j database.
But even if it's not provided, the default database to check the version of GDS should always be system, not neo4j, who will mostly not exists in many production environments.

GraphDataScience(neo4j_credentials['uri'], auth=neo4j_credentials['auth'], database=neo4j_credentials['database'])

**Comment by Mats-SX** [comment]
Hi @Mintactus and thanks for raising this issue. This seems like an obvious bug that we should fix.

**Comment by adamnsch** [comment]
We created a fix for this issue now: https://github.com/neo4j/graph-data-science-client/pull/607 It will hopefully be merged soon

**Comment by Mintactus** [comment]
Excellent, thank you

**Comment by adamnsch** [comment]
The PR is merged now, and it will be included in the next release of `graphdatascience`, so closing this now. Thanks again @Mintactus for reporting this
