### ISSUE TITLE
Compatibility with Neo4j 5.20.0

### ISSUE THREAD

**Issue by danielgen** [neo4j/graph-data-science#310]
**Describe the bug**
Tried to use gds plugin in neo4j 5.20, server failed to start
Could not find it here: https://neo4j.com/docs/graph-data-science/current/installation/supported-neo4j-versions/
I know it came out not long ago 

**To Reproduce**
installing gds plugin in neo4j 5.20

GDS version: 2.6.6
Neo4j version: 5.20.0
Operating system: Mac OS Sonoma

**Additional context**
```
org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:269) ~[neo4j-5.20.0.jar:5.20.0]
	... 5 more
Caused by: org.neo4j.kernel.extension.FailedToBuildExtensionException: 
Failed to build kernel extension Extension:GraphDataScienceExtension[gds.closed] 
because it is compiled with a reference to a class, method, or field, that is not in the class path: 
'GDS 2.6.6 is not compatible with Neo4j version: dev'. 
The most common cause of this problem, is that Neo4j has been upgraded without also upgrading all installed extensions, 
such as APOC. Make sure that all of your extensions are build against your specific version of Neo4j.
```

For now managed to work by downloading neo4j 5.19.0 and gds 2.6.6 works with it

**Comment by Mats-SX** [comment]
Hello @danielgen 

We're about to release GDS plugin version `2.6.7` which will be compatible with Neo4j DBMS 5.20.0. If you download the Neo4j DBMS you will find this version bundled in the `products` directory. We will shortly update the usual direct download locations for GDS plugin as well.

All the best
Mats

**Comment by Mats-SX** [comment]
@danielgen You can use this download link to get GDS version `2.6.7` which is compatible with Neo4j DBMS `5.20.0`: https://graphdatascience.ninja/neo4j-graph-data-science-2.6.7.jar

We will update our website at neo4j.com with download links in the usual spots shortly.

I hope this solves your needs.

All the best
Mats
