### ISSUE TITLE
GDS.graph.export allow replace database

### ISSUE THREAD

**Issue by Mintactus** [neo4j/graph-data-science#313]
The config "replace = False" is missing from gds.graph.export
You can set it to true so it replaces any existing database, short and sweet 

That would create a much more sweet workflow for testing purposes

**Comment by s1ck** [comment]
Sorry for the late reply. This can easily achieved by using database management commands. In your example, you'd need to run `DROP DATABASE <your-db> IF EXISTS DESTROY DATA`. See [docs](https://neo4j.com/docs/operations-manual/current/database-administration/standard-databases/delete-databases/) for detail.
