### ISSUE TITLE
Open GDS v2.7.0+68 ClassNotFoundException org.neo4j.gds.shaded.com.github.benmanes.caffeine.cache.Ticker

### ISSUE THREAD

**Issue by JohT** [neo4j/graph-data-science#316]
### Describe the bug

I get the following error message when trying to create a Graph Projection with an [Open GDS package of the newest (experimental) tag v2.7.0+68](https://github.com/JohT/open-graph-data-science-packaging/releases/tag/v2.7.0%2B68):

```
Dependencies_3_Create_Projection.cypher: {
  "code": "Neo.ClientError.Procedure.ProcedureCallFailed",
  "message": "Failed to invoke procedure `gds.graph.project`: Caused by: java.lang.ClassNotFoundException: org.neo4j.gds.shaded.com.github.benmanes.caffeine.cache.Ticker"
}
```

Here is the corresponding Cypher statement:

```cypher
CALL gds.graph.project('artifact-centrality', 'Artifact', 'DEPENDS_ON', {
    relationshipProperties: ['weight'],
    nodeProperties: ['incomingDependencies', 'outgoingDependencies']
}) YIELD graphName, nodeCount, relationshipCount
RETURN graphName, nodeCount, relationshipCount
```

With [Open GDS 2.7.0-alpha03](https://github.com/JohT/open-graph-data-science-packaging/releases/tag/v2.7.0-alpha03) everything works fine.

### To Reproduce

- **GDS version:** [2.7.0+68](https://github.com/neo4j/graph-data-science/releases/tag/2.7.0%2B68)
- **Neo4j version:** 5.16.0 (community edition)
- **Java:** OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) 
- **Operating system:** ubuntu-22.04 (in GitHub Action)

#### Steps to reproduce the behavior

- Clone https://github.com/JohT/code-graph-analysis-pipeline.git
- Switch to branch `renovate/joht-open-graph-data-science-packaging-2.x`
- Open a terminal
- Set the following environment variable to whatever value you like: `export NEO4J_INITIAL_PASSWORD=whatever_you_like`
- Check if you are using Java 17 with `java -version`
- Run `./scripts/examples/analyzeReactRouter.sh 6.23.0`

#### Alternative steps to reproduce the behavior

- Use the prebuilt [Open GDS package of the newest experimental tag v2.7.0+68](https://github.com/JohT/open-graph-data-science-packaging/releases/tag/v2.7.0%2B68) or build it your own by checking out the tag and running the following command:
  ```
  ./gradlew -Dorg.gradle.jvmargs=-Xmx2g" -Pneo4jVersion=5.16.0 -- :open-packaging:shadowCopy
  ```
- Use it as a plugin for Neo4J
- Create a Projection using `CALL gds.graph.project`

### Expected behavior

Open GDS packaging should contain all libraries needed. I presume that it would be beneficial to define all dependencies in Gradle when they are imported somewhere in the repository directly. 
[Open GDS 2.7.0-alpha03](https://github.com/JohT/open-graph-data-science-packaging/releases/tag/v2.7.0-alpha03) as a reference works fine.

### Additional context

With commit [Use caches instead of hash maps (df4ebed)](https://github.com/neo4j/graph-data-science/commit/df4ebed6ac11fe7125908fe7c835ad58ea82bed8) the package `com.github.benmanes.caffeine.cache` had been added to [EphemeralResultStore.java](https://github.com/neo4j/graph-data-science/blob/c3e3d9e63b62fb85b8d64470fb89855da7a81043/core/src/main/java/org/neo4j/gds/api/EphemeralResultStore.java). I couldn't find that library as a direct dependency in any Gradle configuration (see https://github.com/ben-manes/caffeine?tab=readme-ov-file#download). I guess it needs to be configured somewhere to be able to be picked up by [open-packaging](https://github.com/neo4j/graph-data-science/blob/6d932685128e3744bbb06c6964933142c3f2cae2/open-packaging/build.gradle). I guess this issue would also happen with tag [2.7.0+65](https://github.com/neo4j/graph-data-science/releases/tag/2.7.0%2B65) since it also contains the mentioned changes.

**Comment by vnickolov** [comment]
Hi @JohT,

Thank you for reporting this!
The `+XYZ` suffix is used for GDS for internal testing and should not be used as user deployment..
Please use the stable `2.6.x` release of the library or the `-alphaXY` if you absolutely must have the latest GDS.

I hope this helps.
Kind Regards,
Ves

**Comment by JohT** [comment]
Hi @vnickolov, I'm aware of that. Nonetheless do I want to report that as early as possible so that there is more time to resolve it. Additionally, it is specific to the Open GDS package, not the "normal" package with Neo4j proprietary code.

**Comment by vnickolov** [comment]
Thank you @JohT, 

We will discuss this with the team.

**Comment by JohT** [comment]
Thank you too @vnickolov.

**Comment by Mats-SX** [comment]
@JohT We will stop syncing these tags. They do not indicate OpenGDS release commits, but are used for Neo4j-internal purposes.

We will look into the reported issue with OpenGDS however.

**Comment by JohT** [comment]
Hey @Mats-SX, thanks very much for your effort. 

Don't worry too much about those extra tags. I'm absolutely aware that they shouldn't be used, that they are ever more experimental than alpha and beta tags and in fact I even needed to [loosen Renovate versioning](https://github.com/JohT/code-graph-analysis-pipeline/commit/e3e52dad31ead2465c3861078f88ba7362ac2186) to get them. So this is more on me hacking my way into the newest things fully knowing that this is not stable. I'm just playing around with it. I'm pretty sure no one else would do that especially not for production code. 

So if those tags help you to be more efficient in any way then by no means leave them as is. If, on the other hand, you don't create them any more I'm also completely fine with that.

>We will look into the reported issue with OpenGDS however.
Great. 👍 Thank you.

**Comment by knutwalker** [comment]
@JohT we merged [a commit](https://github.com/neo4j/graph-data-science/commit/5c178e616963acb3cfb4cd4c4a640e2b35e41fd8) yesterday that adds the missing dependency, then OpenGDS build should now work again on the master branch.
