### ISSUE TITLE
Betweenness Centrality - Shortest path on higher relationship weight values

### ISSUE THREAD

**Issue by Mintactus** [neo4j/graph-data-science#318]
Hi

I have a markov chain model representing marketing channels ( nodes ) with the numer of users moving ( relationships weight ) between them. In this context, the most efficient path is the path who has the most users. Betweenness Centrality would be an excellent algo but it's definition of shortest path rely only on the lower relationship weight.

I tried to naivly use the reverse value of each relationship weight but it doesn't work since it breaks the "balance" in the graph.
You can see it in this simple example that if you reverse 2 and 4 who becomes 1/2 and 1/4 the "balance" is broken since paths that were equivalent before are no longuer.

The cost of the paths
A -> B -> C  4
A -> C  4

Becomes
A -> B -> C  1
A -> C  1/4

So the betweeness centrality of B who was 0.5 becomes 0.

I don't expect a technical answer but, maybe a work around suggestion...which makes this feature request not really one in that case but I did't know who to put it. I don't expect to have a feature modifying the core behavior of the underlying dikstra algo behind the betweeness centrality, but I think presenting this use case my trigger some other features ideas maybe.

![abc](https://github.com/neo4j/graph-data-science/assets/30415501/7a8d08eb-7b95-4f1a-9eed-f6a6733a0555)

**Comment by IoannisPanagiotas** [comment]
Hi @Mintactus ,

Unfortunately, there is not much I could think of to help with your situation. Finding heaviest paths is notoriously more complicated than shortest paths. Indeed, in GDS we do support it only for the special case of [directed-acyclic-graphs (dags)](https://neo4j.com/docs/graph-data-science/current/algorithms/dag/longest-path/), where the graph structure allows to compute them exactly.

The reversal trick you have mentioned can work in some situations  but not always as you have figured out yourself. Perhaps it can be fine for approximation purposes, but cannot tell for certain. I am not aware of other such techniques you could try, probably they are very data specific.

I am sorry I could not provide more insightful input, but please let me know if have any other questions.
I would suggest perhaps checking in the [community forums](https://community.neo4j.com/c/neo4j-graph-platform/graph-algorithms/73).  Maybe another user  faced something similar in the past and can provide his working solution.

Best regards,
Ioannis.

**Comment by Mintactus** [comment]
Thanks for the answer, at least now i know that i'm not crazy to find it
difficult to solve
