### ISSUE TITLE
Documentation for cypher projection multi labels node statement

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#32]
When we are demonstrating how to project many node labels with cypher projection we use:

`MATCH (n) WHERE n:Author OR n:Article OR n:Book RETURN id(n) AS id, labels(n) AS labels`

As I guess many users will copy this query, maybe we should give them the optimized version as this query does AllNodesScan followed by a filter, which is not really optimized. The optimized version would be using the `UNION`:

```
MATCH (n:Author) RETURN id(n) as id
UNION
MATCH (n:Article) RETURN id(n) as id
...
```

I can prepare a PR if you agree.

**Comment by Mats-SX** [comment]
Hey @tomasonjo, yes I think you're correct! And I also think using this model is much more in line with the general way one would think about the Cypher projections, seeing as it is quite visible that the multiple queries correspond to multiple node labels, and that each of them could also be used singularly.

Like a progression where you just use one label first:

```
CALL gds.graph.create.cypher('g', 
  'MATCH (n:Author) RETURN id(n), labels(n) AS labels',
  ...
)
```

and then two

```
CALL gds.graph.create.cypher('g', 
  'MATCH (n:Author) RETURN id(n), labels(n) AS labels
   UNION
   MATCH (n:Article) RETURN id(n), labels(n) AS labels',
  ...
)
```

and into any amount.

If you would like to issue a PR we'd be very happy to review it!

**Comment by Mats-SX** [comment]
@tomasonjo You know what, I just checked on Neo4j `4.0.3` with `EXPLAIN` and it actually uses label scans and a `UNION` operator when faced with a disjunctive predicate such as the one we currently have in our docs, so in fact it may not be suboptimal to use the disjunction (`OR` predicate) after all. (I'm quite sure this hasn't always been the case, however.)

That being said, perhaps using the `UNION` syntax could still be an improvement, just for understandability. Without the performance aspect, the cost of the extra verbosity is higher, I suppose. What do you think?

**Comment by tomasonjo** [comment]
If the performance is the same, then I think the `OR` predicate is fine as the statement is more compact and quite clear anyhow.
