### ISSUE TITLE
Explanation needed for the GraphSAGE relationshipWeightProperty

### ISSUE THREAD

**Issue by pascalwhoop** [neo4j/graph-data-science#321]
**Describe the bug**
Not so much a bug but unclear how the `relationshipWeightProperty` is considered in GraphSage.
Someone else asked a similar question before:
https://github.com/neo4j/graph-data-science/issues/141
We dug into the code here but all we could find was the `negativeBatch` method leveraging the `WeightedUniformSampler` which in turn was referenced above. 

Basically the question we have is: If we give 10% of the edges a weight of 0, do these edges essentially not get considered in the random walks & thus the same result as if we had removed them from the Graph alltogether? 

@lvijnck FYI

**Comment by brs96** [comment]
Hi @pascalwhoop and @lvijnck,

If the degrees of the nodes are high and `sampleSize` is small, then setting 10% of edges with weight = 0 and removing them are the same.

However, if a node has few neighbours, and `sampleSize` (num. neighbours to sample for each node) is relatively high, than even if the edges have weight 0, they will be sampled. They will be given a very low priority according to https://github.com/neo4j/graph-data-science/blob/master/ml/ml-core/src/main/java/org/neo4j/gds/ml/core/samplers/WeightedUniformSampler.java#L75.
However if you have the edges removed, there will be potentially fewer sampled neighbours than `sampleSize`.

Thanks,
Brian

**Comment by brs96** [comment]
And they edge weights are used in aggregation as well, since the local neighbourhoods (subgraphs) are constructed with the relationshipProperty. https://github.com/neo4j/graph-data-science/blob/master/algo/src/main/java/org/neo4j/gds/embeddings/graphsage/GraphSageHelper.java#L102

**Comment by pascalwhoop** [comment]
Can you elaborate on the weight that should be given? The `1/weight` suggests that a large number == low probability of selection, but that is counterintuitive to what I'd expect a weight to be used. Just giving feedback here, there's hardly any stackoverflow/other posts online about this lib+parameter so it's hard to see examples

**Comment by brs96** [comment]
Sure, a Java caveat is `random.nextDouble()` gives a double in `[0, 1)`. Therefore the larger the weight, the smaller the exponent (`1/weight`) and hence the larger the priority (since the base is in `[0, 1)`)...

Thanks for pointing this out. Hopefully the discussions in this thread will be generally useful for the others too.

**Comment by pascalwhoop** [comment]
Agreed, the beauty of open source :) everyone learns from each other. 

So just to reiterate, the way it works is
- a weight of 0 gets a tiny number added to it so we don't divide by 0
- if there's only 1 edge, that means the edge doesn't actually "drop out" but gets chosen always, because there's just that edge to choose from
- if there are 10k edges, it'll statistically never be chosen

So am I correct in the assumption that the algorithm works statistically almost perfectly except with the edge case of a weight == 0 because we adjust it slightly above 0 and thus the sampling probability is always weight+EPSILON (where epsilon is e.g. 1e^-10)

idk if we are the only ones doing weight = 0 but it could be worth mentioning in the docs. 

Btw we're only doing this because the https://neo4j.com/docs/graph-data-science/current/management-ops/graph-creation/graph-project/ projection doesn't let you filter based on labels and we only discovered the subsequent filter step https://neo4j.com/docs/graph-data-science/current/management-ops/graph-creation/graph-filter/ later.

**Comment by brs96** [comment]
Yes that's right.
Purely filtering on node labels should be doable in native projection. More complex filtering can be done with cypher projection as well. It would be interesting to know what exact type of filtering aren't supported by the existing projections.
Will close this thread and filtering can be discussed in a separate one if needed.
