### ISSUE TITLE
Num of layers as a parameter to tune for GraphSAGE

### ISSUE THREAD

**Issue by piotrkan** [neo4j/graph-data-science#324]
**Is your feature request related to a problem? Please describe.**
I am trying to reproduce a publication which utilizes GraphSAGE algorithm. In the publication they incorporate two hidden layers of size [256. 256] within GraphSAGE. I am using GDS within neo4j and there doesn't seem to be an option to incorporate two hidden layers. However this seems to be possible within other libraries https://stellargraph.readthedocs.io/en/stable/demos/embeddings/graphsage-unsupervised-sampler-embeddings.html#Unsupervised-GraphSAGE:

**Describe the solution you would like**
Parameter within GraphSAGE conflict allowing for custom number of layer

**Comment by FlorentinD** [comment]
Hello @piotrkan ,
you can configure the number of layers using the `sampleSizes` parameter

from the docs

`
A list of Integer values, the size of the list determines the number of layers and the values determine how many nodes will be sampled by the layers.
`

Maybe we could add an explicit example to the docs?

**Comment by piotrkan** [comment]
HI @FlorentinD  thanks for prompt reply! 

Thanks for clarification; is it possible then to configure the number of dimensions of each of the layers? I want to have [256, 256] dimensions of the hidden layers and neighbor sampling size for each of these layers set to 96, with the final output vector being 512. 

I am trying to reproduce the following configuration of GraphSage
![image](https://github.com/user-attachments/assets/de99aaba-fc9c-4ae9-b8fd-9bea3566e9bf)

**Comment by brs96** [comment]
Hi @piotrkan ,

That is a current restriction, `embeddingDimension` is not per layer. However I don't see that the screenshot you are trying to reproduce mentions the output is 512. They seem to do [256,256]?

**Comment by piotrkan** [comment]
Hi @brs96 sorry for delayed reply. Thanks for explanation, good to be aware of potential restrictions. In the paper the hidden layers had 256 and 256 dimensions but the output size reported is 512. 

Off-topic but I have a question about activation function. GraphSAGE allows you to choose activation function between Sigmoid and ReLU. By default it's Sigmoid, does it mean that Sigmoid is implemented between the layers as well as for the final layer? or is it just the choice for the final layer?  I don't know Java but from what I read, it seems like Sigmoid is being implemented between the layers?

The reason why I am asking is because in the original [graphsage implementation that I found,](https://github.com/williamleif/GraphSAGE/blob/a0fdef95dca7b456dab01cb35034717c8b6dd017/graphsage/layers.py#L74) the Sigmoid layer is only implemented at the last layer and ReLU is implemented between the layers.

**Comment by brs96** [comment]
Hi @piotrkan ,

You're right, the same activation is applied in all layers, this is another existing limitation. 
On a side note, depending on what you're trying to achieve, even with the limitations removed it may not be worth it to completely reproduce the original setup, because differences in the Java/Python, backprop , seed etc. means that the scores can't be exactly the same.

**Comment by piotrkan** [comment]
Hi @brs96 thanks for confirmation! Its a good point about reproducing the results - in my case I am not trying to reproduce the results 1:1, I used the paper as a reference when looking for the most optimal parameters for my use case. Hence my questions about some of the params!

That answers all my questions, will close the issue now.
