### ISSUE TITLE
JSON file mapping GDS release versions to NEO4J release versions.

### ISSUE THREAD

**Issue by HungryGnu** [neo4j/graph-data-science#327]
**Is your feature request related to a problem? Please describe.**
I need a quick way to map the available GDS versions to Neo4J versions.

I would like a versions JSON document like APOC has:https://neo4j.github.io/apoc/versions.json

**Describe the solution you would like**
A json document that lists GDS versions and their compatible neo4j version.
It could be as simple as:
{"<GDS_VERSION":[<NEO4J_VERSIONS>],
...
}

**Describe alternatives you have considered**
This can be parsed out of README.md but a JSON file would be more user friendly.

**Additional context**

**Comment by vnickolov** [comment]
Hello @HungryGnu,

Would this work for you: https://graphdatascience.ninja/versions.json

**Comment by vnickolov** [comment]
@HungryGnu, this is the file that is being used by Neo4j Desktop, and is kept up to date, I am closing this issue.

**Comment by HungryGnu** [comment]
@vnickolov the remaining question I have is why is this hosted on 'graphdatascience.ninja' and not a part of the graph-data-science repository itself?

**Comment by vnickolov** [comment]
@HungryGnu the reason is that this file is generated and updated whenever there is either Neo4j or GDS release and is more convenient to host it externally than maintaining it in GitHub. 
I hope this helps.
