### ISSUE TITLE
Write edge properties during community detection

### ISSUE THREAD

**Issue by HashRocketSyntax** [neo4j/graph-data-science#33]
## Feature Request

I'd like to be able to persist the *community of each edge*. 

Is that information known, but discarded deep in the source code? Perhaps there is a way to `return` the edges and I missed it. Either way, it would be nice to just `write` the edges.

---

#### Use Case

1. I cannot understand the communities without the edges. My graphs are too complete to infer this information.
2. I'd like to feed this edge community attribute into my graph neural net.

---

#### Details

> https://neo4j.com/docs/graph-data-science/current/algorithms/label-propagation/

<table>
    <thead>
        <tr>
            <th align="center">Nodes</th>
            <th align="center">Edges</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td align="center">nodeWeightProperty</td>
            <td align="center">relationshipWeightProperty</td>
        </tr>
        <tr>
            <td align="center">writeProperty</td>
            <td align="center"><i>null</i></td>
        </tr>
        <tr>
            <td align="center">nodePropertiesWritten</td>
            <td align="center"><i>null</i></td>
        </tr>
    </tbody>
</table>

---
Separate request = Return the nodes and edges of each community as a named_graph. We provide named_graphs as input. It's only fair!

**Comment by AliciaFrame** [comment]
Our community detection algorithms are all node based -- each node is assigned to a single community, and the edges aren't explicitly considered or assigned to communities in their own right. While there _are_ edge based community detection algorithms (eg. https://www.nature.com/articles/srep22470) we  haven't yet implemented them for Neo4j. If you want to assign a community to your edges, you could use a cypher statement to set a relationship property based on the neighboring nodes.

For you second request (returning named graphs representing each community), that's an interesting idea -- we've created a card on our planning wall to consider that feature in a future release. Thank you for suggesting it :)
