### ISSUE TITLE
Inconsistent FastRP Embeddings with Fixed randomSeed in Neo4j GDS

### ISSUE THREAD

**Issue by MaxLohove** [neo4j/graph-data-science#335]
**Describe the bug**
I am analyzing topological similarity between two nodes and their networks using the FastRP algorithm. My objective is to make controlled changes to the network, rerun FastRP, and observe if similarity increases or decreases.

However, when rerunning FastRP with the same randomSeed value, the results vary across executions. This contradicts the documentation, which indicates randomSeed should control all randomness for reproducible embeddings ([FastRP documentation](https://neo4j.com/docs/graph-data-science/current/machine-learning/node-embeddings/fastrp/)).

A similar issue was previously encountered with node2vec, and the suggested solution was to set concurrency to 1 ([see issue #332](https://github.com/neo4j/graph-data-science/issues/332)). However, this solution has not worked for FastRP in my case.

If an alternative algorithm is more suitable for reproducible embeddings, I am open to adjusting my approach.

**To Reproduce**

```
from neo4j import GraphDatabase

# Connection details
NEO4J_URI = "bolt://localhost:9687/"
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = "neo4j_test_password"

# Configuration settings
GRAPH_NAME = "TestGraph"
WRITE_PROPERTY = "embedding"
FAST_RP_CONFIG = FastRPConfiguration(
    iteration_weights=[100.0, 10.0, 1.0], random_seed=1337
)
NUM_EXECUTIONS = 10

driver = GraphDatabase().driver(uri=NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))

# Function to calculate similarity between two nodes using FastRP
def calculate_similarity():
    with driver.session() as session:
        session.run("MATCH (N) DETACH DELETE N")
        # remove graph projection if it exists
        session.run(
            """
            CALL gds.graph.list()
            YIELD graphName AS graph_name
            CALL {
                WITH graph_name
                CALL gds.graph.drop(graph_name)
                YIELD graphName
            }
        """
        )

        session.run(
            """
            CREATE (First_a:First {Label: "First 1"})
            CREATE (First_b:First {Label: "First 2"})
            CREATE (Second:Second {Label: "Second"})
            CREATE (Third:Third {Label: "Third"})
            MERGE (First_a)<-[:USES]-(Second)
            MERGE (First_a)<-[:USES]-(Third)
            MERGE (First_b)<-[:USES]-(Third)
            """,
        )

        session.run(
            """
            MATCH (source)-[r]->(target)
            WITH gds.graph.project(
                    $graph_name,
                    source,
                    target,
                    $data_config,
                    $config
                ) AS g
            // Return the graph name, node count, and relationship count
            RETURN g.graphName AS graph_name, g.nodeCount AS node_count, g.relationshipCount AS relationship_count
            """,
            parameters={
                "graph_name": GRAPH_NAME,
                "data_config": {},
                "config": {"undirectedRelationshipTypes": ["*"]},
            },
        )

        # Run FastRP with given configuration and concurrency set to 1
        session.run(
            """
            CALL gds.fastRP.write(
                $graph_name,
                {
                    writeProperty: $write_property,
                    embeddingDimension: $embedding_dimension,
                    iterationWeights: $iteration_weights,
                    normalizationStrength: $normalization_strength,
                    randomSeed: $random_seed,
                    concurrency: 1
                }
            )
            """,
            parameters={
                "graph_name": GRAPH_NAME,
                "write_property": WRITE_PROPERTY,
                "embedding_dimension": FAST_RP_CONFIG.embedding_dimension,
                "iteration_weights": FAST_RP_CONFIG.iteration_weights,
                "normalization_strength": FAST_RP_CONFIG.normalization_strength,
                "random_seed": FAST_RP_CONFIG.random_seed,
            },
        )
        # Compute similarity between nodes
        results = session.run(
            f"""
            MATCH (First_a:First {{Label: "First 1"}}), (First_b:First {{Label: "First 2"}})
            WITH gds.similarity.cosine(First_a.{WRITE_PROPERTY}, First_b.{WRITE_PROPERTY}) AS similarity
            RETURN similarity
            """
        ).single()
        if not results:
            raise ValueError("No results found")
    return results["similarity"]

results = [calculate_similarity() for i in range(1, NUM_EXECUTIONS)]
results
```

[0.7722555280562642,
 0.6587776898683295,
 0.7495241137581521,
 0.653958844276052,
 0.7438637713351416,
 0.7252064525339789,
 0.7422746017148159,
 0.7081793621027523,
 0.6547023154363596]
 
 

Neo4j Version: 5.24.2 (Docker Image neo4j:5.24.2)
GDS Version: 2.11.0
Operating System: Windows 11
Container Information: Running in Docker

**Expected behavior**
The embeddings generated by FastRP for two nodes should remain consistent across executions when randomSeed and concurrency are fixed.

**Additional context**
FastRPConfiguration is a custom Pydantic model to store FastRP parameters. The random_seed property remains constant throughout.

CALL gds.debug.sysInfo
| key | value |
|-----|--------|
| "gdsVersion" | "2.11.0"|
| "gdsEdition" | "Unlicensed"|
| "neo4jVersion" | "5.24.2"|
| "minimumRequiredJavaVersion" | "17"|
| "unavailableCompatibility" | "Neo4j 5.23"|
| "availableCompatibility" | "Neo4j 5.24"|
| "featureBitIdMap" | true|
| "featureUncompressedAdjacencyList" | false|
| "featurePackedAdjacencyList" | false|
| "featureReorderedAdjacencyList" | false|
| "featureArrowDatabaseImport" | true|
| "buildDate" | "2024-10-01_15:11:03"|
| "buildJdk" | "17.0.12+7 (Eclipse Adoptium)"|
| "buildJavaVersion" | "17"|
| "buildHash" | "05c656af76dbb573c79d32d09b6c0d70d3716491"|
| "availableCPUs" | 8|
| "physicalCPUs" | 8|
| "availableHeapInBytes" | 3122659328|
| "availableHeap" | "2978 MiB"|
| "heapFreeInBytes" | 367681632|
| "heapFree" | "350 MiB"|
| "heapTotalInBytes" | 664797184|
| "heapTotal" | "634 MiB"|
| "heapMaxInBytes" | 3122659328|
| "heapMax" | "2978 MiB"|
| "offHeapUsedInBytes" | 523896200|
| "offHeapUsed" | "499 MiB"|
| "offHeapTotalInBytes" | 529661952|
| "offHeapTotal" | "505 MiB"|
| "poolCodeheapNonNmethodsUsedInBytes" | 2586752|
| "poolCodeheapNonNmethodsUsed" | "2526 KiB"|
| "poolCodeheapNonNmethodsTotalInBytes" | 2752512|
| "poolCodeheapNonNmethodsTotal" | "2688 KiB"|
| "poolMetaspaceUsedInBytes" | 381969920|
| "poolMetaspaceUsed" | "364 MiB"|
| "poolMetaspaceTotalInBytes" | 385744896|
| "poolMetaspaceTotal" | "367 MiB"|
| "poolCodeheapProfiledNmethodsUsedInBytes" | 56570112|
| "poolCodeheapProfiledNmethodsUsed" | "53 MiB"|
| "poolCodeheapProfiledNmethodsTotalInBytes" | 56623104|
| "poolCodeheapProfiledNmethodsTotal" | "54 MiB"|
| "poolCompressedClassSpaceUsedInBytes" | 54365616|
| "poolCompressedClassSpaceUsed" | "51 MiB"|
| "poolCompressedClassSpaceTotalInBytes" | 56098816|
| "poolCompressedClassSpaceTotal" | "53 MiB"|
| "poolG1EdenSpaceFreeInBytes" | 115343360|
| "poolG1EdenSpaceFree" | "110 MiB"|
| "poolG1EdenSpaceTotalInBytes" | 245366784|
| "poolG1EdenSpaceTotal" | "234 MiB"|
| "poolG1EdenSpaceMaxInBytes" | -1|
| "poolG1EdenSpaceMax" | "N/A"|
| "poolG1OldGenFreeInBytes" | 251441152|
| "poolG1OldGenFree" | "239 MiB"|
| "poolG1OldGenTotalInBytes" | 413138944|
| "poolG1OldGenTotal" | "394 MiB"|
| "poolG1OldGenMaxInBytes" | 3122659328|
| "poolG1OldGenMax" | "2978 MiB"|
| "poolG1SurvivorSpaceFreeInBytes" | 897120|
| "poolG1SurvivorSpaceFree" | "876 KiB"|
| "poolG1SurvivorSpaceTotalInBytes" | 6291456|
| "poolG1SurvivorSpaceTotal" | "6144 KiB"|
| "poolG1SurvivorSpaceMaxInBytes" | -1|
| "poolG1SurvivorSpaceMax" | "N/A"|
| "poolCodeheapNonProfiledNmethodsUsedInBytes" | 28406656|
| "poolCodeheapNonProfiledNmethodsUsed" | "27 MiB"|
| "poolCodeheapNonProfiledNmethodsTotalInBytes" | 28442624|
| "poolCodeheapNonProfiledNmethodsTotal" | "27 MiB"|
| "freePhysicalMemoryInBytes" | 8949530624|
| "freePhysicalMemory" | "8534 MiB"|
| "committedVirtualMemoryInBytes" | 9548505088|
| "committedVirtualMemory" | "9106 MiB"|
| "totalPhysicalMemoryInBytes" | 12485439488|
| "totalPhysicalMemory" | "11907 MiB"|
| "freeSwapSpaceInBytes" | 3221225472|
| "freeSwapSpace" | "3072 MiB"|
| "totalSwapSpaceInBytes" | 3221225472|
| "totalSwapSpace" | "3072 MiB"|
| "openFileDescriptors" | 470|
| "maxFileDescriptors" | 1048576|
| "vmName" | "OpenJDK 64-Bit Server VM"|
| "vmVersion" | "17.0.13+11"|
| "vmCompiler" | "HotSpot 64-Bit Tiered Compilers"|
| "containerized" | true|
| "dbms.security.procedures.unrestricted" | "apoc.*,gds.*,n10s.*"|
| "db.tx_state.memory_allocation" | "ON_HEAP"|
| "server.memory.pagecache.size" | 536870912|
| "server.memory.off_heap.transaction_max_size" | 2147483648|
| "dbms.memory.transaction.total.max" | 2185861529|
| "db.memory.transaction.total.max" | 0|
| "db.memory.transaction.max" | 0|

**Comment by breakanalysis** [comment]
Hi Max, 

The cause of the non-determinism is likely that the graph is deleted and recreated between runs.
You are correct that FastRP should be deterministic given a fixed random seed, however that applies only when the same graph is used. FastRP uses neo4j node ids to compare nodes. Hence if the re-created graph has new node ids, the algorithm has no way of identifying the new graph with the old graph.
Typically when removing nodes and creating new ones in neo4j, the nodeid counter is not reset back to 0.
More precisely, fastrp will use the a combination of the random seed and the neo4j node id to obtain the initial random vector for each node.

If you can rewrite the example so that it drops the created embedding property instead of deleting the graph, the results should become deterministic.

You can also try to verify that the node'ids have been changed 
```
MATCH (n {Label: "First 1"}) RETURN id(n)
``` 

Let us know if the behavior persists after the applying the suggestions.

Best regards,
Jacob Sznajdman

**Comment by MaxLohove** [comment]
Hi Jacob,

I can confirm that the results are consistent and deterministic if the graph is not dropped in between calculations. Is there any way to use a node property instead of the internal node id Neo4j uses?

My graph has unique identifiers (UUIDs) for each node and relationship that remain consistent even after deletion of nodes. 
As [cypher projections](https://neo4j.com/docs/graph-data-science/current/management-ops/graph-creation/graph-project-cypher-projection/#graph-project-cypher-projection-syntax) only allow for integers or nodes to be projected, I tried casting the UUID to a big integer, but this caused various internal problems as the integer was too big to handle. 

Is there a more elegant way to allow for the consistency of the algorithm, even if node ids vary?
In my current setup I aimed to quantify the amount of change introduced to a network by running the algorithm on a test dataset. This, however, can never be consistent as the container is regularly restarted and emptied depending on the tests.

Thank you for your support,
Best regards,
Max Lohove

**Comment by breakanalysis** [comment]
Hi Max,

I understand, your request makes sense.
There is no way currently to use a node property instead of the node ids.
I will raise this as a feature request internally.

What you could do meanwhile, if you have other properties on the node you can use them as featureProperties and set propertyRatio=1.0. In that case the nodeIds are not used at all.
Theoretically you can one-hot encode the UUIDs and use the one-hot encoding as a featureProperty, but that would be completely infeasible due to high dimension. You could thus write a script that multiplies the one-hot encoding with a random projection matrix, write that back as a "approximate vectorized nodeId" and use that as a featureProperty.
However then you are doing manually part of the job that fastRP is supposed to be doing, but I thought I'd mention it if the idea is appealing despite of that.

Thanks for your input!
