### ISSUE TITLE
GDS 2.12 - Graph Object has no attribute 'name'

### ISSUE THREAD

**Issue by Mintactus** [neo4j/graph-data-science#338]
Neo4j 5.25.1
GDS 2.12
GDS Python Client 1.12

This is a shitshow, I have been stuggeling to make a simple projection works since hours and I never had a problem like that, something is wrong with GDS 2.12.

I'm also the one who wrote the "[GDS - RandomWalk - Unable to load NODE](https://community.neo4j.com/t/gds-randomwalk-unable-to-load-node/71513)" post. I hink both problems could be linked.

```
  File "/venv/lib/python3.12/site-packages/graphdatascience/algo/algo_proc_runner.py", line 16, in _run_procedure
    params = CallParameters(graph_name=G.name(), config=config)
                                       ^^^^^^
AttributeError: 'GraphCreateResult' object has no attribute 'name'
```

This is the call I used

```
    def run_random_walk(self):
        gds = GraphDataScience(NEO4j_CREDENTIALS['uri'], auth=NEO4j_CREDENTIALS['auth'], database=PAIR)
        graph = gds.graph.project(
            graph_name = 'eurusd',
            node_spec = {'Pattern': {'properties': 'pattern'}},  # Node projection
            relationship_spec = {'TO': {'properties': 'transition probability'}})
        pattern = self.markov_chain_nodes['pattern'].last()
        sourceNode = gds.find_node_id(["Pattern"], {"pattern": pattern})
        print(sourceNode)

        random_walk_config = {
            'sourceNodes': [sourceNode],
            'walkLength': FUTURE_SIZE,
            'walksPerNode': 1,
            'relationshipWeightProperty': 'transition probability',
            'concurrency': 4
        }
        future = gds.randomWalk.stream(graph, **random_walk_config)
        print(future)
```

If you need anything else let me know

Thanks for your support

**Comment by IoannisPanagiotas** [comment]
Hi again @Mintactus,

Can you try G = gds.graph.get("eurusd") and use G to run the  randomWalk?

The  `graph` in your instance corresponds to the projection result which is not necessarily the graph object. Doing the line above should help.

Also, make sure to check  florentin's reply to your other [thread](https://github.com/neo4j/graph-data-science/issues/337#issuecomment-2491097327)  bypass creating a disk graph.

Best regards,
Ioannis.

**Comment by Mintactus** [comment]
Thanks Ioannis

I will test both soon :)

**Comment by FlorentinD** [comment]
As a tip, I can also recommend using [mypy](https://www.mypy-lang.org/) to find out such problems.

Also our API docs contain the GraphCreateResult (see https://neo4j.com/docs/graph-data-science-client/1.12/api/graph_create_result/). 
Its actually a named tuple, thats why you can use `result.graph` as well

**Comment by Mintactus** [comment]
Thanks guys, I will mark the issue as closed.
