### ISSUE TITLE
Unable to start neo4j 5.26.0 with gds 2.13.1

### ISSUE THREAD

**Issue by WindyOrgUK** [neo4j/graph-data-science#340]
I am Unable to start neo4j 5.26.0 with gds 2.13.1
both via /etc/init.d/neo4j start
and
/usr/bin/neo4j start

The most meaningful log entry says:

Caused by: org.neo4j.kernel.extension.FailedToBuildExtensionException: Failed to build kernel extension Extension:GraphDataScienceExtension[gds.closed] because it is compiled with a reference to a class, method, or field, that is not in the class path: 'io/prometheus/client/Collector'. The most common cause of this problem, is that Neo4j has been upgraded without also upgrading all installed extensions, such as APOC. Make sure that all of your extensions are build against your specific version of Neo4j.

GDS version: 2.13.1
Neo4j version: 5.26.0
Ubuntu 24.04

============

ls -al /var/lib/neo4j/plugins/
total 65352
drwxr-xr-x  2 neo4j adm     4096 Dec 12 11:58 .
drwxr-xr-x 12 neo4j adm     4096 Dec 12 11:56 ..
-rw-r--r--  1 neo4j adm  2962191 Dec  6 10:08 apoc-5.26.0-core.jar
-rw-r--r--  1 neo4j adm 63935636 Dec 11 16:31 neo4j-graph-data-science-2.13.1.jar
-rw-r--r--  1 neo4j adm     2217 Dec  5 12:07 README.txt

============

java --version
openjdk 17.0.13 2024-10-15
OpenJDK Runtime Environment (build 17.0.13+11-Ubuntu-2ubuntu124.04)
OpenJDK 64-Bit Server VM (build 17.0.13+11-Ubuntu-2ubuntu124.04, mixed mode, sharing)

============

The server only fails to start if neo4j-graph-data-science-2.13.1.jar file is in the plugin folder.
Wit only apoc-5.26.0-core.jar in plugin folder the server starts just fine

The jar files in https://github.com/neo4j/graph-data-science/releases seem to have been updated just 19 hrs ago, while the src file 3 days ago.
Is there a chance that this newly compiled plugin has not been tested on Linux ?

**Comment by FlorentinD** [comment]
Hey @WindyOrgUK ,
Thank you for reporting the issue.
Its actually a problem with Community Neo4j + GDS.

We are already working on a fix 🤞

**Comment by WindyOrgUK** [comment]
Thank you @FlorentinD for quick response.
Is the fix ETA closer to days or rather weeks ?

**Comment by FlorentinD** [comment]
Closer to days.
I would hope even in a couple of hours.

**Comment by Mats-SX** [comment]
@WindyOrgUK I am pleased to announce the release of GDS version 2.13.2. You can download it via [this link](https://graphdatascience.ninja/neo4j-graph-data-science-2.13.2.jar). Please report back here again if it still does not work for you, and we'll reopen the issue.

Note that if you're an openGDS user, there is a slight delay (1-6h) for the Maven Central publication to reach all mirrors.

All the best
Mats

**Comment by WindyOrgUK** [comment]
in progress
