### ISSUE TITLE
Failed to invoke procedure `gds.alpha.spanningTree.minimum.write`: Caused by: java.lang.IllegalArgumentException: Cannot construct a relationship filter out of a java.lang.Long

### ISSUE THREAD

**Issue by amitabak-MA** [neo4j/graph-data-science#35]
Branch: master
Reconstruct: 

Step 1:

```
CREATE (a:Place {id: 'A'}),
       (b:Place {id: 'B'}),
       (c:Place {id: 'C'}),
       (d:Place {id: 'D'}),
       (e:Place {id: 'E'}),
       (f:Place {id: 'F'}),
       (g:Place {id: 'G'}),
       (d)-[:LINK {cost:4}]->(b),
       (d)-[:LINK {cost:6}]->(e),
       (b)-[:LINK {cost:1}]->(a),
       (b)-[:LINK {cost:3}]->(c),
       (a)-[:LINK {cost:2}]->(c),
       (c)-[:LINK {cost:5}]->(e),
       (f)-[:LINK {cost:1}]->(g);
```

Step 2

```
MATCH (n:Place {id: 'D'})
CALL gds.alpha.spanningTree.minimum.write({
  nodeProjection: 'Place',
  relationshipProjection: {
    LINK: {
      type: 'LINK',
      properties: 'cost',
      orientation: 'UNDIRECTED'
    },
    startNodeId: id(n),
    relationshipWeightProperty: 'cost',
    writeProperty: 'MINST',
    weightWriteProperty: 'writeCost'
  }
})
YIELD createMillis, computeMillis, writeMillis, effectiveNodeCount
RETURN createMillis, computeMillis, writeMillis, effectiveNodeCount;
```

Getting

```
Neo.ClientError.Procedure.ProcedureCallFailed
Failed to invoke procedure `gds.alpha.spanningTree.minimum.write`: Caused by: java.lang.IllegalArgumentException: Cannot construct a relationship filter out of a java.lang.Long
```

**Comment by Mats-SX** [comment]
Hello @amitabak-MA and thanks for reaching out to us!

I took the liberty of editing your issue with some markup to improve readability. I believe there is a small syntax error in your query. Could you try to run this:

```
MATCH (n:Place {id: 'D'})
CALL gds.alpha.spanningTree.minimum.write({
  nodeProjection: 'Place',
  relationshipProjection: {
    LINK: {
      type: 'LINK',
      properties: 'cost',
      orientation: 'UNDIRECTED'
    }
  },
  startNodeId: id(n),
  relationshipWeightProperty: 'cost',
  writeProperty: 'MINST',
  weightWriteProperty: 'writeCost'
})
YIELD createMillis, computeMillis, writeMillis, effectiveNodeCount
RETURN createMillis, computeMillis, writeMillis, effectiveNodeCount;
```

As an alternative, you could separate the graph projection from the algorithm configuration, to simplify the configuration of the two:

```
CALL gds.graph.create('my-graph', 'Place', {
    LINK: {
      type: 'LINK',
      properties: 'cost',
      orientation: 'UNDIRECTED'
    }
  }
)
```

and then

```
CALL gds.alpha.spanningTree.minimum.write('my-graph', {
  startNodeId: id(n),
  relationshipWeightProperty: 'cost',
  writeProperty: 'MINST',
  weightWriteProperty: 'writeCost'
})
```

**Comment by amitabak-MA** [comment]
Thanks for the answer.
Results...
First query works and returned the value 
![image](https://user-images.githubusercontent.com/52035400/80299639-a15c8880-879e-11ea-8dc1-12b3ee9de7dc.png)

Ass for the second option ..
The graph.create ... works but the second call match(n:Place.....) failed without adding the following two lines at the bottom . Once added, it run succesfuly
YIELD createMillis, computeMillis, writeMillis, effectiveNodeCount
RETURN createMillis, computeMillis, writeMillis, effectiveNodeCount

**Comment by Mats-SX** [comment]
Ah, yes of course! I forgot that when the `CALL` is used in conjunction with other clauses (`MATCH` in this case) it mandates that `YIELD` and `RETURN` are given. Thanks for pointing that out.

For future reference, here is a working version of the second query:

```
MATCH (n:Place {id: 'D'})
CALL gds.alpha.spanningTree.minimum.write('my-graph', {
  startNodeId: id(n),
  relationshipWeightProperty: 'cost',
  writeProperty: 'MINST',
  weightWriteProperty: 'writeCost'
})
YIELD createMillis, computeMillis, writeMillis, effectiveNodeCount
RETURN createMillis, computeMillis, writeMillis, effectiveNodeCount
```

I'm glad you got past the error!

**Comment by AdamMCG97** [comment]
Hello, I also ran into this issue. The original post is just a copy of the example in the GDS docs: 

https://neo4j.com/docs/graph-data-science/current/alpha-algorithms/minimum-weight-spanning-tree/

The missing bracket syntax error is in the example in section 5.5.1.5, hopefully this could be updated to avoid others running into this issue in the future?

**Comment by Mats-SX** [comment]
@AdamMCG97 Thanks for pointing that out! Yes, we will amend this. I'll close this issue once it's dealt with.

**Comment by lingxuan9** [comment]
Hi, I have a question about the performance of create a new graph? Sometimes it costs me 1 hours to run the query in a graph with only 3000 nodes. Does it normal?

**Comment by Mats-SX** [comment]
Hello @lingxuan9 

It doesn't sound like your issue is with `spanningTree`, is that right? If you have an issue with graph projections, could you please open a new GitHub issue and also provide details on your data and the queries (GDS procedure calls) that you are using?
