### ISSUE TITLE
Cannot install on Neo4j 4.0.3

### ISSUE THREAD

**Issue by aaramg** [neo4j/graph-data-science#36]
The plugin is disabled in Neo4j Desktop to install.

P.S. If it is not supported on version 4,,, please could you write somewhere for people like me to know when to expect the release? I could not find anywhere info about it.

**Comment by kingoodie** [comment]
It must be installed manually at this time. Download the plugin from [Neo4j Download Center](https://neo4j.com/download-center/) and place the file in your plugins directory (if you're using Neo4j Desktop: Manage>Open folder and your desktop browser will open at the database location).

**Comment by soerenreichardt** [comment]
Hi @aaramg ,
currently GDS does not support Neo4j 4.x. However it will be supported with the 1.2 release coming this week on May 7th.
We will discuss a place to display such information for future releases.

**Comment by aaramg** [comment]
Nice to hear :) Thanks for the response.

**Comment by AliciaFrame** [comment]
I've updated the readme to include a compatibility matrix and a link to the installation instructions in our documentation. 

You can download the preview release of 1.2 and install it manually, or we will make it available in Desktop once it's GA.
