### ISSUE TITLE
Feature request: Node similarity stats mode return additional column similarityPairs

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#37]
Currently when evaluating stats with `gds.nodeSimilarity.stats`, it is really hard if not impossible to evaluate how many similarity relationships will be created if I would run the algorithm in write mode with the current settings. It would be nice if we could get the same value as we get with the `relationshipsWritten` return of the `write` mode.

**Comment by FlorentinD** [comment]
done in 17c531cfb2d7aaa1a54eb736e669b3de7e78dc09

**Comment by FlorentinD** [comment]
@Mats-SX @tomasonjo  I think this issue can be closed, as it is implemented in the commit I referenced.

**Comment by tomasonjo** [comment]
Sure, thanks @FlorentinD
