### ISSUE TITLE
Update the versions json to include 3.5.18

### ISSUE THREAD

**Issue by BalmungSan** [neo4j/graph-data-science#38]
**Neo4j** `3.5.18` was released recently and is the first `3.5.x` release whose docker image supports the **gds** plugin out of the box using the `NEO4JLABS_PLUGINS` env var.
However, since the [versions.json](https://s3-eu-west-1.amazonaws.com/com.neo4j.graphalgorithms.dist/graph-data-science/versions.json) file doesn't include this new version, it fails to run.

Would it be possible to update this file?
Or will we have to wait for a new `1.1.2` release of the **gds** plugin?

**Comment by vnickolov** [comment]
Hello @BalmungSan,

Thank you for reaching out, we have updated the `versions.json` file, can you please give it a try and let us know how it goes.

**Comment by BalmungSan** [comment]
Hi @vnickolov juest tested it, everything working as expected!

Thanks for quick reply and fix!

**Comment by vnickolov** [comment]
@BalmungSan, I'm really glad it's working fine.

**Comment by BalmungSan** [comment]
Hi @vnickolov sorry for bothering you again.
Something similar just happened with `4.0.5` I guess again the fix should be just updating the `versions.json` file.

Random thought, maybe that file should support some kind of regex like `4.0.x` so you guys do not have to update it every time a new version of the server is published.

**Comment by Mats-SX** [comment]
@BalmungSan Thanks for reporting this. Yes, when Neo4j releases a new patch we are not immediately compatible, but we have to update our dependency and run all tests. If this works out well we could just update `versions.json`, but sometimes we have to modify code to make it compatible and then we have to release this new code under a new version, so it can take a little longer than one would like. Our process around this does need to be improved (and we're working on it), but using a future-compatible regex wouldn't be safe.

**Comment by BalmungSan** [comment]
@Mats-SX makes sense.

One may say that for a patch release nothing should go wrong.

But well, a database is a complex technology as well as all the graph algorithms.
And I understand the sentiment of making sure everything works as expected.

**Comment by Mats-SX** [comment]
@BalmungSan You're right, but we're not using Neo4j public API, but we reach deep into the internals, which _need_ to change sometimes to fix bugs. This is expected to (slowly) improve over time as we mature our collaboration with the core database.

**Comment by BalmungSan** [comment]
Hi @Mats-SX @vnickolov 

Sorry, for troubling you.
I am coming to report a simple typo in the _version.json_ file.
The entry for **Neo4j** `4.0.6` has a typo in the `jar` entry, it asks for a `1.2.3` version, whereas the correct one would be `1.2.2`

**Comment by vnickolov** [comment]
Thank you very much @BalmungSan, this should be fixed now.
