### ISSUE TITLE
KSpanningTree java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 19812484

### ISSUE THREAD

**Issue by amitabak-MA** [neo4j/graph-data-science#39]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 19812484
        at org.neo4j.graphalgo.impl.spanningTrees.KSpanningTree.compute(KSpanningTree.java:94)
        at org.neo4j.graphalgo.impl.spanningTrees.KSpanningTree.compute(KSpanningTree.java:41)

When added a protection around line 94 
 // remove k-1 relationships
        for (int i = 0; i < k - 1 && running(); i++) {
            int cutNode = priorityQueue.pop();
            if ((0 <= cutNode) && (cutNode < parent.length)) {
                parent[cutNode] = -1;
            }else{
                logger.logMessage("kSpanningTree error: k:" + k + " i:" + i + " priorityQueue.isEmpty:"+priorityQueue.isEmpty());
            }
        }

The algorithm finishes the run and the log shows:

➜  installation-4.0.3 grep kSpanningTree ./logs/*
./logs/debug.log:2020-05-16 03:29:11.649+0000 INFO [o.n.k.a.p.GlobalProcedures] [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:52535] ] KSpanningTree 100% kSpanningTree error: k:10 i:4 priorityQueue.isEmpty:true
./logs/debug.log:2020-05-16 03:29:11.649+0000 INFO [o.n.k.a.p.GlobalProcedures] [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:52535] ] KSpanningTree 100% kSpanningTree error: k:10 i:5 priorityQueue.isEmpty:true
./logs/debug.log:2020-05-16 03:29:11.649+0000 INFO [o.n.k.a.p.GlobalProcedures] [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:52535] ] KSpanningTree 100% kSpanningTree error: k:10 i:6 priorityQueue.isEmpty:true
./logs/debug.log:2020-05-16 03:29:11.649+0000 INFO [o.n.k.a.p.GlobalProcedures] [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:52535] ] KSpanningTree 100% kSpanningTree error: k:10 i:7 priorityQueue.isEmpty:true
./logs/debug.log:2020-05-16 03:29:11.650+0000 INFO [o.n.k.a.p.GlobalProcedures] [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:52535] ] KSpanningTree 100% kSpanningTree error: k:10 i:8 priorityQueue.isEmpty:true
./logs/neo4j.log:2020-05-16 03:29:11.649+0000 INFO  [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:52535] ] KSpanningTree 100% kSpanningTree error: k:10 i:4 priorityQueue.isEmpty:true
./logs/neo4j.log:2020-05-16 03:29:11.649+0000 INFO  [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:52535] ] KSpanningTree 100% kSpanningTree error: k:10 i:5 priorityQueue.isEmpty:true
./logs/neo4j.log:2020-05-16 03:29:11.649+0000 INFO  [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:52535] ] KSpanningTree 100% kSpanningTree error: k:10 i:6 priorityQueue.isEmpty:true
./logs/neo4j.log:2020-05-16 03:29:11.649+0000 INFO  [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:52535] ] KSpanningTree 100% kSpanningTree error: k:10 i:7 priorityQueue.isEmpty:true
./logs/neo4j.log:2020-05-16 03:29:11.649+0000 INFO  [neo4j.BoltWorker-5 [bolt] [/127.0.0.1:52535] ] KSpanningTree 100% kSpanningTree error: k:10 i:8 priorityQueue.isEmpty:true

**Comment by FlorentinD** [comment]
This is very likely also based on a wrong `startNodeId` (one that wasn't loaded).

**Comment by amitabak-MA** [comment]
@FlorentinD 
The node exists in the graph.
The query I run is of the form that is shown in the tutorial  and below and once I added my guards it actually returns valid results . 
Not sure why the cost of the  check is so expensive relative to other compute running at query time.
Should I open a PR or will this be handled by neo's team  in some other way that will fix it ? 
MATCH (n:qqqqqqq {abc: 'XXX'})
CALL gds.alpha.spanningTree.kmin.write({
  nodeProjection: 'qqqqqqq',
  relationshipProjection: {
    LINK: {
      type: 'YYYYY',
      orientation: 'NATURAL'
    }
  },
  k: 2,
  startNodeId: id(n),
  writeProperty: 'YYYYY_MINST',
  weightWriteProperty: zzzzzzzz
})
YIELD createMillis, computeMillis, writeMillis, effectiveNodeCount
RETURN createMillis, computeMillis, writeMillis, effectiveNodeCount;

**Comment by FlorentinD** [comment]
I definitely could find and fix a bug, where the startNodeId did not exists. Because -1 is the result of the neo-id could not be mapped to our in-memory graph id.

Your query seems valid however.
Could you give me an example graph, where the error occurs?

**Comment by FlorentinD** [comment]
And you don’t need to open in PR. If we find another error, it should get fixed by the neo team.

**Comment by FlorentinD** [comment]
@amitabak-MA I found another bug in `spanningTree.kmin`.
Maybe you could try it out and verify, if this solves your issue :)

**Comment by FlorentinD** [comment]
I will close this issue now.
Feel free to reopen the issue, if the bug still occurs!
