### ISSUE TITLE
Relationship count is zero

### ISSUE THREAD

**Issue by kingebere** [neo4j/graph-data-science#42]
Call gds.graph.write gives result of relationshipcount is zero.

**Comment by FlorentinD** [comment]
Did you check, that the relationship type exists in the in-memory graph? 
You could check by calling `gds.graph.list($graphName) YIELD schema`.
Relationships are currently only created via _node similarity_ and written to the in-memory graph, if you use the `mutate` mode.

Could you explain in more detail, when this occurs?

**Comment by Mats-SX** [comment]
Closing this as unresponsive. Please feel free to reach back and we'll re-open to investigate further.
