### ISSUE TITLE
bug in DFS

### ISSUE THREAD

**Issue by kpasko** [neo4j/graph-data-science#44]
discussed in community here - 
https://community.neo4j.com/t/data-science-dfs-returns-nonsense/18698

using several versions, but specifically the current data science sandbox, deleting everything, and running the code from here - 
https://neo4j.com/docs/graph-data-science/current/algorithms/dfs/?_ga=2.169582247.785309550.1590181766-1571973824.1590181766

note to see the issue  'order by' should be removed, as that only shows nodes reachable by the search but not the search order.  specifically this would be, given a new sandbox as default- 
```
MATCH p=()-[]-() detach delete p
MATCH (n) delete n
CREATE
       (nA:Node {tag: 'a'}),
       (nB:Node {tag: 'b'}),
       (nC:Node {tag: 'c'}),
       (nD:Node {tag: 'd'}),
       (nE:Node {tag: 'e'}),

       (nA)-[:REL {cost: 8.0}]->(nB),
       (nA)-[:REL {cost: 9.0}]->(nC),
       (nB)-[:REL {cost: 1.0}]->(nE),
       (nC)-[:REL {cost: 5.0}]->(nD)
MATCH (a:Node{tag:'a'})
WITH id(a) AS startNode
CALL gds.graph.create('myGraph', 'Node', 'REL', { relationshipProperties: 'cost' })
CALL gds.alpha.dfs.stream('myGraph', {startNode: startNode})
YIELD path
UNWIND [ n in nodes(path) | n.tag ] AS tags
RETURN tags
```
this will frequently return a non-dfs ordering. to confirm, returning the full path results in the same, as does setting concurrency to 1.

**Comment by Mats-SX** [comment]
There is an issue of usability here when it comes to some of the `stream` modes for algos that return ordered results. In general, Cypher does not guarantee order of records across clauses. The guarantee that exists is that a clause will consume records in the order the preceding clause outputted them, but in the absence of `ORDER BY` there is no guarantee that any subsequent clause will have any order.

Concretely, this means that in your query above, the `path` values that come from the `CALL gds.alpha.dfs.stream()` may actually have a correct DFS order, but this order can be lost following the `UNWIND` clause, and this is expected. Now, there might still be a bug in the DFS algorithm but it wouldn't be determinable by this query.

We discussed this briefly and we see two options that would circumvent this issue: either we project the path as a list instead of a number of rows, or we project an additional column indicating the DFS order, which can be used to `ORDER BY` later on in the query.

**Comment by kpasko** [comment]
Thanks for the detailed explanation, that makes sense. I think 
ORDER BY n.traversalTime
or somesuch is a reasonable solution (although it gets somewhat sticky if allowing for a “full traversal” type output which keeps track of return edges back up the graph)

I will mention though the path itself, if returned, also doesn't look like dfs

![image](https://user-images.githubusercontent.com/167271/82926646-5b791880-9f34-11ea-9db0-c8bf5a43fc0e.png)

![image](https://user-images.githubusercontent.com/167271/82928151-aeec6600-9f36-11ea-967c-f15f0932c60b.png)

**Comment by FlorentinD** [comment]
@kpasko There was indeed a bug in the dfs implementation.
Now the path itself should make sense again.

**Comment by kpasko** [comment]
Thanks for looking into this! Would also love your thoughts on different
path outputs as a feature.

**Comment by FlorentinD** [comment]
I like the idea of a traversal time.
But this might come in conflict with returning a list of nodeIds.
Having a list of tuples of (nodeId, traversalTime) looks a bit ugly IMO. 
Maybe just adding it as a property to the nodes in the _path_ might be an option.

**Comment by kpasko** [comment]
Yes i was thinking a relationship added similar to "next" that currently
exists. the return order would stay the same, but would allow an option to
query if desired

**Comment by FlorentinD** [comment]
In the meantime _ apoc.map.fromLists([keys],[values])_ should solve the problem, when combining the path with a range of 1 to size of _nodeIds_

**Comment by kpasko** [comment]
current benefits to this approach over apoc path expansion default dfs?

**Comment by FlorentinD** [comment]
Didn't know there was one.

So you would like a write mode for dfs/bfs correct? (With _writeRelationshipType_ and _writeNodeProperty_)

**Comment by kpasko** [comment]
>
>     MATCH (n) WHERE n.name="GLOBAL_ROOT"
>
>
>     CALL apoc.path.expandConfig(n, {
>
>
>       relationshipFilter: "FEEDS>",
>
>
>       minLevel: 1,
>
>
>       uniqueness: "RELATIONSHIP_GLOBAL",
>
>
>       bfs:false
>
>
>     })
>
>
>     YIELD path
>
>
>     with relationships(path) as ps
>
>
>     with endNode(ps[-1]) as cur, ps
>
>
>     set cur.level = apoc.coll.max([cur.level,size(ps)])
>
>



thats my current call using apoc. i don't know if the graph lib is meant to
phase out apoc calls, but at least mirroring the abilities for that call
would be a good start. I think write(*) as you mention is great, along with
potentially options for which to write (i.e. traversalFilter: withBackEdge
or what have you)

**Comment by kpasko** [comment]
Thanks for looking into it!

**Comment by FlorentinD** [comment]
I just mentioned the issue in the bugfix commit, so it won't close automatically.
Maybe @Mats-SX could close it? :)
