### ISSUE TITLE
Custom calculation for Yen’s K-Shortest Paths

### ISSUE THREAD

**Issue by kashish-draup** [neo4j/graph-data-science#45]
Can you provide a way for us to compute the total weight of a path with a custom function that might use more than one property to compute the total weight.

For example, each weight can be - X * GraphProperty1 + Y * GraphProperty2  
where X and Y are customizable based on user input.

**Comment by tomasonjo** [comment]
While you can't do that in the algorithm directly, you can preprocess your custom weights with cypher projection and then run the algorithm on this custom projected network.

**Comment by breakanalysis** [comment]
Like Tomas is saying, you can do this with as cypher projection as follows
```
CALL gds.graph.create.cypher('myGraph', 'MATCH (n) RETURN id(n) AS id', 'MATCH (n)-[r]->(m) RETURN id(n) as source, id(m) as target, -X * r.prop1 + Y * r.prop2 as weight')

CALL gds.alpha.kShortestPaths.stream(
  'myGraph', 
  {
    startNode: 42,
    endNode: 47,
    k: 3,
    relationshipWeightProperty: 'weight'
})
YIELD index, nodeIds, totalCost

```
