### ISSUE TITLE
Algorithm failed to complete Neo4jError: LIMIT: Invalid input. '3.0' is not a valid value. Must be a non-negative integer.

### ISSUE THREAD

**Issue by laurabravopriegue** [neo4j/graph-data-science#47]
Heya! 

I keep getting an error when trying to run any algorithm due to the value I select for "rows to show". The values I can select are fixed and always integers, but still I keep getting the error. I am completely new to Neo4j and I would really appreciate some help. 

Thanks

**Comment by vnickolov** [comment]
Hi, can you please share what statement is running?

Also try using `LIMIT 3`, the error message suggests that `LIMIT 3.0` is being used.

**Comment by laurabravopriegue** [comment]
<img width="692" alt="Screenshot 2020-05-26 at 16 49 09" src="https://user-images.githubusercontent.com/24269034/82915330-dfe98c80-9f70-11ea-9740-53382cad8790.png">

I am using limit 3... however I still get that error...

**Comment by Mats-SX** [comment]
@laurabravopriegue The tool you are using is called Graph Data Science Playground, or NEuler, and is not maintained by us who manage the GDS library directly. I've forwarded this bug report to the relevant people and it does seem to be a known issue.

Fortunately there's a way for you to work around it. Switch to the `Code` tab and either copy-paste each of the generated statements directly into your Neo4j Browser, or use the `Send to Neo4j Browser` button to generate a small Browser Guide where the queries will actually work.

Hope this helps and thanks for reporting the issue!

**Comment by craigtaverner** [comment]
Neo4j 4.0 is stricter on the processing of parameters that are supposed to be integers but are inadvertently floats. Unfortunately JavaScript does not have an integer type. It is possible that this is a JS app that is sending the `3` as `3.0` and Neo4j 3.x would have silently coerced this back into `3`, but Neo4j 4.0 no longer allows that. There is a function in the Neo4j JavaScript library to fix this.

**Comment by Mats-SX** [comment]
I have moved this issue over to https://github.com/neo4j-apps/neuler/issues/77

Please continue the correspondence there. If additional problems arise from using GDS, please feel free to open additional issues. Thanks for reporting this @laurabravopriegue!
