### ISSUE TITLE
bug: randomWalk algorithm using relationshipTypes parameter acts weird

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#48]
Looking at the [documentation](https://neo4j.com/docs/graph-data-science/current/alpha-algorithms/random-walk/), the random walk algorithm does not support `relationshipTypes` parameter. However, you can still run it, but it will behave weird. 

Create graph:

`CREATE (n:Node)-[:REL]->(:Node)
`

Load the graph into memory:

`CALL gds.graph.create('test','*',{test:{type:'*', orientation:'UNDIRECTED'}})`

And when I try to execute the algorithm:

```
MATCH (node)
CALL gds.alpha.randomWalk.stream('test', 
{ start: id(node), steps: 2, walks: 1,
relationshipTypes:['test'] }) YIELD nodeIds 
RETURN nodeIds
```

I get an error:

> Failed to invoke procedure `gds.alpha.randomWalk.stream`: Caused by: java.lang.IllegalArgumentException: No relationships have been loaded for relationship type 'RelationshipType{name='test'}'

This could be really confusing given that I have loaded all relationships under the alias test. However, if I load the algorithm using the string to define a single rel type like:

`CALL gds.graph.create('test_string','*','REL')
`
Running the algorithm with `relationshipTypes` works ok-ish:

```
MATCH (node)
CALL gds.alpha.randomWalk.stream('test_string', 
{ start: id(node), steps: 2, walks: 1,
relationshipTypes:['REL'] }) YIELD nodeIds 
RETURN nodeIds
```

nodeIds 
--
[38] 
[39]

**Comment by jjaderberg** [comment]
@tomasonjo Which version of GDS? I can't reproduce on master.

**Comment by tomasonjo** [comment]
I have tried it and it works on Neo4j 4.0.4 and GDS 1.2.1.
However, this error is still present in Neo4j 3.5.18 and GDS 1.1.1.

**Comment by jjaderberg** [comment]
@tomasonjo Could you try with 1.1.2?

**Comment by tomasonjo** [comment]
Works fine now, thanks!
