### ISSUE TITLE
Syntax proposal: syntax for multiple node labels

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#5]
Currently, we are using the pipe operator to allow projecting many node labels. My suggestion would be to try to be more consistent with that we use for relationship types:

Loading a single node label: `'Label'`
Loading many node labels: `['Label1', 'Label2', 'Label3']`

If we don't support multiple node label projection like:

`{Person: {properties:'seed_property'}, Hobby: {properties:'activity'}}`

I would suggest we use:

Using configuration map: `{Label: {label: ['Label1', 'Label2'], properties:['seed_property', 'activity'] }}`

This way node projection and relationship projection are more similar and IMO more understandable.

**Comment by s1ck** [comment]
Hi @tomasonjo Thanks for the proposal. 

We changed it to have node and relationship projections syntax closer aligned. You can now use the same full map syntax for both as described in the docs. However, applying additional filters when running an algorithm on a loaded graph still applies only to relationships (we'll add support for nodes filters, soon).

In the next release, you can use the following syntactic equivalent variants:
```
1) ['Label1', 'Label2', 'Label3']

2) 'Label1 | Label2 | Label2'

3) { Label1 : { label: 'Label1' }, /*...*/ }
```

1) and 2) are normalized to become 3)

Same for relationship types (except the different map syntax ofc).

I like your proposal about changing the map syntax, but we moved away from that for now, as we first need to clarify semantics, e.g. what does `{Label: {label: ['Label1', 'Label2'], ... ` mean in terms of query semantics? Exact match vs label subset vs one of etc.

**Comment by Mats-SX** [comment]
Is it actually better to support both 1 and 2, rather than just going for one of them? Both seem to be on an equal footing in terms of readability, understandability and complexity. To me, it would make more sense to constrain the API to make it so that the string values are never to be parsed, but are always describing a verbatim label (or relationship type) name.

@tomasonjo Do you have a particular opinion on whether allowing 2) is providing additional useful variation, or would more likely confuse a user as to why there are two very similar ways of expressing the same thing?

**Comment by tomasonjo** [comment]
IMHO it would be better to allow only one option to not confuse users, that is the `['Label1', 'Label2']` option, which is more consistent with relationship types.

As for configuration maps, the only pro I see in using 

single_map: `{Label: {label: ['Label1', 'Label2']}}`

vs

multi_map: `{Label1:{...}, Label2: {...}}` 

is to make sure that all the nodes are initialized with the same properties. (With relationship-types, for example, we make no such guarantees)

I have tried it, and the single_map option does not allow for post-filtering of nodes with the `nodeProjection` parameter as the alias **Label** contains both **Label1** and **Label2** nodes. I have also tried using the current pipe operator `'Label1 | Label2'`, and that does not allow for post-filtering either as it translates to:

```
{
  "Hobby | Person": {
    "properties": {

    },
    "label": "Hobby | Person"
  }
}
```

 I guess it has to do with something on a more deeper level of library.

In an ideal world I would like to be able to post-filter nodes, that have been loaded with a configuration map or an array, so I would definitely root for multi_map option. As for making sure that all nodes are initialized with the same properties, we could either display an error when loading a graph, or display an error when running the actual algorithm, that uses those properties(my preferred option). I would definitely avoid using some default values if the properties are not initialized as it could be very confusing, and the users would have no idea what is going on underneath the hood.

So I guess the real question is, will we support post-filtering of nodes in the near future or not?

**Comment by Mats-SX** [comment]
@tomasonjo Very good input! Thank you.

That's right, node filtering will be a feature in an upcoming version. Currently, we squash all nodes together into the same data structure and lose the label mapping. The design was built to allow this feature similarly to the relationship filtering, but there was not enough time for the first release. The configuration key for this will be `nodeLabels` and would only usable when calling an algorithm using a named graph (over which to filter).

On the error message: `nodeProjection` is never expected when using a named graph. I think that could be added to the error message to make it more clear between anonymous and named syntax.

For the syntactic sugars I tend to agree that omitting the `|`-separated syntax would reduce confusion. And while it's true that it may not always make sense to project the same properties for many different labels and/or relationship types we do see some use cases for this; for example when using time-bucketed rel types (like `T_2019`, `T_2020`, etc) that really have the same schema. In these circumstances the shorthand syntax would reduce repetitiveness by not forcing a user to repeat the same properties configuration in each relationship projection. So I think I'd argue to retain the shorthand syntax for `nodeProperties` and `relationshipProperties`.

**Comment by tomasonjo** [comment]
I would also argue that we should use the shorthand syntax for both relationships and node properties that could be later filtered with nodeLabel or (relationshipType?)

The only thing we lose due to shorthand syntax is:

```
CALL gds.graph.create('labelpropagation_example', 'Library', {
  DEPENDS_ON_DIRECTED: {
    type: 'DEPENDS_ON',
    // loading a directed network
    projection: 'NATURAL'
  },
  DEPENDS_ON_UNDIRECTED: {
    type: 'DEPENDS_ON',
    // loading an undirected network
    projection: 'UNDIRECTED'
  }
});
```

But I feel like there aren't many use cases where you want to project both directed and undirected relationships of the same type. And it brings more clarity as the graph can either be directed or undirected, but not both at the same time, which could also bring in some confusion.

**Comment by Mats-SX** [comment]
> I would also argue that we should use the shorthand syntax for both relationships and node properties that could be later filtered with nodeLabel or (relationshipType?)

I'm not sure I understand exactly. The properties are sub-elements of the projections. The projections are what you can filter on. Thus the properties are 'invisible' in the graph filtering feature.

For example:
```
CALL gds.graph.create('foo', ['A'], {
  KNOWS: {
    type: 'KNOWS',
    projection: 'NATURAL', 
    properties: ['foo', 'bar', 'baz']
  },
  KNOWN_BY: {
    type: 'KNOWS',
    projection: 'REVERSE', 
    properties: ['foo', 'grok', 'grist']
  }
})

// on KNOWS
CALL gds.pageRank.stream('foo', {relationshipTypes: ['KNOWS'], relationshipWeightProperty: 'bar'})
// on KNOWS in reverse direction
CALL gds.pageRank.stream('foo', {relationshipTypes: ['KNOWN_BY'], relationshipWeightProperty: 'grok'})
// on KNOWS in both directions
CALL gds.pageRank.stream('foo', {relationshipTypes: ['KNOWS', 'KNOWN_BY'], relationshipWeightProperty: 'foo'})
```

In the above, there's no way to reference (or filter) the properties for the different types. The user is assumed to know what properties were projected into what relationships (if unsure this can be retrieved from the graph catalog). The properties are part of the projected relationship, and subsequently they just 'follow along' wherever the relationship goes (into the algorithm, usually). Then in the algorithm configuration the properties can be requested as weights, if they exist (see example).

----

> But I feel like there aren't many use cases where you want to project both directed and undirected relationships of the same type. And it brings more clarity as the graph can either be directed or undirected, but not both at the same time, which could also bring in some confusion.

Actually, we model the syntactic shorthands as pure sugar, in the way that they always (deterministically) expand into the general long-form model. So your example above is perfectly valid. It may not make a lot of sense to use the graph in its entirety when projected like in your example, but it will save work by providing what is essentially _graph views_ where only a sub-part of all projected rels are being used at any time. This helps the library to save work by sharing nodes, for example.

**Comment by tomasonjo** [comment]
Ok, now I get it.

My point was that adding support for multiple rel types within a single alias would also be a great idea when dealing with bucketed rel types to avoid repetitiveness if later filtering is not needed. 

For example:

```
 {T_X:
    {type:['T_2019', 'T_2020'],
     projection: 'Undirected',
     properties:['foo', 'bar']}}
```
This is however not a big priority as you can always do them one by one... just an idea I had based on the short syntax to remove repetitiveness

**Comment by Mats-SX** [comment]
That's a good idea. We've been thinking along those lines as well. However, I would argue that we should be a little bit cautious at this point in introducing too many features within a completely new API. 

I think by limiting the `type` and `label` values to simple strings that just match label/rel-type names we're buying ourselves some freedom to later expand the syntax (in some backwards-compatible way) to a richer language in the future. But we should only do that if it actually turns out to be a pain point.

**Comment by s1ck** [comment]
We removed the option to use piped strings for both node labels and relationship types. The only valid arguments are:
* String, containing a single label  / rel type
* List of Strings
* Full Map syntax
