### ISSUE TITLE
Feature request: an API to query against a named graph

### ISSUE THREAD

**Issue by ThachNgocTran** [neo4j/graph-data-science#51]
In the [documentation](https://neo4j.com/docs/graph-data-science/current/management-ops/graph-catalog-ops/), there is no API that allows us to query a named graph. The reason for this feature is that given a Neo4j graph, we project into a subgraph for later running with, e.g. PageRank. Unfortunately, we have no way to verify if the projected named graph follows our expectation. One workaround is to export via `CALL gds.beta.graph.export('my-graph', { dbName: 'mydatabase' })`. However, this approach is very inconvenient: create an empty database, then stop it, then export data to it, then start it again.

I also asked on StackOverflow [link](https://stackoverflow.com/questions/62185075/neo4j-graph-data-science-library-how-to-cypher-query-against-a-named-graph-i).

**Comment by FlorentinD** [comment]
Couldn't you run the projection-queries on the neo4j-graph to check the structure of the subgraph, before creating the in-memory graph?

**Comment by ThachNgocTran** [comment]
> Couldn't you run the projection-queries on the neo4j-graph to check the structure of the subgraph, before creating the in-memory graph?

Thanks for the reply. That's one possibilty. However, later after running PageRank or some other algorithms on the projected graph in [mutate](https://neo4j.com/docs/graph-data-science/current/common-usage/running-algos/#running-algos-mutate) mode, we again want to explore the changes in the projected graph.

**Comment by FlorentinD** [comment]
For PageRank it would be enough to look at the mutated properties via f.i. a stream of `nodeId, propertyValue` right? 

When adding new relationships, something like a stream of relationships might be an idea.
I just think, that allowing to look at the changes done by `mutate` is sufficient, instead of the need to run arbitrary cypher queries against the in-memory graph.

**Comment by ThachNgocTran** [comment]
@FlorentinD It feels to me that the data structures of named graphs are very much different than those of normal Neo4j Graph. Please correct me if I'm wrong on this point.

Originally, I thought they could be the same. I.e. when creating a named graph, instead of flushing data to disk, it flushes to a dedicated memory. So in terms of functionalities (Neo4j Graph vs. Named graph), they should be the same, thus, cypher-able. All that were needed was to expose such API.

Implementing cypher-ability against named graphs seems to require much efforts. I guess I can live with it:

- Check/visualize the Cypher before projecting the named graph with that Cypher script.

- Use `gds.util.nodeProperty` to selectively view results of running PageRank in the named graph.

- In worst cases, export the named graph to an empty/offline Neo4j Graph, for permanently storing the result (without modifying the original Neo4j Graph) as well as further investigate. But this approach has a problem as posted [here](https://github.com/neo4j/graph-data-science/issues/50).

**Comment by FlorentinD** [comment]
You are correct, GDS uses creates a new graph in a graph format optimized for analytical workloads.
It is not impossible to implement this feature, and we will definitely keep your request in mind!
I will keep you updated, when `gds.graph.streamNodeProperties` is done.

Also I would recommend to look into the `write` mode, if you want to permanently store the result.

**Comment by Mats-SX** [comment]
This is possible to do using [Cypher on GDS](https://neo4j.com/docs/graph-data-science/current/management-ops/create-cypher-db/).
