### ISSUE TITLE
all pairs shortest paths

### ISSUE THREAD

**Issue by Assiam** [neo4j/graph-data-science#52]
Hello,

I suggest to return paths in all pair shortest path algorithm like apoc dijkstra.

Thank you

**Comment by AliciaFrame** [comment]
I think this has been addressed on the community forum: https://community.neo4j.com/t/shortest-paths-algorithms/19733/7

For now, you can use Yen's K shortest paths with k=1, but we've added a feature request to our roadmap to have our other pathfinding algorithms return paths as well.
