### ISSUE TITLE
Neo4j stops when running more than a few algorithms in sequence

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#58]
I've noticed this problem before when running lots of random walks or shortest paths in sequence, but it was too random to be able to provide an issue. Now I have finally come up with an example that consistently stops the database. This would probably not happen in practice as you rarely want to run 100 Pageranks in sequence, but you sometimes want to run more than a 100 random walks or shortest paths in sequence.

I am using Neo4j Desktop 1.2.9, Neo4j 4.0.6 Enterprise and GDS 1.2.2.

create a graph:

`CALL gds.beta.graph.generate('test',10000, 10)`

Run 100 Pageranks in sequence:

```
UNWIND range(0,100) as x
CALL gds.pageRank.stats('test') YIELD centralityDistribution
RETURN centralityDistribution
```

**Comment by tomasonjo** [comment]
Apparently this is only a problem on Neo4j Desktop, works fine in standalone

**Comment by Mats-SX** [comment]
Thanks for reporting this @tomasonjo. We had discovered this in internal testing and can confirm that this is indeed related to Neo4j Desktop. According to our investigation, a possible workaround is to avoid _starting_ the database using Neo4j Desktop (ie, pressing the :arrow_forward: Start button), and instead manually start it by running `bin/neo4j start` from the terminal (which can be opened using Neo4j Desktop).

We're in contact with the Neo4j Desktop team to find a permanent solution.

**Comment by galadrielbriere** [comment]
I'm also using Neo4j Desktop and had the same issue with the Louvain algorithm. Starting Neo4j from command line fixed it, thanks.

**Comment by tomasonjo** [comment]
With the 1.3.2 version of Neo4j Desktop the bug is fixed! :partying_face:
