### ISSUE TITLE
Buggy spanning tree examples wrt relationshipProjection

### ISSUE THREAD

**Issue by cybersam** [neo4j/graph-data-science#59]
This issue is related to https://github.com/neo4j/graph-data-science/issues/35.

The [documentation](https://neo4j.com/docs/graph-data-science/current/alpha-algorithms/minimum-weight-spanning-tree/#alpha-algorithms-minimum-weight-spanning-tree) still has a couple of examples where the `relationshipProjection` map contains properties that do not belong in the map. (There are a couple of other examples where map is OK.)

This caused this Stackoverflow question: https://stackoverflow.com/questions/62578246/routing-in-neo4j-for-osm-pointofinterest

**Comment by Mats-SX** [comment]
Hello @cybersam and thanks for reaching out! You're quite right, it seems we missed to backport the [documentation bugfix](https://github.com/neo4j/graph-data-science/commit/b297295ae3c34065fa9662d25ed9f24c16bf86bc) to the prior versions of the manual. I'll make sure that we do this. Thanks for pointing this out!

**Comment by Mats-SX** [comment]
The documentation has now been published with the correct syntax in the examples. Thanks again for notifying us on this!
