### ISSUE TITLE
Syntax proposal: SCC stream result parameters

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#6]
Currently the syntax is the following:

`CALL gds.alpha.scc.stream('scc_example') YIELD nodeId,partition`

To keep it more consistent with the overall library parameter names I propose we switch the YIELD syntax to:

`CALL gds.alpha.scc.stream('scc_example') YIELD nodeId,componentId`

This way it uses the same syntax as the wcc algorithm.

**Comment by Mats-SX** [comment]
I agree, this seems like a good change. It is in an alpha algorithm, however, so it falls into lower priority.

**Comment by DarthMax** [comment]
Fixed by #12
