### ISSUE TITLE
Node2Vec returns ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by bramble50** [neo4j/graph-data-science#61]
I've tried to run the `node2vec` algo from the 1.3.0 preview on my database but have not had much luck and keep getting an `ArrayIndexOutOfBoundsException`. Is this a bug?

Queries used:
* Create the in-memory graph
```
CALL gds.graph.create(
'my-graph',
{NodeName: {properties: ['property_1','property_2']}}, 
{EdgeName: {orientation: 'UNDIRECTED'}}
)
```
* Run Node2Vec
```
CALL gds.alpha.node2vec.stream('my-graph')
```

* Error:
```
Failed to invoke procedure `gds.alpha.node2vec.stream`: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4898 out of bounds for length 3598
```
I'd also tried directed edges and another node but get the same error, and tried tweaking the params of node2vec as well (e.g. reducing the walk length and the dimensions). The same in-memory graphs work with GraphSage and other algos without issue problem. 

Error occurs calling via both python and via Neo4J browser (I've not tried anything else).

Neo4J version: 4.1.0
GDS version: 1.3.0 Preview
Desktop version: 1.2.9

OS: Mac OSX 10.14

**Comment by vnickolov** [comment]
@bramble50 thank you for reporting this.

A couple of things that will be very useful for resolving this (if possible)

- A detailed stack trace from Neo4j log
- A dataset that you used to try out the algorithm

Thank you in advance.

**Comment by vnickolov** [comment]
Hi @bramble50 , we have managed to reproduce the issue, so no need to provide the requested additional details.
We have prepared a fix that will get into the repository in the next couple of days.

**Comment by bramble50** [comment]
@vnickolov great 🙂 Thanks!

**Comment by vnickolov** [comment]
@bramble50 thank you again for raising this, please be aware that although the fix is in, it is not released yet, you can build the artefact from the source and use it.
We do plan a release in the following few days though, please stay tuned.

**Comment by AliciaFrame** [comment]
We've just pushed a release that fixes your bug: https://github.com/neo4j/graph-data-science/releases/tag/1.3.0-alpha03

Let us know if you have any further questions!
