### ISSUE TITLE
Weighted WCC disclaimer

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#62]
I have seen a few cases where people use weighted WCC algorithm without the `threshold` parameter. Relationship weight parameter is only useful if it used in combination with the threshold parameter, otherwise it doesn't influence the results whatsoever. Should we maybe add a disclaimer if someone uses a `relationshipWeightProperty` parameter without the `threshold` parameter, that it won't make any difference?

**Comment by Mats-SX** [comment]
We responded to this by adding logging when `relationshipWeightProperty` is specified but `threshold` is not. That is probably very subtle. I agree that it would make sense to also update documentation.

**Comment by Mats-SX** [comment]
Conclusion is that we are fine with just logging this dependency of parameters. Please reach back if you strongly think we should reconsider.
