### ISSUE TITLE
Bug- wasserman-Faust algo

### ISSUE THREAD

**Issue by adfel70** [neo4j/graph-data-science#67]
****_basic_** Closeness Centrality algo, is**

_C (u) = (n − 1) / Σ d (u, v)_

while:
**u** is a node, **n** is the number of nodes in the same **subgraph**, **d(u,v)** is the shortest-path distance between another node v and u.

****_wasserman-Faust_** Closeness Centrality algo, is**

_C (u) =  ((n − 1) / Σ d (u, v)_) * ( (n-1) / (N-1) )

while:
**N** is the **total** node count

**_Inside the code_**
` return (componentSize / ((double) farness)) * ((componentSize - 1.) / (nodeCount - 1.));`

as we can see, __componentSize__ represent __n-1__, so there is no need to subtruct again __1__ from componentSize _(componentSize - 1.)_ 

https://github.com/neo4j/graph-data-science/blob/072af21db4475e757050eaaf686bf0d52079444c/alpha/alpha-algo/src/main/java/org/neo4j/graphalgo/impl/closeness/MSClosenessCentrality.java#L138

**fix to**
` return (componentSize / ((double) farness)) * ((componentSize) / (nodeCount - 1.));`

**Comment by DarthMax** [comment]
Hello @adfel70,
thanks a lot for reporting this bug. We have applied a fix here https://github.com/neo4j/graph-data-science/commit/3f818b81146d90f648a2a2cee0c9e453630a382f. The fix will be included in the next release. 
Best, Max
