### ISSUE TITLE
Documentation Bug: Missing node embedding chapter in algorithm overview

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#70]
On the https://neo4j.com/docs/graph-data-science/current/algorithms/, there is missing the 5.7. chapter titled Node embeddings.
![miss](https://user-images.githubusercontent.com/19948365/87664957-6860fe00-c766-11ea-92aa-edaa20a01bfa.png)

**Comment by jjaderberg** [comment]
@vnickolov fixed this, should be published soon. thanks for reporting!
