### ISSUE TITLE
IntPriorityQueue has wrong copyright and license

### ISSUE THREAD

**Issue by karussell** [neo4j/graph-data-science#71]
You should use the correct licensing and copyright for the original work of the IntPriorityQueue to ASF (lucene-solr project) instead of GPL (neo4j).

It was very likely copied with the wrong license header from the lucene repository. The original work was done in [SOLR-2092](https://issues.apache.org/jira/browse/SOLR-2092) from @yonik and is from 2010. (Please note that I'm not affiliated with him nor did he ask me to create this issue.)

You can see from the upHeap/downHeap code and comments that the class was copied but with the wrong license header. See the [lucene LongPriorityQueue](https://github.com/apache/lucene-solr/blob/master/solr/core/src/java/org/apache/solr/util/LongPriorityQueue.java#L203) and the one from [neo4j/graph-data-science](https://github.com/neo4j/graph-data-science/blob/master/alpha/alpha-core/src/main/java/org/neo4j/graphalgo/core/utils/queue/IntPriorityQueue.java#L213). Probably it was not directly taken from lucene but from the now archived [neo4j-contrib/neo4j-graph-algorithms repo](https://github.com/neo4j-contrib/neo4j-graph-algorithms/blob/3.5/core/src/main/java/org/neo4j/graphalgo/core/utils/queue/LongPriorityQueue.java) but this does not matter license-wise IMO and changing this to Apache license is only fair and IMO a no-brainer.

**Comment by s1ck** [comment]
Thanks for reporting this. We must have missed adding the correct license when taking over the code from the contrib project. We are usually aware of fairness, giving credit and using the correct license (see https://github.com/neo4j/graph-data-science/blob/master/core/src/main/java/org/neo4j/graphalgo/utils/CloseableThreadLocal.java for an example). 
Will fix this ASAP.

**Comment by karussell** [comment]
Thanks for the prompt response and taking these issues serious - shows only the professionalism of neo4j :+1: 

BTW: when we embed small snippets, ideas or source files we point this out in a NOTICE.md file additionally to the header, so additional "legal dependencies" can be easily seen like in a pom.xml/build.gradle file.

**Comment by s1ck** [comment]
That's a nice idea. Will bring it up with the team.
