### ISSUE TITLE
GraphSAGE inductive

### ISSUE THREAD

**Issue by ngshya** [neo4j/graph-data-science#72]
Hi there! 

I am trying to use the implementation of GraphSAGE. It is an inductive algorithm so I should be able to train the weights on a graph containing certain nodes and then use the trained model to make predictions on new nodes of the graph. How could I perform this task? 

On the [documentation page](https://neo4j.com/docs/graph-data-science/current/algorithms/alpha/graph-sage/index.html) I can find only an example to perform the training on the entire graph without any method to make predictions.

**Comment by vnickolov** [comment]
H @ngshya, 

Thank you for the question, you are right, as an `alpha` implementation it is not currently inductive.
We are working currently working on this and will post you with an update once it is released.
Also there is no predictions functionality, the generated embeddings need to be processed by a downstream machine learning pipeline.

I hope this helps.

**Comment by ngshya** [comment]
@vnickolov, thank you for the answer!

**Comment by vnickolov** [comment]
Hi @ngshya, 

We have added the inductive option, please see the [Model Catalog documentation](https://neo4j.com/docs/graph-data-science/1.4-preview/model-catalog/model-catalog/) and the changes to [Graph Sage](https://neo4j.com/docs/graph-data-science/1.4-preview/algorithms/alpha/graph-sage/).

The changes can be found in the latest [alpha release](https://github.com/neo4j/graph-data-science/releases/tag/1.4.0-alpha05).

Please let us know if there is anything we can help with.

**Comment by ngshya** [comment]
Top! Thanks!

**Comment by laxmimerit** [comment]
Hi,
I also could not find the prediction method. I have trained the GraphSage model and now want to generate embedding for a newly added node in the graph. I am following this tutorial
https://neo4j.com/docs/graph-data-science/current/algorithms/graph-sage/#_stream

It is currently in beta mode. I have added a new node as follows and wanted to generate embedding for it.
```
match (jeff:Person{name:'Jeff'})
match (laxmi:Person{name:'Laxmi'})
merge (laxmi)-[:KNOWS {relWeight: 5.0}]->(jeff)
```

Please advise how to do it?

**Comment by vnickolov** [comment]
Good morning @laxmimerit, 

Thank you for raising this question, you will need to project the new graph in-memory, adding nodes and relationships to the Neo4j database doesn't automatically update the in-memory graph. You can use the code from the example in the documentation, you may also want to drop the outdated in-memory graph using `gds.graph.drop('persons')` and re-create it:

```
CALL gds.graph.create(
  'persons',
  {
    Person: {
      label: 'Person',
      properties: ['age', 'height', 'weight']
    }
  }, {
    KNOWS: {
      type: 'KNOWS',
      orientation: 'UNDIRECTED',
      properties: ['relWeight']
    }
})
```

Once you have this you can run

```
CALL gds.beta.graphSage.stream(
  'persons',
  {
    modelName: 'graphSage'
  }
)
```

to get the embeddings for the new nodes.

I hope this helps.

**Comment by laxmimerit** [comment]
Thanks, it works.
Just for completeness. Ran this code to save the embeddings
```
CALL gds.beta.graphSage.write(
  'persons',
  {
    writeProperty: 'embedding',
    modelName: 'graphSage'
  }
) YIELD
  nodeCount,
  nodePropertiesWritten
```
