### ISSUE TITLE
Documentation Bug: Delta stepping shortest Path

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#73]
The alpha is missing in the stream syntax example.

> The following will run the algorithm and stream results: 
> 
> CALL gds.shortestPath.deltaStepping.stream(configuration: Map)
> YIELD nodeId, distance

And also the docs say that **delta** parameter is optional while executing the algorithm without this parameter returns an error:

> Failed to invoke procedure `gds.alpha.shortestPath.deltaStepping.stream`: Caused by: java.lang.IllegalArgumentException: No value specified for the mandatory configuration parameter `delta`

**Comment by FlorentinD** [comment]
Thank you for reporting this issue.

For the `delta` parameter I couldn't find a good default, so I changed this parameter to non optional.
I also found some more errors in the documentation like non matching result columns.
