### ISSUE TITLE
Failed to invoke procedure `gds.alpha.GraphSage.stream()` with `YIELD Embedding`

### ISSUE THREAD

**Issue by NC0DER** [neo4j/graph-data-science#82]
I am using the GDS Library version 1.3.0.
As mentioned in the dev manual regarding GraphSage, the results can be yielded as such.

![image](https://user-images.githubusercontent.com/20143137/94916479-6b42d380-04b7-11eb-8902-4b85d5588350.png)

However when I run this call:
```
CALL gds.alpha.graphSage.stream('GraphOfDocs', {
  degreeAsProperty: True
}) YIELD nodeId, embedding
RETURN gds.util.asNode(nodeId).key AS Issue, embedding
```
I get an error in the output:
![image](https://user-images.githubusercontent.com/20143137/94916552-8dd4ec80-04b7-11eb-9ff3-3f3b3e45f0e5.png)

However if I change the `embedding` to `embeddings` then the algorithm works as expected, producing a list of embeddings for each node in the named graph. I would also like to note that in contrast to GraphSage, using the parameter `embedding` instead of `embedding` works as intended when invoking `gds.alpha.node2vec.stream()` and `gds.alpha.randomProjection.stream()`.

Is this behavior intended on GraphSage?

**Comment by vnickolov** [comment]
@NC0DER thank you for the comment, 

This has already been addressed and available since [GDS 1.3.1](https://github.com/neo4j/graph-data-science/releases/tag/1.3.1)
