### ISSUE TITLE
gds.graph.writeRelationship does not include the relationship property

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#86]
Create graph:

```
CREATE (n:Node)-[:REL]->(:Node)<-[:REL]-(:Node)
```

Project graph:

```
CALL gds.graph.create('test','Node','REL')
```

Execute node similarity:

```
CALL gds.nodeSimilarity.mutate('test',{mutateProperty:'score',mutateRelationshipType:'SIM'})
```

And then finally write the relationship back to Neo4j:

```
CALL gds.graph.writeRelationship('test','SIM')
```

The stored relationship has no property score:

![das](https://user-images.githubusercontent.com/19948365/96874153-18d15300-1476-11eb-963c-d1ed44b86755.png)

**Comment by tomasonjo** [comment]
I've made even a simpler example to check if this is node similarity issue or not:

```
CREATE (n:Node)-[:REL{weight:1}]->(:Node)
```
then project

```
CALL gds.graph.create('test', 'Node', 'REL', {relationshipProperties:'weight'})
```

and write the rel back to neo4j:

```
CALL gds.graph.writeRelationship('test','REL')
```

And it has the same problem as it doesn't write the property back to Neo4j

**Comment by s1ck** [comment]
Have you tried `CALL gds.graph.writeRelationship('test', 'REL', weight')`?

**Comment by tomasonjo** [comment]
Didn't look hard enough, sorry for confusion

**Comment by s1ck** [comment]
No worries :)
