### ISSUE TITLE
Edge weights in Node2Vec

### ISSUE THREAD

**Issue by blackvvine** [neo4j/graph-data-science#88]
Hello,

I noticed that in the [documentation](https://neo4j.com/developer/graph-data-science/graph-embeddings/) for the three graph embedding algorithms currently supported, there is no configuration for setting the weights of edges. 

Specifically, we're interested in Node2Vec. In most implementations (e.g. original stanford paper [repo](https://github.com/aditya-grover/node2vec)) edge weights can be specified that are proportionate to the probability of picking an edge in the random walk. 

Is this currently supported? If not, any plans for supporting it in near future?

**Comment by seankrobinson** [comment]
Hey Iman,

Edge weights were added to GraphSage and FastRP in the latest pre-release of GDS 1.4 https://github.com/neo4j/graph-data-science/releases

**Comment by blackvvine** [comment]
Awesome, thank you.

**Comment by jjaderberg** [comment]
Hey @blackvvine it's true what @seankrobinson says that we added some support for weights in 1.4. But Node2Vec is not covered in that work. If you want weights in GDS Node2Vec you might want to re-open the issue.

If you do, please consider describing a use case. We love the "reference implementation" as much as the next guy, but there are lots of ways for us to spend our time--there are other papers and reference implementations, and even the occasional new thing that we dream up ourselves. So if weights in GDS Node2Vec matters to you, it would be helpful to have a use case to reason about as we plan future work.

**Comment by blackvvine** [comment]
Hi **@jjaderberg** , Thanks for the response. I personally think the weights are a very important aspect of the algorithm. 

For the use case, imagine a social graph where the relationship between people is scored (e.g. based on how well they know each other), and we want to create a similarity metric between them in terms of their network and social circle by embedding the nodes and then using vector distance. This is much more powerful than simply counting mutual neighbors, etc.

If the embedding does not reflect the information of how close people are (i.e. edge weights), you may end up with poor results because the algorithm treats two people barely knowing each other the same as two people who are married. The same issue is very likely to exist with any sort of clustering/classification/regression you do based on the embedding (e.g. recommendation engine that has no means to incorporate the people's closeness information).

**Comment by voutilad** [comment]
I believe node2vec edge weights was recently included in [v1.6.0](https://github.com/neo4j/graph-data-science/releases/tag/1.6.0)

**Comment by vnickolov** [comment]
@voutilad, @blackvvine indeed Node2Vec was updated to support `relationshipWeightProperty` in GDS 1.6, see the updated documentation [here](https://neo4j.com/docs/graph-data-science/current/algorithms/node2vec/#algorithms-embeddings-node2vec-syntax)
