### ISSUE TITLE
modelName in GraphSAGE

### ISSUE THREAD

**Issue by blackvvine** [neo4j/graph-data-science#89]
Hi, I am trying to run GraphSAGE in the v1.4alpha7 preview using the following query:

```cypher
CALL gds.beta.graphSage.stream({
	`nodeProjection`: "Person",
    `relationshipProjection`: {
    	eroad: {
          type: "KNOWS",
          orientation: "UNDIRECTED"
        }
    },
    `modelName`: "foobar"
})
```

But I keep getting the error:

```
Failed to invoke procedure `gds.beta.graphSage.stream`: Caused by: java.lang.IllegalArgumentException: No model with model name `iman` was found.
```

There is no guide in the docs about how the model name should be set, can somebody please help with this?

**Comment by blackvvine** [comment]
For anybody else, refer to:
/doc/asciidoc/algorithms/beta/graph-sage/graph-sage.adoc

**Comment by Mats-SX** [comment]
For the record, the referenced page can be viewed in its rendered format in our preview documentation: https://neo4j.com/docs/graph-data-science/preview/algorithms/graph-sage/
