### ISSUE TITLE
Unweighted Single Shortest Path

### ISSUE THREAD

**Issue by mneedham** [neo4j/graph-data-science#9]
I'm following the example from the [Single Shortest Path Documentation](https://neo4j.com/docs/graph-data-science/preview/labs-algorithms/single-source-shortest-path/):

```
CREATE (a:Loc {name: 'A'}),
       (b:Loc {name: 'B'}),
       (c:Loc {name: 'C'}),
       (d:Loc {name: 'D'}),
       (e:Loc {name: 'E'}),
       (f:Loc {name: 'F'}),
       (a)-[:ROAD {cost: 50}]->(b),
       (a)-[:ROAD {cost: 50}]->(c),
       (a)-[:ROAD {cost: 100}]->(d),
       (b)-[:ROAD {cost: 40}]->(d),
       (c)-[:ROAD {cost: 40}]->(d),
       (c)-[:ROAD {cost: 80}]->(e),
       (d)-[:ROAD {cost: 30}]->(e),
       (d)-[:ROAD {cost: 80}]->(f),
       (e)-[:ROAD {cost: 40}]->(f);
```

And I wanted to see what would happen if I exclude the weight from the computation. So if I do that, I have the following procedure call:

```
MATCH (n:Loc {name: 'A'})
CALL gds.alpha.shortestPath.deltaStepping.stream({
  nodeProjection: 'Loc',
  relationshipProjection: {
    ROAD: {
      type: 'ROAD'
    }
  },
  startNode: n,
  delta: 3.0
})
YIELD nodeId, distance
RETURN gds.util.asNode(nodeId).name AS destination, distance
```

which returns:

```
+------------------------+
| destination | distance |
+------------------------+
| "A"         | 0.0      |
| "B"         | 0.0      |
| "C"         | 0.0      |
| "D"         | 0.0      |
| "E"         | 0.0      |
| "F"         | 0.0      |
+------------------------+
```

I was expecting that it would treat the weight as being `1` between each node that has the `ROAD` relationship. 

So I'm not sure if my assumption is incorrect or if there's a bug that returns an unexpected result. Thoughts?

**Comment by Mats-SX** [comment]
At first glance, I would agree that this looks like a bug.

**Comment by MartinGroesbacher** [comment]
Was there ever anything done in this regard? Getting the same output still and its April 2021.....

**Comment by eivindkopperud** [comment]
I am doing some benchmarking on some data sets, and stumbled upon this issue too. Is the execution time reliable even though the path lengths aren't?

**Comment by s1ck** [comment]
We are moving delta stepping into the beta or product tier in the next release. Since it'll be a different implementation, I suggest performing benchmarks or testing using the upcoming version. I will close this for now. Feel free to open new issues once delta stepping is out of alpha and show unexpected, wrong or slow behavior. Thanks!

**Comment by s1ck** [comment]
@MartinGroesbacher @eivindkopperud We have re-implemented delta stepping and moved it to the product-tier. It returns the expected results for weighted and unweighted graphs.

@eivindkopperud re benchmarking: We chose a different implementation for the product-tier which outperforms the previous alpha implementation. I suggest re-running your benchmarks.

Thanks for your inputs.
