### ISSUE TITLE
Community users can only store one model in the catalog

### ISSUE THREAD

**Issue by sepehrafla** [neo4j/graph-data-science#90]
We have a startup license but when trying to train we got this error: 

Failed to invoke procedure `gds.beta.graphSage.train`: Caused by: java.lang.IllegalArgumentException: Community users can only store one model in the catalog

**Comment by AliciaFrame** [comment]
Hi @sepehrafla - GDS Enterprise Edition is a separate license from our database enterprise edition, and not covered by default as part of the free start up license program.

**Comment by laxmimerit** [comment]
Hi,
That I understand that I can not use Community edition for more than one model. How can I delete that single model? so that I can load another model?

**Comment by laxmimerit** [comment]
To Remove already stored model in gds
```
call gds.beta.model.drop('exampleTrainModel')
```

Otherwise, list out the stored model
```
call gds.beta.model.list()
```
and then remove the stored model.

**Comment by Mats-SX** [comment]
@laxmimerit You can find a full reference of operations in [the GDS manual](https://neo4j.com/docs/graph-data-science/current/model-catalog/model-catalog/#model-catalog-ops).
