### ISSUE TITLE
How to install Graph Data Science (GDS) library embedded in Java applications

### ISSUE THREAD

**Issue by santipongth** [neo4j/graph-data-science#91]
Hi, friends

I would like to create a Java project including Neo4j and Graph Data Science (GDS) library. I used Eclipse editor to develop my project. The steps of including GDS library in Eclipse are shown as follows:

I used Neo4j 4.1.3 and GDS library 1.3.0.

1. including the core module using Maven:
```
<dependency>
  <groupId>org.neo4j.gds</groupId>
  <artifactId>core</artifactId>
  <version>1.3.0</version>
</dependency>
```
2. Adding  ```dbms.security.procedures.unrestricted=gds.* ``` in the conf/neo4j.conf file
3. Adding  ```dbms.security.procedures.whitelist=gds.*``` in the conf/neo4j.conf file
4. Restart a standalone Neo4j server using Eclipse.

When I check my installation using cypher, I found a **problem**.

![problem](https://user-images.githubusercontent.com/30307646/99006828-686de080-2543-11eb-833d-a0833deb3447.PNG)

Please help me to solve this problem.
Thank you very much.

**Comment by vnickolov** [comment]
Hi @santipongth, 

The library consist of a number of artifacts that are published to Maven, including `core` will not bring them all.

I would advise to include `proc` which will bring the rest of the artifacts as transitive dependencies. i.e.
```
<dependency>
  <groupId>org.neo4j.gds</groupId>
  <artifactId>proc</artifactId>
  <version>1.3.0</version>
</dependency>
```

PS: You can use the latest versions `1.4.0` 

I hope this helps

**Comment by vnickolov** [comment]
Also, depending on what you are trying to achieve you may not need to include a dependency to the GDS library to your project but use Cypher queries via Neo4j Driver.

If you want to develop new procedures then you will need to make sure that you update the jar in the `plugins` directory with the one you compile.

**Comment by Mats-SX** [comment]
Extending the project by writing your own procedures is possible, but this is considered advanced, and we do not have much in terms of documentation to support you. A much simpler solution to develop your own algorithms would be to write them towards our Pregel API, which offers tooling support for generating procedures, and which we have proper documentation for: https://neo4j.com/docs/graph-data-science/current/algorithms/pregel-api/

**Comment by santipongth** [comment]
> 
> 
> Hi @santipongth,
> 
> The library consist of a number of artifacts that are published to Maven, including `core` will not bring them all.
> 
> I would advise to include `proc` which will bring the rest of the artifacts as transitive dependencies. i.e.
> 
> ```
> <dependency>
>   <groupId>org.neo4j.gds</groupId>
>   <artifactId>proc</artifactId>
>   <version>1.3.0</version>
> </dependency>
> ```
> 
> Also in addition to the configuration changes you have made you need to copy the [release jar](https://github.com/neo4j/graph-data-science/releases/download/1.3.0/neo4j-graph-data-science-1.3.0-standalone.jar) to the `plugins` directory of the Neo4j database.
> 
> PS: You can use the [latest version](https://github.com/neo4j/graph-data-science/releases/tag/1.4.0) `1.4.0`; in that case you need to update the version in the Maven config too.
> 
> I hope this helps

I try to do as you told but I got the same problem. My objective is that I want to install GDS library in Eclipse to make a standalone Neo4j server and I want to call graph algorithm via Cypher language with Neo4j Driver. I do not want to use the Neo4j desktop as server because I have to develop some modules in the embedded Java application. Do you have any solutions for me. In my Java project does not have the plugins directory. Where can I copy the released Jar of my Java application in Eclipse.

Please help me, Thank you.

**Comment by vnickolov** [comment]
Hi @santipongth 

Thank you for the explanation, in this case you wouldn't need the Maven dependencies at all, you would need to do the settings as you described:
`Adding dbms.security.procedures.unrestricted=gds.* in the conf/neo4j.conf file`

And copy the standalone released jar to the Neo4j `plugins` directory.
Please refer to the Installation of the GDS Plugin onto a Neo4j Server here: https://neo4j.com/docs/graph-data-science/current/installation/#_neo4j_server

I hope this helps.

**Comment by santipongth** [comment]
> Hi @santipongth
> 
> Thank you for the explanation, in this case you wouldn't need the Maven dependencies at all, you would need to do the settings as you described:
> `Adding dbms.security.procedures.unrestricted=gds.* in the conf/neo4j.conf file`
> 
> And copy the standalone released jar to the Neo4j `plugins` directory.
> Please refer to the Installation of the GDS Plugin onto a Neo4j Server here: https://neo4j.com/docs/graph-data-science/current/installation/#_neo4j_server
> 
> I hope this helps.

Thank you for your answers. You misunderstand me. I need to use the Maven dependencies because I want to develop some functions that is embedded in Neo4j and I also need to use the GDS library. Could you please suggest me for installing GDS library using Maven in Eclipse. After I start the Neo4j server in Eclipse, I will call a graph algorithm via Cypher language. Thai is a reason that I do not want to use Neo4j desktop. Please explain me to install GDS library by using Maven and call GDS library via Cypher with Neo4j driver.

Thank you very much

**Comment by santipongth** [comment]
> 
> 
> Extending the project by writing your own procedures is possible, but this is considered advanced, and we do not have much in terms of documentation to support you. A much simpler solution to develop your own algorithms would be to write them towards our Pregel API, which offers tooling support for generating procedures, and which we have proper documentation for: https://neo4j.com/docs/graph-data-science/current/algorithms/pregel-api/
> 
> (And for a standard installation, please see the [installation docs](https://neo4j.com/docs/graph-data-science/current/installation/#_neo4j_server).)

@Mats-SX Thank you for your reply. I do not want to extend my project by writing new procedures. I just want to call graph algorithms in Graph Data Science (GDS) on Java applications. Do you have any solutions to call graph algorithms? However, I try to install GDS library on my Java application and call it using Cypher in Neo4j browser. But I found a problem.

 ```There is no procedure with the name `gds.list` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.```

After a reboot, I try to show a list of **currently active settings** in neo4j.conf from Cypher on Neo4j Browser:

```CALL dbms.listConfig()```

**The value of "dbms.security.procedures.unrestricted" correctly shows on the browser.**

Then, I call it again by using the command below. I found an error.

```CALL gds.list()```

**Comment by Mats-SX** [comment]
@santipongth All right. Well, it isn't enough to just put the procedures on the classpath. You have to register them with your Neo4j DBMS. In a server deployment, you would move the (shaded) JAR into the `plugins` directory to accomplish that.

When you say that you are "starting Neo4j from Eclipse", what does that actually mean? Are you running a startup script from the IDE terminal (such as `bin/neo4j start`), or are you calling some `main` method from a class you wrote that instantiates the DBMS, or are you running Neo4j from a test? 

Depending on how you start Neo4j, there are different ways for you to achieve the registration of your procedures. [Here](https://github.com/neo4j/graph-data-science/blob/439816caa21cc0467d63bd4f3a5977a3e23a752c/neo4j-adapter/src/main/java/org/neo4j/graphalgo/compat/GraphDatabaseApiProxy.java#L55-L60) is some code that we use to register procedures with Neo4j in a programmatic way. You'll need access to an instance of `GraphDatabaseAPI` as well as the `Class<>` instances of the procedures you want to use. This can get pretty verbose to use, as you can see in for example [this test](https://github.com/neo4j/graph-data-science/blob/439816caa21cc0467d63bd4f3a5977a3e23a752c/proc/src/test/java/org/neo4j/graphalgo/ListProcTest.java#L268-L336).

Please tell us more about how exactly you are starting Neo4j and we can try to guide you further.

**Comment by santipongth** [comment]
@Mats-SX I really appreciate your reply. Let me explain the steps of installation for developing my Java application.

1. I start to setup my Java Application including the **Neo4j and GDS** library jars using Eclipse editor. I followed this [document](https://neo4j.com/docs/java-reference/current/java-embedded/include-neo4j/#java-embedded-setup). I show my source code below. I also define my embedded DBMS **configuration** in the `neo4j.conf` file. [neo4j.conf.txt](https://github.com/neo4j/graph-data-science/files/5545444/neo4j.conf.txt)

![aa](https://user-images.githubusercontent.com/30307646/99235956-d42ba400-27f6-11eb-809e-f10c61333c00.PNG)

In my project structure, there are no `plugin` directory.

2. I add the dependencies to my project in the pom.xml file.
```
<dependency>
<groupId>org.neo4j</groupId>
<artifactId>neo4j</artifactId>
<version>4.1.4</version>
</dependency>
<dependency>
<groupId>org.neo4j.gds</groupId>
<artifactId>proc</artifactId>
<version>1.4.0</version>
</dependency>
<dependency>
<groupId>org.neo4j.gds</groupId>
<artifactId>core</artifactId>
<version>1.4.0</version>
</dependency>
```
3. I add syntaxs in neo4j.conf to use GDS library
```
dbms.security.procedures.unrestricted=apoc.*, gds.*
dbms.security.procedures.whitelist=apoc.*, gds.*
```
4. I start a standalone Neo4j server using Eclipse. In another way, you can build and run a project using Maven as well. In the below picture, I start a standalone Neo4j server using `Maven`
```
mvn compile
mvn exec:java -Dexec.mainClass={myPackageHere}.App
```
![bb](https://user-images.githubusercontent.com/30307646/99237676-1c4bc600-27f9-11eb-9cd0-cd3a7a5797fa.PNG)

5. Then, I try to check the status of GDS via Cypher language using Neo4j Browser. I found an error.
![problem2](https://user-images.githubusercontent.com/30307646/99238362-ed821f80-27f9-11eb-9dcd-b3060116fc80.PNG)

My objective is that I want to implement my Java applcation as a standalone Neo4j server. I do not want to setup a project via [Neo4j desktop or Community server](https://neo4j.com/download-center/#desktop). I want to use some graph algorithms in GDS library under **only** my Java application, and call graph algorithms using **Neo4j Java driver with Cypher language according to my java application**. Please let me know that you have any solutions to help me to achieve my goal.

Thank you for your consideration. If you have any questions or concerns, don’t hesitate to let me know. I am looking forward to hearing from you.

Best regards,

**Comment by Mats-SX** [comment]
@santipongth Very good, that shows that you are using the `main` method way of starting the server. In your `main` method you must then also register procedures. If you insert this code below your line 15 in `Server.java`, you should find a couple of procedures available in Neo4j Browser:

```
var proceduresRegistry = ((GraphDatabaseAPI) graphDb)
    .getDependencyResolver()
    .resolveDependency(GlobalProcedures.class, DependencyResolver.SelectionStrategy.SINGLE);
var procsToRegister = List.of(
    GraphListProc.class,
    GraphCreateProc.class,
    PageRankStreamProc.class
);
for (Class<?> procedureClass : procsToRegister) {
    proceduresRegistry.registerProcedure(procedureClass);
}
```

You can test that by running `CALL gds.list()` and it should show I think 7 GDS procedures.

In order to register _all_ GDS procedures, you will have to list them all in that list. That can be done statically by adding each class to the list in the way I've started, but it will be a lot of tedious work. I recommend that you instead do a reflection-based scan of the classpath to find them all. You will find an example of that in this test class: https://github.com/neo4j/graph-data-science/blob/439816caa21cc0467d63bd4f3a5977a3e23a752c/doc/src/test/java/org/neo4j/graphalgo/doc/AppendixAProcedureListingTest.java#L54-L61

**Comment by santipongth** [comment]
@Mats-SX I really appreciate for your help. It works well for me.

![re](https://user-images.githubusercontent.com/30307646/99266918-985b0380-2823-11eb-82dc-66824b11c6d5.PNG)

However, I have **two questions** to ask you.
1.  Do I have to also register **functions** inside the `main`  method of the `Server.java` file? I mean the last line that I use an arrow to point it.
```
for (Class<?> procedureClass : procsToRegister) {
    proceduresRegistry.registerProcedure(procedureClass);
    --->proceduresRegistry.registerFunction(procedureClass);
}
```
2. I try to follow what you recommended me to do a reflection-based scan instead. My question is where can I get the `registerProcedures` and `registerFunctions` methods?

https://github.com/neo4j/graph-data-science/blob/439816caa21cc0467d63bd4f3a5977a3e23a752c/doc/src/test/java/org/neo4j/graphalgo/doc/AppendixAProcedureListingTest.java#L116

https://github.com/neo4j/graph-data-science/blob/439816caa21cc0467d63bd4f3a5977a3e23a752c/doc/src/test/java/org/neo4j/graphalgo/doc/AppendixAProcedureListingTest.java#L131

Best regard,

**Comment by Mats-SX** [comment]
@santipongth For the function classes you need to call `registerFunction()`, that's right. We use a naming convention where the function classes are called `SomethingFunc` like `AsNodeFunc` or `GraphExistsFunc`.

If you open our project in Eclipse you can navigate around and find the sources for these function from the `AppendixAProcedureListingTest`. They are little more than convenience functions for the same code as I exemplified above; that is, getting a `DependencyResolver` via the `GraphDatabaseAPI`, resolving the `GlobalProcedures` and then calling methods on that.

**Comment by santipongth** [comment]
> 
> 
> @santipongth For the function classes you need to call `registerFunction()`, that's right. We use a naming convention where the function classes are called `SomethingFunc` like `AsNodeFunc` or `GraphExistsFunc`.
> 
> If you open our project in Eclipse you can navigate around and find the sources for these function from the `AppendixAProcedureListingTest`. They are little more than convenience functions for the same code as I exemplified above; that is, getting a `DependencyResolver` via the `GraphDatabaseAPI`, resolving the `GlobalProcedures` and then calling methods on that.

Thank you very much.

**Comment by Mats-SX** [comment]
@santipongth You're very welcome. A word of caution: you are using a way of extending our project that is somewhat volatile, and not something we consider public API in the same way we do with our documented API (ie, procedures and Pregel). Now, we do still avoid doing dramatic changes in the internals between minor releases to not cause issues for library authors such as yourself, but we cannot guarantee the stability of classes you may reach for in your code. This means that updating between versions could come with some migration work. If you do find any issues, please do reach out and we'll see how we can help.

That being said, is it fair to say that your current problems are now resolved, and we can close this issue?

**Comment by santipongth** [comment]
@Mats-SX Thank you for your advice. I can say that my current issues are resolved.

Best regard,

**Comment by xiz675** [comment]
Hi there,

I have similar settings as you:
1. I downloaded graph-data-science jar and put it under plugins folder;
2. I added these two lines to neo4j.conf 
     dbms.security.procedures.unrestricted=gds.*
     dbms.security.procedures.whitelist=gds.*
3.  I started the server in java code:
   
![屏幕快照 2021-06-18 下午10 01 04](https://user-images.githubusercontent.com/32505316/122631451-ca199e80-d080-11eb-86af-8a6118abb54d.png)

But I got an error when I started the server:
![屏幕快照 2021-06-18 下午10 03 33](https://user-images.githubusercontent.com/32505316/122631513-0baa4980-d081-11eb-84c7-8baa7de19342.png)

Anyone can help me with this ?

**Comment by Mats-SX** [comment]
For the record, @xiz675's issue was resolved by updating Neo4j version: https://github.com/neo4j/graph-data-science/issues/117#issuecomment-868209781

**Comment by wjholden** [comment]
Hello everyone. This discussion was really helpful to me in writing my [Neo4j term project](https://wjholden.com/neo4j-ospf.pdf) in a class I just completed. My code is at https://github.com/wjholden/OSPF-Analyzer.

I did a few things differently from the discussion above. I have described these in more detail in section 2 of my term paper, but I will outline my main findings here:

1. I needed to pull in `org.neo4j.gds:core`, `org.neo4j.gds:proc`, and (obviously) `org.neo4j:neo4j` from Maven.
2. A HashMap of settings was the easiest way for me to configure the DBMS using the `setConfigRaw` method. I didn't want to load a configuration file and I couldn't figure out how to whitelist procedures another way. `setConfigRaw` allows you to configure your DBMS using the same syntax you would have seen in Neo4j Desktop.
3. I wrote my own `registerGds` method. You need to look in `org.neo4j.gds.embeddings` and `org.neo4j.gds.paths` for some algorithms. The functions (classes ending in `Func`) do not share a common supertype, so I just defined an array of the ones I needed.
