### ISSUE TITLE
GraphSAGE train metrics

### ISSUE THREAD

**Issue by bastiansg** [neo4j/graph-data-science#92]
Hi!

I am running GraphSAGE implementation with multiple node labels (following documentation from https://neo4j.com/docs/graph-data-science/current/algorithms/graph-sage/), but I can't see any metrics anywhere, I want to see loss or accuracy.

I am using neo4j-graph-data-science 1.4.0 and neo4j 4.2.0

**Comment by Mats-SX** [comment]
Hello @bastiansg and thanks for reaching out to us!

Unfortunately, we do not publish the internal metrics like loss or accuracy during computation of GraphSage in the current released versions in the standard API. However, we do log the loss for each `epoch` on `DEBUG` level in the `debug.log`. So if you you turn on debug logging you would be able to inspect the loss progression via these log statements.

We will consider adding API for exposing metrics such as these in our upcoming releases. I will keep this card open for that feature request, if that makes sense to you.

**Comment by vnickolov** [comment]
@bastiansg we have added metrics to the modelInfo in GDS 1.6, you can find the documentation and some examples [here](https://neo4j.com/docs/graph-data-science/current/algorithms/graph-sage/#algorithms-embeddings-graph-sage-syntax)

**Comment by bastiansg** [comment]
Thanks @vnickolov !!

**Comment by yatharth-malik** [comment]
Hi
It'd be really helpful if we have epoch-wise metric report for other learning algorithms as well. Node2vec being one such use case.
