### ISSUE TITLE
Model catalog community check

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/graph-data-science#95]
As the model catalog is restricted to only a single model for the community version of the GDS, it would make more sense to first check if there is an existing model already in the model catalog and only then train the model. The current setup is that the GDS first trains the model and then checks the restriction. This could be a bit annoying if you are waiting for x time only to show up with an error.

**Comment by tomasonjo** [comment]
On a similar note, I used the same model name for training and it didn't check if a model already exists under the same name. So for the enterprise version, it would make sense to first check if a model with the same name already exists in the model catalog before the training.

**Comment by s1ck** [comment]
Thanks @tomasonjo for reporting this. It has already been fixed in https://github.com/neo4j/graph-data-science/commit/c7e02a016b7ea5e12e502221918f8f176d6328bc
