### ISSUE TITLE
Perhaps Official document parameter error 

### ISSUE THREAD

**Issue by hua7448** [neo4j/graph-data-science#99]
when I follow the official documentations of GDS
places:  https://neo4j.com/docs/graph-data-science/current/algorithms/article-rank/
![image](https://user-images.githubusercontent.com/60468366/106412028-a236ef00-6481-11eb-8bd2-394eda4b038c.png)

![image](https://user-images.githubusercontent.com/60468366/106411711-db229400-6480-11eb-82c9-58b00d390f6f.png)
is the parameters of this iterations wrong?

my neo4j version : 4.2.3
GDS version : 1.4.1-standalone

**Comment by hua7448** [comment]
mayby it want to write   maxIterations  ?

**Comment by vnickolov** [comment]
@hua7448 thank you for pointing this out, yes, the documentation for ArticleRank is incorrect, the configuration parameter is  `maxIterations`.
